### ISSUE TITLE
Coordinating with wasm-bingden about versions and list of NPM dependencies

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#101]
This is related to https://github.com/rust-lang-nursery/rust-wasm/issues/34 and https://github.com/rust-lang-nursery/rust-wasm/issues/36, but I'd like to propose a strawman idea here.

Right now wasm-bindgen has the ability to say where you're importing functionality from:

```rust
#[wasm_bindgen(module = "foo")]
extern {
    // ...
}
```

If `module = "..."` is omitted it's assumed to come from the ambient environment (aka the browser). Otherwise `foo` is interpreted as an ES module directive and that's where items are imported from in the generated JS that wasm-bindgen emits.

The wasm-bindgen output is pretty "dumb" right now in that it's just bland ES module information, it doesn't currently attempt to give extra information like verison requirements for NPM packages. But that's where wasm-pack comes in! Ideally wasm-bindgen would emit information that wasm-pack later reads, parses, and emits a package.json for.

So I'd propose something like:

* Add support for `version = "..."` next to `module = "..."` in wasm-bindgen
* For all `module = "..."` directives that *don't* start with `.`, require that `version` is listed
* Emit a new section in the wasm executable in the wasm that `wasm-bindgen` emits in the format:
  * The section name is `__wasm_pack_unstable`
  * The section format is a list of elements. Each element is prefixed with 4 bytes of how long it is and then the rest of the data is a JSON payload.
  * The JSON payload for each element is currently `{ "module": "string", "version": "string" }`
* When `wasm-pack` executes it slurps up the `__wasm_pack_unstable` section, if present, and emits these packages into the `package.json` that's generated.

An example of using this would look like:

```rust
#[wasm_bindgen(module = "moment", version = "2.0.0")]
extern {
    type Moment;
    fn moment() -> Moment;
    #[wasm_bindgen(method)]
    fn format(this: &Moment) -> String;
}

#[wasm_bindgen]
pub fn run() -> String {
    moment().format()
}
```

And `wasm-pack` would automatically generate a `package.json` with:

```json
{ 
   "dependencies": {
        "moment": "2.0.0"
    }
}
```

I'm definitely up for changing anything here, this is just an initial strawman! I'd love to hear others' thoughts on this as well.

**Comment by Pauan** [comment]
> Add support for version = "..." next to module = "..." in wasm-bindgen

Shouldn't that be the responsibility of `package.json` though?

**Comment by alexcrichton** [comment]
@Pauan indeed! Although `wasm-pack` is the one generating `package.json`, right? So it just needs to know what to fill in?

**Comment by Pauan** [comment]
@alexcrichton Please correct me if I'm wrong, but my understanding is that the plan is that Rust crates will include a `package.json` file at the same place where they contain `Cargo.toml`, and `wasm-pack` will then merge all of those `package.json`s together to create the final `package.json`.

So the version information would be in the crate's `package.json` file, not inside of the crate's Rust code. That's what I meant by "isn't that the responsibility of `package.json`"?

**Comment by alexcrichton** [comment]
Oh I was thinking that intermediate Rust crates would not ship `package.json`, and that would explain the confusion!

Currently wasm-bindgen knows very little about Rust crates and dependencies, it purely takes one wasm file as input. It could be the case that `#[wasm_bindgen]` slurps up a a crate's `package.json` and inserts it into a custom section to later be read by `wasm-bindgen`, but AFAIK `wasm-pack` has no ability to walk the dependency graph and locate instances of `package.json`

I'm also not certain we'd want to ship `package.json` with `Cargo.toml` because that would imply that the crate is a standalone package for NPM which likely isn't?

**Comment by ashleygwilliams** [comment]
@Pauan the goal was for wasm-pack to have a version parser and solver :)

@alexcrichton need to read the backscroll a little more closely but i think in general i agree with ur approach

**Comment by ashleygwilliams** [comment]
ok so, addressing a few of @Pauan's concerns 

> And a package.json can only contain a single version per package.

a `package.json` can contain a single semver expression per package.

> And there's a bunch of other package.json metadata which is useful as well: such as the minimum Node/npm version, what platforms it supports, the CPU architecture, etc.

this is vaguely true but none of it is enforced by the npm client. this info could be kept anywhere (most people use a `.travis.yml`)

<hr/>

i'm quite strongly against requiring a `package.json` in a Rust crate. it would both not be functional and not aligned with the goals of the project that i clearly state in my blog post on this tool. i'm quite certain that we can avoid requiring it, a single manifest file per project is **plenty**

**Comment by ashleygwilliams** [comment]
yeah i think leaving resolution of deps to wasm-pack makes the most sense here, tho if we really wanted we could do it in a crate that both tools could leverage if we wanted to

**Comment by alexcrichton** [comment]
I've opened a PR for this at wasm-bindgen at https://github.com/rustwasm/wasm-bindgen/pull/161

**Comment by Pauan** [comment]
> @ashleygwilliams the goal was for wasm-pack to have a version parser and solver :)

Okay, that sounds fine.

Though I wonder if wasm-pack actually needs a version solver. Given these Rust crates...

```rust
#[wasm_bindgen(module = "moment", version = "^2.0.0")]
```

```rust
#[wasm_bindgen(module = "moment", version = "^2.4.0")]
```

...couldn't wasm-pack combine all the versions together, like this:

```json
{
  "dependencies": {
    "moment": "^2.0.0 ^2.4.0"
  }
}
```

That would leave the version solving up to npm/yarn/whatever.

The biggest downside I can see is that it would result in inferior error messages in the case of conflicts. But it might be good as a temporary solution.

> a package.json can contain a single semver expression per package.

Indeed, that's what I meant.

> i'm quite strongly against requiring a package.json in a Rust crate. it would both not be functional and not aligned with the goals of the project that i clearly state in my blog post on this tool. i'm quite certain that we can avoid requiring it, a single manifest file per project is plenty

I don't have a strong preference either way (between `package.json` and an attribute), though I am curious why you are strongly against `package.json`

**Comment by Pauan** [comment]
One of the downsides of the attribute is that it makes it very unclear what dependencies the package has.

For Rust crates you can simply look at `Cargo.toml` and know instantly all of the dependencies. With the `wasm_bindgen` attribute you have to actually look through all of the source code to find the dependencies.

There is also the possible alternative of specifying the npm dependencies in `Cargo.toml`, so that way it doesn't require a separate file, and it's more intuitive for Rust programmers.

**Comment by ashleygwilliams** [comment]
@Pauan i'm confused... 

```
{
  "dependencies": {
    "moment": "^2.0.0 ^2.4.0"
  }
}
```

is not a valid `package.json` so that's def not something we will do

**Comment by Pauan** [comment]
@ashleygwilliams What do you mean? Node's semver allows a space between versions, which it treats as logical and (i.e. set intersection).

**Comment by ashleygwilliams** [comment]
huh @Pauan i guess that is technically true! tho it's a dangerous move because i don't actually know what npm does if the intersection represents a set with no members... i think fundamentally this is something we'd probably want to sort at the wasm-pack level, mostly because i don't want to allow the publish of a package that is not installable

[edit, i was curious so i checked] npm does this:
```
Ashleys-MacBook-Pro-2:test ag_dubs$ vi package.json
Ashleys-MacBook-Pro-2:test ag_dubs$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for lodash@^1.0.0 ^2.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'test'
npm ERR! notarget
```

which is not super useful. in all my years working at npm i have to be honest i never saw ANY package.json declare deps like that, so for that reason alone and my desire to not surprise people, i would opt to not do that

**Comment by alexcrichton** [comment]
Pedagogically I don't have too much of an opinion either way on where this info lives. Technically I'd prefer the attribute because it means I don't have to pull a TOML parser into wasm-bindgen.

**Comment by sendilkumarn** [comment]
Ergonomically 😜

**Comment by ashleygwilliams** [comment]
@alexcrichton let's stick with what we have for now... if it turns out that people want something else, we can build it later, based on people's actual experience, and not just guessing ;)

**Comment by Pauan** [comment]
> @ashleygwilliams let's stick with what we have for now... if it turns out that people want something else, we can build it later, based on people's actual experience, and not just guessing ;)

I strongly disagree with this. A lot of people are already using wasm-bindgen and wasm-pack, and so it will quickly become a de-facto standard, which will be very hard to change later.

If we're going to experiment with different things, we should do so *now*. As I said, there are benefits to using `Cargo.toml`, so we shouldn't just dismiss it as a possibility.

**Comment by mgattozzi** [comment]
Modifying a config file for a different tool other than what that file is for does not sit well with me. Cargo.toml is used to modify how cargo works, not wasm-pack/wasm-bindgen. If you want to do build config things I highly recommend it either be in it's own config file or build.rs as is current convention for Rust projects.

**Comment by mgattozzi** [comment]
@Pauan Oh I didn't even know about the metadata field! Thanks for letting me know about that :D

**Comment by Pauan** [comment]
> [...] going to work on an RFC tomorrow and hopefully post it on friday on the rust-wasm repo [...]

That sounds great! As a general principle, I think we *should* have RFCs for these sorts of issues that have long-term consequences for the entire community and ecosystem.

In addition to discussing the system for specifying dependencies, maybe the RFC should also discuss about whether the versions should be semver-by-default or not?

**Comment by ashleygwilliams** [comment]
closing because stale and waiting on an rfc process.
