### ISSUE TITLE
How do I load wasm into Deno?

### ISSUE THREAD

**Issue by nabezokodaikon** [rustwasm/wasm-pack#1013]
When I started the server with the following command, an error occurred.
```
$ deno run --allow-read --allow-net https://deno.land/std@0.97.0/http/file_server.ts
```

<img width="752" alt="スクリーンショット 2021-06-07 21 16 37" src="https://user-images.githubusercontent.com/3197942/121015202-ada27a00-c7d5-11eb-9a0a-d6e8a066973b.png">

How can I load wasm?

I tried the following:
```
$ wasm-pack build --out-dir ./server/public/pkg --target web
```

**Comment by DesmondWillowbrook** [comment]
Could you please show the code which is importing the WebAssembly as well?

**Comment by nabezokodaikon** [comment]
Thank you for your reply!

Rust code
```rust
extern crate wasm_bindgen;

use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    pub fn alert(s: &str);
}

#[wasm_bindgen]
pub fn greet(name: &str) {
    #[allow(unused_unsafe)]
    unsafe {
        alert(&format!("Hello, {}!", name));
    }
}
```

Import code. (typescript)
```typescript
const js = import('../pkg/wasm_deno.js');
js.then(js => {
  js.greet('WebAssembly')
});
```

**Comment by DesmondWillowbrook** [comment]
From your first message, it looks like you're using `--target web`. Have you tried `--target deno` and following the [syntax listed in the wasm_bindgen book about deploying to Deno](https://rustwasm.github.io/wasm-bindgen/reference/deployment.html#deno)?

**Comment by nabezokodaikon** [comment]
wasm-bindgen can target deno, but wasm-pack does not have a deno target.

**Comment by nabezokodaikon** [comment]
The initial state can no longer be reproduced.
Instead, I got the following error:

<img width="1118" alt="スクリーンショット 2021-06-08 21 37 19" src="https://user-images.githubusercontent.com/3197942/121186160-c0828080-c8a1-11eb-9218-2ad78bf085e0.png">

**Comment by nabezokodaikon** [comment]
This can happen in either of the following two ways:

```typescript
//@deno-types="../pkg/wasm_deno.d.ts"
import { greet } from '../pkg/wasm_deno.js';
greet('Hello');
```

```
const wasmCode = await Deno.readFile("../pkg/wasm_deno.wasm");
const wasmModule = new WebAssembly.Module(wasmCode);
const wasmInstance = new WebAssembly.Instance(wasmModule);
const greet = wasmInstance.exports.greet as CallableFunction;
greet('Hello');
```

**Comment by nabezokodaikon** [comment]
When I ran the following command, the error changed.

```
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg --target deno
```

<img width="1358" alt="スクリーンショット 2021-06-08 22 11 05" src="https://user-images.githubusercontent.com/3197942/121190938-7a7beb80-c8a6-11eb-82d2-8466426fd51d.png">

**Comment by nabezokodaikon** [comment]
Below is the pattern I tried.

### Pattern1
```typescript
const js = import('../pkg/wasm_deno.js');
js.then(js => {
  js.greet('WebAssembly')
});
```
```bash
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg
$ deno bundle server/public/ts/greet.ts server/public/js/greet.js
```
#### Error
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/wasm". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Pattern2
```typescript
const js = import('../pkg/wasm_deno.js');
js.then(js => {
  js.greet('WebAssembly')
});
```
```bash
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg --target web
$ deno bundle server/public/ts/greet.ts server/public/js/greet.js
```
#### Error
```
Uncaught (in promise) TypeError: Cannot read property '__wbindgen_malloc' of undefined
    at Module.greet (wasm_deno.js:78)
    at greet.js:3
```

### Pattern3
```typescript
//@deno-types="../pkg/wasm_deno.d.ts"
import { greet } from '../pkg/wasm_deno.js';
greet('Hello');
```
```bash
$ cargo build --target wasm32-unknown-unknown --release
$ wasm-bindgen target/wasm32-unknown-unknown/release/wasm_deno.wasm --out-dir ./server/public/pkg --target deno
$ deno bundle server/public/ts/greet.ts server/public/js/greet.js
```
#### Error
```
Uncaught ReferenceError: Deno is not defined
    at greet.js:67
```

**Comment by nabezokodaikon** [comment]
When I changed the code to the following, the error changed.
```
import init, { greet } from '../pkg/wasm_deno.js';
async function run() {
  await init();
  greet('hello');
}

run();
```

<img width="1264" alt="スクリーンショット 2021-06-09 20 04 22" src="https://user-images.githubusercontent.com/3197942/121343670-ea00e200-c95d-11eb-9b99-ae250e965e17.png">

**Comment by nabezokodaikon** [comment]
Does typescript bundled with deno not work with browser?
I wrote the following in javascript and it worked.
```typescript
import init, { greet } from '../pkg/wasm_deno.js';
async function run() {
  await init();
  greet('hello');
}
run();
```

**Comment by nabezokodaikon** [comment]
I solved it by reading the wasm file separately using fetch.

import init, { greet } from '../pkg/wasm_deno.js';
async function run() {
  await init(await fetch('../public/pkg/wasm_deno_bg.wasm'));
  greet('hello');
}
run();

**Comment by nabezokodaikon** [comment]
I solved it by reading the wasm file separately using fetch.
```typescript
import init, { greet } from '../pkg/wasm_deno.js';
async function run() {
  await init(await fetch('../public/pkg/wasm_deno_bg.wasm'));
  greet('hello');
}
run();
```

**Comment by mindon** [comment]
my demo running with deno
https://gist.github.com/mindon/7265d3e68e7bc3c59bda97005f3316fd
