### ISSUE TITLE
Install script fails for wasm-pack 0.10.0

### ISSUE THREAD

**Issue by gkaemmer** [rustwasm/wasm-pack#1023]
## 🐛 Bug description

Hey, noticed there was a version bump earlier today. I just tried to update `wasm-pack` using the following commands and it failed: (note I normally download install scripts to disk before piping them to `sh`):

```sh
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf > /tmp/wasm-install
chmod a+x /tmp/wasm-install
/tmp/wasm-install
```

When I ran that, I got the following errors:

```
info: downloading wasm-pack
mv: rename /var/folders/3k/_5c4_thn1_v_fphcd31bcrd40000gq/T/tmp.ZHduu0yl/wasm-pack to /var/folders/3k/_5c4_thn1_v_fphcd31bcrd40000gq/T/tmp.ZHduu0yl/wasm-pack-init: No such file or directory
/tmp/wasm-install: line 72: /var/folders/3k/_5c4_thn1_v_fphcd31bcrd40000gq/T/tmp.ZHduu0yl/wasm-pack-init: No such file or directory
```

Upon further investigation, it looks like the `--strip-components 1` argument to `tar` needs to be removed on [line 64 of the install script](https://github.com/rustwasm/wasm-pack/blob/master/docs/_installer/init.sh#L64) in order for the install to succeed on my machine:

```sh
# Old:
ensure tar xf "$_file" --strip-components 1 -C "$_dir"
# New
ensure tar xf "$_file" -C "$_dir"
```

When I updated that line and re-ran the install script, it succeeded.

#### 🤔 Expected Behavior
What should have happened?

The install should have succeeded and upgraded my wasm-pack version to `0.10.0`.

#### 👟 Steps to reproduce
I _think_ you could reproduce this by just running the install script:
```
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
```

I bet the format of the .tar.gz file has changed or something causing the `--strip-components` no longer to be necessary.

#### 🌍 Your environment
I'm on an intel Mac running MacOS 10.15.6

wasm-pack version: 0.10.0
rustc version: rustc 1.40.0-nightly (its old but I doubt this matters)

**Comment by drager** [comment]
We had some issues with the tarball here: https://github.com/rustwasm/wasm-pack/releases/tag/v0.10.0 in the latest release. I have fixed them now. Could you try to reproduce it now?

**Comment by gkaemmer** [comment]
Yeah that fixed it, thanks 👍

**Comment by drager** [comment]
Thanks for verifying!
