### ISSUE TITLE
wasm-pack does not compile on Raspberry Pi 4 (ARMV7)

### ISSUE THREAD

**Issue by NeoTech** [rustwasm/wasm-pack#1036]
## 🐛 Bug description
Tried installing wasm-pack with the cargo command and got the following output.
```
   Compiling xattr v0.2.2
   Compiling terminal_size v0.1.17
   Compiling socket2 v0.4.0
error[E0658]: `match` is not allowed in a `const fn`
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/lib.rs:156:9
    |
156 | /         match address {
157 | |             SocketAddr::V4(_) => Domain::IPV4,
158 | |             SocketAddr::V6(_) => Domain::IPV6,
159 | |         }
    | |_________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/49146

error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/sys/unix.rs:680:46
    |
680 |     msg.msg_iovlen = min(bufs.len(), IovLen::MAX as usize) as IovLen;
    |                                              ^^^ associated item not found in `usize`

error[E0599]: no associated item named `MAX` found for type `usize` in the current scope
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/sys/unix.rs:740:46
    |
740 |     msg.msg_iovlen = min(bufs.len(), IovLen::MAX as usize) as IovLen;
    |                                              ^^^ associated item not found in `usize`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0599, E0658.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `socket2`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.9.1`, intermediate artifacts can be found at `/tmp/cargo-installyi599o`

Caused by:
  build failed
```

#### 🤔 Expected Behavior
wasm-pack should have built.

#### 👟 Steps to reproduce
Get a pi4, pi400 or similar, run Raspbian, install Rust from apt (1.41) and runt command for `cargo install wasm-pack`

#### 🌍 Your environment
Include the relevant details of your environment.
Architechture: ARMv7
wasm-pack version: -
rustc version: 1.41

**Comment by simlay** [comment]
>  rustc version: 1.41

That version of rust was released [more than a year ago](https://blog.rust-lang.org/2020/02/27/Rust-1.41.1.html). I'm not sure what the best way to install rust on Raspbian is but based on your error message, you need a newer version of rust that works with `const fn`.

According to [socket2's repo](https://github.com/rust-lang/socket2#minimum-supported-rust-version-msrv), you need at least rust 1.46 but you might as well just upgrade to latest stable rust (1.53 as of today) as I think you'll have other problems.
