### ISSUE TITLE
Error: Bad CPU type in executable (os error 86)

### ISSUE THREAD

**Issue by baoming158** [rustwasm/wasm-pack#1040]
## 🐛 Bug description (help)
Error: Bad CPU type in executable (os error 86)

#### 🤔 Expected Behavior
program have good running

#### 👟 Steps to reproduce
when : wasm-pack build 
Error: Bad CPU type in executable (os error 86)

#### 🌍 Your environment
wasm-pack version: wasm-pack 0.10.0
rustc version: rustc 1.49.0 (e1884a8e3 2020-12-29)

**Comment by shore-yong** [comment]
https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable ?
