### ISSUE TITLE
🐛 `cargo install wasm-pack` fails during openssl-sys build on Windows for v0.10.0+

### ISSUE THREAD

**Issue by rivy** [rustwasm/wasm-pack#1058]
## 🐛 Bug description

v0.9.1 compiles and installs correctly; all v0.10+ versions fail during the openssl-sys build...

#### 🌍 Your environment

Windows: `Microsoft Windows [Version 10.0.19042.1165]`
rustc version: `rustc 1.54.0 (a178d0322 2021-07-26)`

```shell
> rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

> cargo install wasm-pack --version 0.10.1
    Updating crates.io index
  Installing wasm-pack v0.10.1
   Compiling winapi v0.3.9
...
The following warnings were emitted during compilation:

warning: expando.c

error: failed to compile `wasm-pack v0.10.1`, intermediate artifacts can be found at `C:\Users\Roy\AppData\Local\Temp\cargo-installW072cj`

Caused by:
  failed to run custom build command for `openssl-sys v0.9.66`

Caused by:
  process didn't exit successfully: `C:\Users\Roy\AppData\Local\Temp\cargo-installW072cj\release\build\openssl-sys-3858cc32ec00fcdb\build-script-main` (exit code: 101)
...
  running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX64\\x86\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "C:\\Users\\Roy\\AppData\\Local\\Temp\\cargo-installW072cj\\release\\build\\openssl-sys-98af2d501d0cf259\\out\\openssl-build\\install\\include" "-W4" "-E" "build/expando.c"
  cargo:warning=expando.c
  exit code: 0
  cargo:rustc-cfg=osslconf="OPENSSL_NO_COMP"
  cargo:rustc-cfg=osslconf="OPENSSL_NO_ENGINE"
  cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
  cargo:rustc-cfg=osslconf="OPENSSL_NO_SEED"
  cargo:conf=OPENSSL_NO_COMP,OPENSSL_NO_ENGINE,OPENSSL_NO_SSL3_METHOD,OPENSSL_NO_SEED
  cargo:rustc-cfg=ossl101
  cargo:rustc-cfg=ossl102
  cargo:rustc-cfg=ossl102f
  cargo:rustc-cfg=ossl102h
  cargo:rustc-cfg=ossl110
  cargo:rustc-cfg=ossl110f
  cargo:rustc-cfg=ossl110g
  cargo:rustc-cfg=ossl110h
  cargo:rustc-cfg=ossl111
  cargo:rustc-cfg=ossl111b
  cargo:rustc-cfg=ossl111c
  cargo:version_number=101010cf
  cargo:version=111
  cargo:rerun-if-env-changed=I686_PC_WINDOWS_MSVC_OPENSSL_LIBS
  I686_PC_WINDOWS_MSVC_OPENSSL_LIBS unset
  cargo:rerun-if-env-changed=OPENSSL_LIBS
  OPENSSL_LIBS = libcrypto64MT:libssl64MT
  cargo:rerun-if-env-changed=I686_PC_WINDOWS_MSVC_OPENSSL_STATIC
  I686_PC_WINDOWS_MSVC_OPENSSL_STATIC unset
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  OPENSSL_STATIC unset

  --- stderr

  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.


  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.


  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.


  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.


  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.


  Microsoft (R) Program Maintenance Utility Version 14.23.28105.4
  Copyright (C) Microsoft Corporation.  All rights reserved.

  thread 'main' panicked at 'OpenSSL libdir at `C:\Users\Roy\AppData\Local\Temp\cargo-installW072cj\release\build\openssl-sys-98af2d501d0cf259\out\openssl-build\install\lib` does not contain the required files to either statically or dynamically link OpenSSL', C:\Users\Roy\.cargo\registry\src\github.com-1285ae84e5963aae\openssl-sys-0.9.66\build/main.rs:350:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
```

#### 👟 Steps to reproduce

Full compilation output attached.

[cargo install wasm-pack --version 0.10.1.txt](https://github.com/rustwasm/wasm-pack/files/7116550/cargo.install.wasm-pack.--version.0.10.1.txt)

**Comment by rivy** [comment]
Looks like a duplicate of #1026.

**Comment by drager** [comment]
I just made a branch without `openssl/vendored`. Could your try running this to try it out? `cargo install wasm-pack --git https://github.com/rustwasm/wasm-pack --branch remove-strict`

**Comment by rivy** [comment]
> I just made a branch without `openssl/vendored`. Could your try running this to try it out? `cargo install wasm-pack --git https://github.com/rustwasm/wasm-pack --branch remove-strict`

Done.

It compiles and installs.

Is there any downside to avoiding `'openssl/vendored'` (openssl inclusion/support)?

**Comment by drager** [comment]
> > I just made a branch without `openssl/vendored`. Could your try running this to try it out? `cargo install wasm-pack --git https://github.com/rustwasm/wasm-pack --branch remove-strict`
> 
> Done.
> 
> It compiles and installs.
> 
> Is there any downside to avoiding `'openssl/vendored'` (openssl inclusion/support)?

Not that I can think of, no. I'll publish a `0.10.2` based on the `remove-strict` branch.

**Comment by rivy** [comment]
I just took a quick search through the code ... I don't see any use of `openssl`. Maybe it should just be removed?

**Comment by workingjubilee** [comment]
The curl crate, and others, have an opinion on what version of OpenSSL is used. It is not unusual to see a crate specify a version for a dependency's dependency in order to issue a firmer suggestion to Cargo on how it should be resolved.

**Comment by drager** [comment]
> The curl crate, and others, have an opinion on what version of OpenSSL is used. It is not unusual to see a crate specify a version for a dependency's dependency in order to issue a firmer suggestion to Cargo on how it should be resolved.

Yes, that's the case here. Introduced here: https://github.com/rustwasm/wasm-pack/commit/7ab7a3f2cbe14fc05fcbe4f98bf497f779c39fa2#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542

**Comment by cataggar** [comment]
The `curl` crate dependency makes a dependency on `openssl`, which isn't great for ease of installation on Windows. Why not just use `reqwest` to download, which is already a dependency?

**Comment by yangdan8** [comment]
https://rustwasm.github.io/wasm-pack/installer/

**Comment by 1714080902120** [comment]
i am learning `rust + webAssembly` with tutorial: 
[Compiling from Rust to WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#wasm-pack)
And i met the same problem when i installed `wasm-pack` on windows.
Would it be more helpful to viewers to add a hint to this tutorial?

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
