### ISSUE TITLE
Extra options (--features) result in wasm-pack error.

### ISSUE THREAD

**Issue by iiSeymour** [rustwasm/wasm-pack#1059]
## 🐛 Bug description

Using `--features` as the last argument to `wasm-pack` does not get treated as an extra option that is passed to `cargo build` but an error - 

```
$ wasm-pack build --release --target web --features wasm
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    wasm-pack build --release --target <target>

For more information try --help
```

#### 🤔 Expected Behavior

The build command can pass extra options straight to cargo build even if they are not supported in wasm-pack. To use them simply add the extra arguments at the very end of your command, just as you would for cargo build. For example, to build the previous example using cargo's offline feature:

```
wasm-pack build examples/js-hello-world --mode no-install --offline
```
https://rustwasm.github.io/wasm-pack/book/commands/build.html#extra-options

#### 👟 Steps to reproduce

```
$ wasm-pack build --release --target web --features wasm
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    wasm-pack build --release --target <target>

For more information try --help
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.10.1
rustc version: 1.54.0 (a178d0322 2021-07-26)

**Comment by abalmos** [comment]
@iiSeymour try

```
$ wasm-pack build --release --target web -- --features wasm
```

Looks like the docs need a PR.
