### ISSUE TITLE
0.10.1 does not work properly inside a docker CI

### ISSUE THREAD

**Issue by b-m-f** [rustwasm/wasm-pack#1078]
## 🐛 Bug description
Building my app throws
```
Failed to compile with 1 error6:49:05 PM
#29 38.62
#29 38.62 This relative module was not found:
#29 38.62
#29 38.62 * ./crate/pkg in ./src/lib/crypto.js
```

The weird thing is that it works outside of docker.
Dockerfile in question is here: https://github.com/b-m-f/WirtBot/blob/master/Build-Automation/WirtBot/Dockerfile#L31
Problematic code: https://github.com/b-m-f/WirtBot/blob/master/Interface/src/lib/crypto.js#L3

#### 🤔 Expected Behavior
It should compile correctly and works in 0.9.1

#### 👟 Steps to reproduce
- clone https://github.com/b-m-f/WirtBot
-  remove version constraint in  Build-Automation/WirtBot/Dockerfile#L31
- make test-system in root
- it will error

#### 🌍 Your environment

wasm-pack version: 0.10.1
rustc version: 1.54.0

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
