### ISSUE TITLE
[question] How to export rust struct wihch  has const generics to js 

### ISSUE THREAD

**Issue by master-davidlee** [rustwasm/wasm-pack#1085]
Hi, I want to export a struct to js by wasm-bindgen, but the struct has const generics. 
`pub struct SipMsk<const L: usize> {
    s: [BigNum; L]
}
 `
but I get error like this "structs with #[wasm_bindgen] cannot have lifetime or type parameters currently"
How can I fix this

**Comment by mikefarmer01** [comment]
Your question is not related to wasm-pack.
You should check wasm_bindgen documentation and source.
