### ISSUE TITLE
The tagged release on GitHub does not match what's released under 0.10.1

### ISSUE THREAD

**Issue by d3lm** [rustwasm/wasm-pack#1087]
The first problem I stumbled upon is that the commit that is tagged for the latest release, which is [`bcf0741`](https://github.com/rustwasm/wasm-pack/commit/bcf0741637e610984616e0b0d50d4888b0e96e97) does not really exist in this repo. It point's to something else. However, the equivalent commit in this repo would be https://github.com/rustwasm/wasm-pack/commit/7ccacca9370c418d2108d7bf70e797908a7b6538.

If you then compare the src code of the released version then it's different from what's in master. It seems that there's somehow an older version released or something?

I ran into this issue because I am setting up wasm-pack for my M1 Mac Book Pro and there is currently no pre-built version for `wasm-opt` and just installing wasm-pack via `curl` or `cargo` does not contain the changes that are mentioned in the changelog, for example that it looks up `wasm-opt` in the `$PATH` first using `which`.  This feature has been merged before https://github.com/rustwasm/wasm-pack/commit/7ccacca9370c418d2108d7bf70e797908a7b6538 but it's not part of the released version.

Can we fix this and release a new version which contains the code from `master`?

Also, there's been a change in the CLI argument parsing I believe, because of 
- https://github.com/rustwasm/wasm-pack/blob/master/src/command/build.rs#L104-L111
- https://github.com/rustwasm/wasm-pack/blob/master/src/command/build.rs#L159-L161

And if you use the latest master, and invoke `wasm-pack` with some extra arguments **without** providing a working directory, then that will error, e.g.
```
wasm-pack build --out-dir dist --release --target web -- -Z build-std=std,panic_abort
```
This will print
```
Error: crate directory is missing a `Cargo.toml` file; is `-Z` the wrong directory?
```
It only works if you provide a `path`, so it's not correctly parsing the extra arguments if no path is specified. Or maybe I am missing something.

**Comment by drager** [comment]
@d3lm New version released: https://crates.io/crates/wasm-pack/0.10.2 https://www.npmjs.com/package/wasm-pack/v/0.10.2

Can probably close this now then?

**Comment by d3lm** [comment]
I think so yes! Tho I think the error I pointed out above is still present I guess, or at least we should mention it that when you provide extra args that a working directory is required. Or isn't that true? Maybe I was doing something wrong.

**Comment by d3lm** [comment]
Yep this is fixed 💪 Thanks!

**Comment by d3lm** [comment]
Tho, I think we should update the README, to point out that the cwd is *required* if you pass extra args. WDYT @drager?

**Comment by ArhanChaudhary** [comment]
> Tho, I think we should update the README, to point out that the cwd is _required_ if you pass extra args. WDYT @drager?

@d3lm I think this is worth documenting, as the error message looks quite cryptic if you do indeed have a Cargo.toml in your cwd. Maybe this discussion could be moved to a separate issue. Thoughts?

**Comment by d3lm** [comment]
I also agree that we should document this and that the error is quite cryptic.
