### ISSUE TITLE
Pass arguments to wasm-bindgen

### ISSUE THREAD

**Issue by akriegman** [rustwasm/wasm-pack#1092]
## 💡 Feature description
Right now wasm-pack allows passing arguments to cargo build, but doesn't do the same for wasm-bindgen. I feel like this should be a pretty important feature to have. In my case, I want to use `--weak-refs` flag with wasm-bindgen, and at the moment I see no way to use this feature while using wasm-pack.

For the syntax, we could add a flag:
```console
# Like this:
wasm-pack --wbg-arg --weak-refs --wbg-arg --reference-types
# Or this:
wasm-pack --wbg-args '--weak-refs --reference-types'
```
The only problem I see with this syntax is it's different from the syntax for passing arguments to cargo, which is done with the `--` flag. That's a bit unfortunate, but ¯\\\_(ツ)_/¯.

So, what do people think?

**Comment by serprex** [comment]
#937 adds it like any other flag, but I agree that there should be a mechanism to pass arbitrary flags to wasm-bindgen

**Comment by tennox** [comment]
+1 as I need `--omit-default-module-path`

**Comment by codeart1st** [comment]
The new `--split-linked-modules` arg is also missing.

**Comment by tjramage** [comment]
@rafaelbeckel did you manage to figure this out? I'm coming up against the same problem...

I'm not sure why this was closed, unless there is no plan to support it? It seems if use any argument that is not part of the subset supported by wasm-pack, then sadly they are ignored. I'm trying to set options via my Cargo.toml, as outlined here: https://rustwasm.github.io/docs/wasm-pack/cargo-toml-configuration.html

@drager perhaps you can reopen so this at least gets some more visibility?

**Comment by maxdeviant** [comment]
Found myself wanting this same behavior. I need to pass `--experimental-reset-state-function` to `wasm-bindgen`.
