### ISSUE TITLE
Issue installing wasm-pack on Windows 10

### ISSUE THREAD

**Issue by Squirrelcoding** [rustwasm/wasm-pack#1096]
## 🐛 Bug description
[Encountered an error](https://pastebin.com/H5tPjG4U) while trying to install rust-wasm on my machine

#### 🤔 Expected Behavior
A smooth install process without any errors
#### 👟 Steps to reproduce
Just run `cargo install wasm-pack`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: `v0.10.2`
rustc version: `v1.56.1`
gcc version: `v6.3.0`

## Culprits?
I know that this issue is tied to my environment, and I think `gcc` is the culprit here. The part where the error occurred was here according to the log:
```
  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "bzip2-1.0.8" "-D_WIN32" "-
DBZ_EXPORT" "-D_FILE_OFFSET_BITS=64" "-DBZ_NO_STDIO" "-o" "C:\\Users\\My Name\\AppData\\Local\\Temp\\cargo-installvhphOY\\release\\build\\bzip2-sys-6cdbad4f0a3b6446\\out\\lib\\bzip2-1.0.8/blocksort.o" "-c" "bzip2-1.0.8/blocksort.c" with
args "gcc.exe" did not execute successfully (status code exit code: 1).
```

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
