### ISSUE TITLE
Change in v0.10.2 that causes output directory to first be removed breaks my build

### ISSUE THREAD

**Issue by zzzachzzz** [rustwasm/wasm-pack#1099]
In reference to this change which causes the output directory to first be removed: https://github.com/rustwasm/wasm-pack/pull/986#pullrequestreview-715310944

While I understand this may be intended behavior, I thought I'd share my use case that illustrates why my build is dependent on files already residing in the output `pkg` folder, files which are tracked in git.

I have a `.gitignore` that looks like this:
```
pkg/*
!pkg/index.ts
!pkg/insight.worker.ts
!pkg/insight.d.ts
```
As you can see, I keep some essential files tracked by git in the `pkg` folder, and these modules then reference the output files generated by wasm-pack. Maybe there's a better way for me to go about this? Such as copying the files into `pkg` as part of the build process, or perhaps I should keep these files outside of the `pkg` folder, and reference the build output that goes into `pkg`.

If it is decided to keep this change, please add it to the v0.10.2 changelog.

**Comment by huntc** [comment]
We are also seeing this problem introduced with 0.10.2 and in conjunction with webpack. Webpack is watching the files in the pkg folder and seems to go into a panic, and is unable to recover until we restart its watching.

@zzzachzzz Did you manage to overcome this somehow?

**Comment by zzzachzzz** [comment]
@huntc My temporary solution is to lock wasm-pack @ 0.10.1, installing via npm

**Comment by huntc** [comment]
Fixed by my PR.
