### ISSUE TITLE
Linux arm64 is unsupported in the npm package.

### ISSUE THREAD

**Issue by nnelgxorz** [rustwasm/wasm-pack#1169]
## 🐛 Bug description
In the mono repo for [Qwik](https://github.com/BuilderIO/qwik) we provide a devcontainer for contributors. Some contributors using Apple machines have tried to use the dev container and ran into an error when trying to install wasm-pack from npm.

Further investigation revealed the error as `Error: Unsupported platform: Linux arm64`. It appears that there are binaries built for this, but the npm package has not been updated to reflect that.

#### 🤔 Expected Behavior
What should have happened?

The install should complete.

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.

Clone the Qwik repo on an Apple M1 machine and open the dev container.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version:
rustc version:

**Comment by ethanfrey** [comment]
@drager I just hit this issue trying to use a project on my Mac m1. But the fix is not in latest 0.10.3 release. Could you please make a 0.10.4 with this? (Or I can try to figure out how to build npm package locally and host somewhere)
