### ISSUE TITLE
wasm-pack test should support Microsoft Edge

### ISSUE THREAD

**Issue by abdurraheemali** [rustwasm/wasm-pack#1172]
## 💡 Feature description
It would be nice if we could do wasm-pack test --edge and test our package in Microsoft Edge.

**Comment by abdurraheemali** [comment]
You can just do --chrome and then open localhost in edge

**Comment by iMonZ** [comment]
> You can just do --chrome and then open localhost in edge

can we add --chromium instead of chrome so it's not confusing?
That would be awesome
