### ISSUE TITLE
`Error: failed to parse manifest` when using the workspace inheritance feature from Rust 1.64

### ISSUE THREAD

**Issue by printfn** [rustwasm/wasm-pack#1180]
## 🐛 Bug description
I set up the my `Cargo.toml` files to use the [workspace inheritance feature](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds) from Rust 1.64, which resulted in this error:

```
$ wasm-pack build --target no-modules --out-dir ../web/pkg
Error: failed to parse manifest: /Users/printfn/Code/fend/wasm/Cargo.toml
Caused by: invalid type: map, expected a string for key `package.description`
```

Compiling the same project with `cargo build` works fine, so this error must be specific to `wasm-pack`.

#### 🤔 Expected Behavior
I would've expected the Cargo.toml file to be parsed correctly.

#### 👟 Steps to reproduce
Workspace Cargo.toml:
```toml
[workspace]
members = ["cli", "core", "wasm"]

[workspace.package]
version = "1.1.0"
description = "Arbitrary-precision unit-aware calculator"
# ...
```

Wasm Cargo.toml:
```
[package]
name = "fend-wasm"
version.workspace = true
description.workspace = true
# ...
```

[This commit](https://github.com/printfn/fend/commit/25330f5649cb47a44b5778c75e34d6997a33bd3c) shows the diff between the `Cargo.toml` files.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.10.3
rustc version: 1.64

```
$ cargo -vV
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: aarch64-apple-darwin
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.79.1 (sys:0.4.55+curl-7.83.1 system ssl:(SecureTransport) LibreSSL/3.3.6)
os: Mac OS 12.6.0 [64-bit]
```

**Comment by Firstyear** [comment]
I can reproduce with a similar environment setup.

**Comment by martinfrances107** [comment]
I can confirm this bug 

cargo -vV

```
cargo 1.64.0 (387270bc7 2022-09-16)
release: 1.64.0
commit-hash: 387270bc7f446d17869c7f208207c73231d6a252
commit-date: 2022-09-16
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```

**Comment by martinfrances107** [comment]
The original issue identified problems with name, version, description

```
[package]
name = "fend-wasm"
version.workspace = true
description.workspace = true
``` 
I want to extent this list to  "license" and "repository"

**Comment by martinfrances107** [comment]
Sorry for the distraction my commented above need to be corrected

after reading, the doc more carfully 

 "license" and "repository" are not on the list....

https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table

authors | categories
-- | --
description | documentation
edition | exclude
homepage | include
keywords | license
license-file | publish
readme | repository
rust-version | version

**Comment by printfn** [comment]
@martinfrances107: Yes they are in the list, in the second column. 

This is the full list of attributes that can be referenced from a workspace as of Rust 1.64: `authors`, `categories`, `description`, `documentation`, `edition`, `exclude`, `homepage`, `include`, `keywords`, `license`, `license-file`, `publish`, `readme`, `repository`, `rust-version` and `version`.

Of those, only `description`, `license`, `license-file`, `repository` and `homepage` seem to result in this bug, while setting the other attributes in the workspace root works fine.
