### ISSUE TITLE
npm package regression in 0.10.3 - "You must install wasm-pack before you can run it"

### ISSUE THREAD

**Issue by dnut** [rustwasm/wasm-pack#1189]
There is a regression in 0.10.3. It's a problem in both windows in linux. This issue from 0.10.0 back: https://github.com/rustwasm/wasm-pack/issues/1038

Note at the end of that thread, there is another user experiencing the same regression:
> This problem has resurfaced in 0.10.3 but downgrading to 0.10.1 works. Windows 11 10.0.22000 Build 22000

For me it's happening in linux. WIth 0.10.1 there is no problem, but I get this error with 0.10.3:
> You must install wasm-pack before you can run it

Note: I do not have wasm-pack installed for my entire system or user account. I have wasm-pack *only* as a dependency in the current package.

**Comment by dhruvkelawala** [comment]
I am facing this too

**Comment by wontem** [comment]
have you tried to update your rust toolchain? `rustup update`?

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
