### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by f1am3d** [rustwasm/wasm-pack#1202]
## 💡 Feature description
Full Windows support.

#### 💻 Basic example
Considering significantly higher popularity of Windows OS among developers, me (and not only me) wondering why you're forcing Linux system as a must-use? 

https://survey.stackoverflow.co/2022/

Please add normal Windows support (via cargo, without need to download a separate file).
A lot of people will be grateful to you.

**Comment by drager** [comment]
wasm-pack should work on Windows.

Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
