### ISSUE TITLE
wasm-pack fails to download geckodriver

### ISSUE THREAD

**Issue by mwu-tow** [rustwasm/wasm-pack#1219]
## 🐛 Bug description
Hi, recently I observed that on our CI we have failures when using `wasm-pack` to run tests using headless `geckodriver`.

```
[INFO]: Installing wasm-bindgen...
[INFO]: Getting geckodriver...
Error: failed to download from https://github.com/mozilla/geckodriver/releases/download/0.32.1/geckodriver-0.32.1-linux64.tar.gz
Caused by: received a bad HTTP status code (404) when requesting https://github.com/mozilla/geckodriver/releases/download/0.32.1/geckodriver-0.32.1-linux64.tar.gz
```

The correct URL would be https://github.com/mozilla/geckodriver/releases/download/v0.32.1/geckodriver-v0.32.1-linux64.tar.gz, the `wasm-pack` is missing the leading `v` character.

As I looked into the code, this is caused because the latest `geckodriver` release was in fact tagged twice, once with `v0.32.1` and once with `0.32.1`. `wasm-pack` picks the latter, when only the former is correct. 
In general, I'd say `wasm-pack` should not try guessing tags/urls and just use the API to browse the assets.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: wasm-pack 0.10.3
rustc version: rustc 1.68.0-nightly (1e4f90061 2023-01-11)

**Comment by drager** [comment]
This should be fixed in new versions of wasm-pack.
