### ISSUE TITLE
wasm-pack finds wasm-opt, then looks for it in the wrong place

### ISSUE THREAD

**Issue by derekdreery** [rustwasm/wasm-pack#1276]
## 🐛 Bug description
I'm having intermittent problems running wasm-pack on my system. The key part of the logs is below

```text
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: found wasm-opt at "/usr/bin/wasm-opt"
Error: /usr/bin/bin/wasm-opt binary does not exist
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Caused by: /usr/bin/bin/wasm-opt binary does not exist
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

It seems that `wasm-pack` finds the binary, but then tries to run it at a different location.

#### 🤔 Expected Behavior
`wasm-opt` should be run correctly

#### 👟 Steps to reproduce
Difficult to reproduce because it may depend on my system. I can't share the code I'm writing but I think it's unlikely to be related to code in any case. I'm happy to provide any information that would be useful.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.11.0
rustc version: rustc 1.71.0-nightly (d0f204e4d 2023-04-16)

**Comment by stephanemagnenat** [comment]
I am having the same problem, on Ubuntu 20.04.6 LTS with rustc 1.69.0 (84c898d65 2023-04-16).

**Comment by stephanemagnenat** [comment]
For me, uninstalling the `binaryen` package solved the issue because `wasm-pack` then used a downloaded version of `wasm-opt`.
