### ISSUE TITLE
Can't download  wasm-opt nor use the system-wide installed version

### ISSUE THREAD

**Issue by lvella** [rustwasm/wasm-pack#1280]
## 🐛 Bug description
I am new to trying to build rust to wasm, and was following [wgpu tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/). When it came to building with wasm-pack (i.e. run `wasm-pack build`), it stops with the following error:
```
Error: failed to download from https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Caused by: failed to download from https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-linux.tar.gz
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

I don't know why the download failed, because the URL worked just fine in the browser or via wget.

Then I figured out I could install binaryen via `sudo apt install binaryen` on Ubuntu. That I tried, but when I ran `wasm-pack build` again, I got this different error:
```
[INFO]: found wasm-opt at "/usr/bin/wasm-opt"
Error: /usr/bin/bin/wasm-opt binary does not exist
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Caused by: /usr/bin/bin/wasm-opt binary does not exist
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

I.e. it seems to have found the Ubuntu's wasm-opt, but did not assemble the path properly when executing (inserted an extra `/bin`.

To work around the issue, I have taken up the suggestion in the error and set:
```
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

#### 🤔 Expected Behavior
I expected binaryen to be correctly downloaded if could not be found on the system, and if found, that it could be properly used.

#### 👟 Steps to reproduce
Just follow the [wgpu tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/) on a Ubuntu 22.04.2 machine, and install wasm-pack with `cargo install wasm-pack`.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: v0.11.0 (as reported by `cargo install wasm-pack`)
rustc version: 1.65.0

**Comment by lvella** [comment]
It seems this is a partial duplicate of #1263.

**Comment by nekopsykose** [comment]
this is fixed in 0.11.1

**Comment by puxiao** [comment]
> this is fixed in 0.11.1

Are you sure fixed it? Why do I still have this problem in 0.12.1?

**Comment by JamesTheAwesomeDude** [comment]
I'm experiencing this issue with wasm-pack 0.12.1.

Should I open a new issue?

```
C:\…>wasm-pack build --verbose --target web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
       Fresh unicode-ident v1.0.12
       Fresh once_cell v1.19.0
       Fresh bumpalo v3.15.4
       Fresh log v0.4.21
       Fresh cfg-if v1.0.0
       Fresh proc-macro2 v1.0.79
       Fresh quote v1.0.35
       Fresh wasm-bindgen-shared v0.2.92
       Fresh syn v2.0.58
       Fresh wasm-bindgen-backend v0.2.92
       Fresh wasm-bindgen-macro-support v0.2.92
       Fresh wasm-bindgen-macro v0.2.92
       Fresh wasm-bindgen v0.2.92
       Fresh test009 v0.1.0 (C:\…)
    Finished release [optimized] target(s) in 0.03s
Error: failed to download from https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-windows.tar.gz
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Caused by: failed to download from https://github.com/WebAssembly/binaryen/releases/download/version_111/binaryen-version_111-x86_64-windows.tar.gz
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

**Comment by inanna-malick** [comment]
I'm also experiencing this issue in 12.1

**Comment by drager** [comment]
Still an issue in 0.13.0? If so, please open a new issue.
