### ISSUE TITLE
Error message in init.sh due to using == instead of = in an `if`

### ISSUE THREAD

**Issue by chrisdsloan** [rustwasm/wasm-pack#1283]
## 🐛 Bug description
Running the install (init.sh), it printed an error message ("sh: 139: [: x86_64: unexpected operator").  The error message is caused because `==` is used instead of `=` in the `if` on line 139 of init.sh.

#### 🤔 Expected Behavior
No error message from the if comparison.

#### 👟 Steps to reproduce

```
$ curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
sh: 139: [: x86_64: unexpected operator
info: downloading wasm-pack
info: successfully installed wasm-pack to `/home/cds/.cargo/bin/wasm-pack`
```

Here's my fix:
```
diff --git a/docs/_installer/init.sh b/docs/_installer/init.sh
index 91ec0af..6fb08c0 100644
--- a/docs/_installer/init.sh
+++ b/docs/_installer/init.sh
@@ -136,7 +136,7 @@ get_architecture() {
     esac
 
     # See https://github.com/rustwasm/wasm-pack/pull/1088
-    if [ "$_cputype" == "aarch64" ] && [ "$_ostype" == "apple-darwin" ]; then
+    if [ "$_cputype" = "aarch64" ] && [ "$_ostype" = "apple-darwin" ]; then
         _cputype="x86_64"
     fi
 
```

#### 🌍 Your environment
I'm running on Pop!_OS 20.04 LTS on an x86 laptop.  The bash version is "5.0.17(1)-release".

wasm-pack version: wasm-pack 0.11.0.  The error is present in master (48177dc0d) as well.
rustc version: rustc 1.68.1 (8460ca823 2023-03-20)

**Comment by seanbright** [comment]
Since `init.sh` uses bashisms, the installation instructions should instead be updated to pipe the script to `bash` instead of `sh`, e.g.:

    $ curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | bash

Alternatively `init.sh` could be made compatible with POSIX `sh` and the installation instructions could remain as is.

**Comment by chrisdsloan** [comment]
The existing version has "#!/bin/bash" but the double equals is the only bashism I saw, so I agree that switching the instructions to use bash in the pipe will work fine, but moving the shebang to /bin/sh and fixing the double equals seems like the best way to maintain maximum portability, I'd think.

**Comment by seanbright** [comment]
`local` is not POSIX.
