### ISSUE TITLE
Error while installing wasm-pack on Linux

### ISSUE THREAD

**Issue by vivekpal1** [rustwasm/wasm-pack#1286]
## Description
I followed the bash command
```bash
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
```

Got this message unable to copy executable to `/usr/bin/wasm-pack`
```bash
failed to copy executable to `/usr/bin/wasm-pack`
Caused by: failed to copy executable to `/usr/bin/wasm-pack`
Caused by: Permission denied (os error 13)
```

#### Worked by adding sudo
```bash
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sudo sh
```

#### 🌍 Your environment
Include the relevant details of your environment.
rustup version: 1.26.0
rustc version: 1.69.0
system: Arch Linux, kernel 6.3.1-arch2-1

**Comment by drager** [comment]
This is OS dependent, depends on permissions and locations and works fine on some distros. I think we can close this... You can also install `wasm-pack` directly via cargo `cargo install wasm-pack`
