### ISSUE TITLE
Can't run unit and iteg tests separately

### ISSUE THREAD

**Issue by stan-irl** [rustwasm/wasm-pack#1289]
## 🐛 Bug description
- It's common to want to run unit and integ tests separately because integ tests are slower and can be prone to failure
- `cargo test` currently supports this as documented here: https://github.com/rust-lang/cargo/issues/10491#issuecomment-1074078912
  - unit: `cargo test --lib --bins`
  - integ: `cargo test --test "*"`
- When i pass these flags to wasm-pack test I get a panic in wasm-bidgen-test
  - unit: `wasm-pack test -- --lib --bins` throws `panicked at 'flag --lib not supported'`
  - integ:  `wasm-pack test -- --test *` throws `panicked at 'flag --test not supported'`

I thought this was in issue in wasm-bindgen but they sent me over here: https://github.com/rustwasm/wasm-bindgen/issues/3432

Specifically they pointed out this code: https://github.com/rustwasm/wasm-pack/blob/081861b10e2e81a230701510172f80aaa4f92e3d/src/test/mod.rs

#### 🤔 Expected Behavior
`wasm-pack test -- --lib --bins` does not panic

#### 👟 Steps to reproduce
1. Create a new project and install wasm-pack
2. run `wasm-pack test -- --lib --bins`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.10.3
rustc version: 1.69.0

**Comment by ExpHP** [comment]
I'm not observing a panic in 0.11.1, is this fixed?

**Comment by stan-irl** [comment]
yeah youre right! thanks :)
