### ISSUE TITLE
unexpected argument `--version`  found

### ISSUE THREAD

**Issue by chenrui333** [rustwasm/wasm-pack#1301]
## 🐛 Bug description

While trying to [upgrade wasm-pack to 1.2.0](https://github.com/Homebrew/homebrew-core/pull/134029), we found that the `--version` regression test failed

```
$ /opt/homebrew/Cellar/wasm-pack/0.12.0/bin/wasm-pack --version
error: unexpected argument '--version' found

  tip: a similar argument exists: '--verbose'

Usage: wasm-pack <--verbose...|--quiet|--log-level <LOG_LEVEL>> <COMMAND>

For more information, try '--help'.
```

#### 🤔 Expected Behavior

The version check should pass

#### 👟 Steps to reproduce

just a cargo install build and run the `--version` check against the built binary

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version:
rustc version: `rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)`

**Comment by chenrui333** [comment]
This is the `--help`

```
$ /opt/homebrew/Cellar/wasm-pack/0.12.0/bin/wasm-pack --help
📦 ✨  pack and publish your wasm!

Usage: wasm-pack [OPTIONS] <COMMAND>

Commands:
  build    🏗️  build your npm package!
  pack     🍱  create a tar of your npm package but don't publish!
  new      🐑 create a new project with a template
  publish  🎆  pack up your npm package and publish!
  login    👤  Add an npm registry user account! (aliases: adduser, add-user)
  test     👩‍🔬  test your wasm!
  help     Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...             Log verbosity is based off the number of v used
  -q, --quiet                  No output printed to stdout
      --log-level <LOG_LEVEL>  The maximum level of messages that should be logged by wasm-pack. [possible values: info, warn, error] [default: info]
  -h, --help                   Print help
```

**Comment by ThatOneBro** [comment]
Just noticed this too

**Comment by lynn** [comment]
+1, I was using `wasm-pack --version` in a build script to check the right version of wasm-pack is installed.

```
$ wasm-pack --version    # before
wasm-pack 0.11.0
$ wasm-pack --version    # after installing 0.12
error: unexpected argument '--version' found

  tip: a similar argument exists: '--verbose'
...
```

**Comment by billti** [comment]
Yeah, not to pile on but this broke our CI over the weekend too (below). Currently we run `https://rustwasm.github.io/wasm-pack/installer/init.sh` to install, which maybe isn't a good practice. Is there a way this script can pin to a version?

<img width="782" alt="image" src="https://github.com/rustwasm/wasm-pack/assets/993909/f0265b40-a2ce-424e-a5c2-e2d2c4e6bff1">
