### ISSUE TITLE
Cannot build project following tutorial

### ISSUE THREAD

**Issue by vodkaslime** [rustwasm/wasm-pack#1345]
## 🐛 Bug description
After following the tutorial, I got the project `wasm-game-of-life`. Then when doing `wasm-pack build`, the build runs like:

```
wasm-pack build
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling proc-macro2 v1.0.69
   Compiling unicode-ident v1.0.12
   Compiling wasm-bindgen-shared v0.2.88
   Compiling bumpalo v3.14.0
   Compiling log v0.4.20
   Compiling once_cell v1.18.0
   Compiling wasm-bindgen v0.2.88
   Compiling cfg-if v1.0.0
   Compiling quote v1.0.33
   Compiling syn v2.0.39
   Compiling wasm-bindgen-backend v0.2.88
   Compiling wasm-bindgen-macro-support v0.2.88
   Compiling wasm-bindgen-macro v0.2.88
   Compiling console_error_panic_hook v0.1.7
   Compiling wasm-game-of-life v0.1.0 (/home/jiachen/workspace/rust/wasm-game-of-life)
warning: function `set_panic_hook` is never used
 --> src/utils.rs:1:8
  |
1 | pub fn set_panic_hook() {
  |        ^^^^^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: `wasm-game-of-life` (lib) generated 1 warning
    Finished release [optimized] target(s) in 5.93s
```
Got stuck there without showing `[INFO]: ⬇️  Installing wasm-bindgen...` and followings.

And the `pkg` package has only
```
ls
wasm_game_of_life_bg.js    wasm_game_of_life_bg.wasm.d.ts  wasm_game_of_life.js
wasm_game_of_life_bg.wasm  wasm_game_of_life.d.ts
```

#### 🤔 Expected Behavior
The build should succeed with package.json and other files.

#### 👟 Steps to reproduce
Just following the tutorial https://rustwasm.github.io/docs/book/game-of-life/hello-world.html and then run command `wasm-pack build`

#### 🌍 Your environment
Include the relevant details of your environment.
Os: fedora
wasm-pack version: 0.12.1
rustc version: 1.73.0 (cc66ad468 2023-10-03)

**Comment by vodkaslime** [comment]
Somehow done, maybe network issues

**Comment by toymil** [comment]
I am experiencing this exact problem reliably in every build...

Changing network environment or setting `http(s)_proxy` envvar does not help, so I can't say it's network issue.

**Comment by toymil** [comment]
I left it to run overnight, it finished and now all following builds don't get stuck anymore 🤔

Seems like there is some time consuming (but no cpu usage) tasks needs to be done on the first run.

**Comment by toymil** [comment]
Did some digging in the source code, seems like it's trying to download a pre-built `wasm-opt`, and got stuck due to network issue.

**Comment by toymil** [comment]
If you install the following tools outside of wasm-pack, it won't try to download on its own and get stuck:
- `wasm-bindgen-cli`, `wasm-opt`, `cargo-generate` (e.g., install from cargo)
- `chromium-driver` (install from system package manager)
