### ISSUE TITLE
wasm build failed because of rimage

### ISSUE THREAD

**Issue by pzhasaki** [rustwasm/wasm-pack#1352]
#### 🌍 Your environment
my Cargo.toml config：
`
[package]
name = "imagekit"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
clap = { version = "4.4", features = ["derive"] }
rimage = { version = "0.9", features = ["webp", "avif"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
strip = true 
lto = true
`
and i do orders：
`
CC=emcc wasm-pack build --target web
`
build failed beacause package "rimage"

## 🐛 Bug description
<img width="2060" alt="image" src="https://github.com/rustwasm/wasm-pack/assets/78007999/8abfe8c4-6561-4959-854e-8d2797063285">

**Comment by MiniOcean404** [comment]
May I ask how you solved it?
