### ISSUE TITLE
`wasm-pack` doesn't default-export the init function in .d.ts file

### ISSUE THREAD

**Issue by JohnScience** [rustwasm/wasm-pack#1357]
## 🐛 Bug description

I'm trying to use a Rust library in a Vite + React + TypeScript project. However, I can't use my library because it requires the `init()` function. For a `greet`, example, here are the contents of my `lib-name.d.ts`:

```
/* tslint:disable */
/* eslint-disable */
/**
* @param {string} name
*/
export function greet(name: string): void;
```

Since the `init` function, isn't default-exported, I can't properly import it in my TypeScript code.

#### 🤔 Expected Behavior
What should have happened?

The `init()` function should be default exported like this:

```
export default function (): Promise</*Exports?*/>;

export function greet(s: string): void;
```

So that such code

```ts
import init, { greet } from '../lib-name/pkg/lib-name';

// ...
init().then((/*_exports*/) => {
    greet("Hello");
});
```

can be used without tweaking the `.d.ts` file.

#### 👟 Steps to reproduce

Create TS project and try to use the type definitions there.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.12.1
rustc version: 1.73.0

**Comment by JohnScience** [comment]
It fixed itself. Weird.

**Comment by xrl** [comment]
I am experiencing this bug as well, I generate my WASM from a build.rs script like this:

```
    let build_opts = BuildOptions {
        path: Some(lc3b_path.clone()),
        out_dir: out_dir.join("pkg").display().to_string(),
        disable_dts: true,
        target: Target::Web,
        ..Default::default()
    };
    let mut build = Build::try_from_opts(build_opts).unwrap();
    build.run().expect("wasm-pack build");
```
