### ISSUE TITLE
`wasm32-unknown-unknown` target not found

### ISSUE THREAD

**Issue by grilledwindow** [rustwasm/wasm-pack#1364]
## 🐛 Bug description
I've been building a wasm project using wasm-pack for a few weeks now. All of a sudden I'm hit with this error:

```
Caused by: wasm32-unknown-unknown target not found in sysroot: "/usr"

Used rustc from the following path: "/bin/rustc"
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.
```

I don't understand the error as I am using Rustup, running `rustup target list` also shows that the target is installed. I'm only creating this issue as I couldn't find any useful info on this error. I've already tried reinstalling Rust but the error still persists. 

#### 🤔 Expected Behavior
Project should build normally.

#### 👟 Steps to reproduce
The only command I used was `wasm-pack build`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: `0.12.1`
rustc version: `1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1)`

**Comment by TheCuddleDoodle** [comment]
Removing the snap version for rust-up and re-installing it through apt, fixed the issue on my Ubuntu 22.04.3.
