### ISSUE TITLE
can't install v0.13 

### ISSUE THREAD

**Issue by ulvido** [rustwasm/wasm-pack#1405]
## 🐛 Bug description
Describe your issue in detail.
cant install v0.13

#### 🤔 Expected Behavior
What should have happened?
should install.

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.
```bash
cargo install wasm-pack
```
![image](https://github.com/rustwasm/wasm-pack/assets/27722274/770f354f-b0a8-42a5-80b4-cad64629ef9f)
![image](https://github.com/rustwasm/wasm-pack/assets/27722274/1f999f24-4da6-4fdb-9bf5-91c05fc9c2c0)

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.12.1
rustc version: 1.79.0
![image](https://github.com/rustwasm/wasm-pack/assets/27722274/6846750e-3ec3-4ffc-8be0-7763fcb33c82)

**Comment by nulltrope** [comment]
having the same issue here, pinning to an older version in the meantime.

**Comment by byteszard** [comment]
I have the same problem in MacOS.

**Comment by drager** [comment]
Hmm, I successfully installed `v.0.13.0` after the release on PopOS. Investigation from the ones having problems would be much appreciated. I will also try to break the install on my system.

**Comment by ReneCode** [comment]
on my MacOS

         curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

and
        wasm-pack build
works fine

**Comment by nulltrope** [comment]
> Hmm, I successfully installed `v.0.13.0` after the release on PopOS. Investigation from the ones having problems would be much appreciated. I will also try to break the install on my system.

@drager The root of the issue seems to be that we now require `cmake` be installed on the host system, whereas previous versions did not require this. Simple remove cmake or spin up a new VM/container without cmake and try installing v0.13.0 to repro.

I analyzed dependency changes and it appears that v0.13.0 of this crate updated to a new version of `binary-install` (v0.4.0) which in turn introduced a change here https://github.com/rustwasm/binary-install/pull/29 to depend on a new crate `zip_next`, which uses a newer version of the crate `flate2`.

Here's some cargo tree commands run from the latest version of wasm-pack repo (v0.13.0):
```
# cargo tree -i flate2
flate2 v1.0.30
└── zip v1.1.4
    └── zip_next v1.1.1
        └── binary-install v0.4.0 (*)
```
which in turn depends on cmake as a build dep:
```
# cargo tree -p flate2
flate2 v1.0.30
├── libz-ng-sys v1.1.15
│   └── libc v0.2.155
│   [build-dependencies]
│   └── cmake v0.1.50
│       └── cc v1.0.104
│           ├── jobserver v0.1.31
│           │   └── libc v0.2.155
│           ├── libc v0.2.155
│           └── once_cell v1.19.0
└── miniz_oxide v0.7.4
    └── adler v1.0.2
```

This is compared to the last version of the `wasm-pack` crate v0.12.1:
```
# cargo tree -i flate2
flate2 v1.0.26
└── zip v0.6.6
    └── binary-install v0.2.0 (*)
```
which does not depend on cmake:
```
# cargo tree -p flake2
flate2 v1.0.26
├── crc32fast v1.3.2
│   └── cfg-if v1.0.0
└── miniz_oxide v0.7.1
    └── adler v1.0.2
```

I'm also not sure `zip_next` is the crate you want to be using, given it's archived/deprecated in favor of the regular `zip`: https://crates.io/crates/zip_next.

**Comment by drager** [comment]
> > Hmm, I successfully installed `v.0.13.0` after the release on PopOS. Investigation from the ones having problems would be much appreciated. I will also try to break the install on my system.
> 
> @drager The root of the issue seems to be that we now require `cmake` be installed on the host system, whereas previous versions did not require this. Simple remove cmake or spin up a new VM/container without cmake and try installing v0.13.0 to repro.
> 
> I analyzed dependency changes and it appears that v0.13.0 of this crate updated to a new version of `binary-install` (v0.4.0) which in turn introduced a change here [rustwasm/binary-install#29](https://github.com/rustwasm/binary-install/pull/29) to depend on a new crate `zip_next`, which uses a newer version of the crate `flate2`.
> 
> Here's some cargo tree commands run from the latest version of wasm-pack repo (v0.13.0):
> 
> ```
> # cargo tree -i flate2
> flate2 v1.0.30
> └── zip v1.1.4
>     └── zip_next v1.1.1
>         └── binary-install v0.4.0 (*)
> ```
> 
> which in turn depends on cmake as a build dep:
> 
> ```
> # cargo tree -p flate2
> flate2 v1.0.30
> ├── libz-ng-sys v1.1.15
> │   └── libc v0.2.155
> │   [build-dependencies]
> │   └── cmake v0.1.50
> │       └── cc v1.0.104
> │           ├── jobserver v0.1.31
> │           │   └── libc v0.2.155
> │           ├── libc v0.2.155
> │           └── once_cell v1.19.0
> └── miniz_oxide v0.7.4
>     └── adler v1.0.2
> ```
> 
> This is compared to the last version of the `wasm-pack` crate v0.12.1:
> 
> ```
> # cargo tree -i flate2
> flate2 v1.0.26
> └── zip v0.6.6
>     └── binary-install v0.2.0 (*)
> ```
> 
> which does not depend on cmake:
> 
> ```
> # cargo tree -p flake2
> flate2 v1.0.26
> ├── crc32fast v1.3.2
> │   └── cfg-if v1.0.0
> └── miniz_oxide v0.7.1
>     └── adler v1.0.2
> ```
> 
> I'm also not sure `zip_next` is the crate you want to be using, given it's archived/deprecated in favor of the regular `zip`: https://crates.io/crates/zip_next.

Ah, thank you a lot for the research. I will revert that PR and update zip to the latest version instead. Thanks!

**Comment by drager** [comment]
Got a PR that uses `binary-install` `v0.4.1` instead, which removes `zip-next` and uses latest `zip` instead. Now `cmake` etc is gone: https://github.com/rustwasm/wasm-pack/pull/1407/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eL368-L376

**Comment by zmb3** [comment]
I can confirm this no longer occurs as of 0.13.1.
