### ISSUE TITLE
Release v0.13.1 with `cmake` fix

### ISSUE THREAD

**Issue by ivan770** [rustwasm/wasm-pack#1426]
Hi.

I'd like to request a new wasm-pack release that includes the commit 62ab39cf82ec4d358c1f08f348cd0dc44768f412. Currently, some package repositories (e.g. nixpkgs) still use 0.12.0 specifically due to the build failure fixed in that commit.

**Comment by zmb3** [comment]
Hey @drager are there any updates on this? Would love to see your fix make its way into a release.

**Comment by drager** [comment]
> Hey @drager are there any updates on this? Would love to see your fix make its way into a release.

Yes, I will try to cut a new release today.

**Comment by drager** [comment]
Released in [v0.13.1](https://github.com/rustwasm/wasm-pack/releases/tag/v0.13.1)

**Comment by zmb3** [comment]
Thanks for the quick response!
