### ISSUE TITLE
debug build windows appveyor releases

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#147]
we currently make release binaries for linux and mac using travis. we should also do this for windows with appveyor!

**Comment by huangjj27** [comment]
I have the experience of [setting up AppVeyor for libui-rs](https://github.com/LeoTindall/libui-rs/pull/18) and I'm glad to do the job at this weekend, if you're ok.

**Comment by mgattozzi** [comment]
That would be super super helpful! :D If you want to take a crack at that please do :)

**Comment by ashleygwilliams** [comment]
thanks so much for volunteering @huangjj27 !

**Comment by huangjj27** [comment]
Before I start the job, I want to make it clear which channel and target should I test, Could you give me some advice?

**Comment by ashleygwilliams** [comment]
@huangjj27 at the very least, i would like to have parity with wasm-bindgen, which does this https://github.com/rustwasm/wasm-bindgen/blob/master/.appveyor.yml#L7, targeting `x86_64-pc-windows-msvc` on `nightly`. (your intuitions were totally correct!)

that being said- if there are other targets you think we should use appveyor for as well, we're very open to hearing more! feel free to broaden the horizon if you wish to, just be sure to explain your rationale here at some point :)

thanks again for taking this on!

**Comment by huangjj27** [comment]
I found that you already have a [`.appveyor.yml`](https://github.com/ashleygwilliams/wasm-pack/blob/master/.appveyor.yml) file, Can't that  be used for build? If it can, what I need to do is just to rename it to `appveyor.yml`

**Comment by ashleygwilliams** [comment]
hi @huangjj27 i'm not sure we need to rename it in order for it to build releases for us... it works fine in `wasm-bindgen` as `.appveyor.yml`. is there a reason you think it needs to be renamed?

**Comment by huangjj27** [comment]
Hi, @ashleygwilliams, I'm sorry I'm confused. It seems that [the original yml works fine for wasm-pack](https://ci.appveyor.com/project/ashleygwilliams/wasm-pack/build/1.0.363), and according to [AppVeyor's doc](https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming), renaming the config file make no difference, which I thought it have to be without the prefix-dot.

**Comment by sendilkumarn** [comment]
@ashleygwilliams Don't we already have the windows build? Do you mean something else here.

**Comment by ashleygwilliams** [comment]
@huangjj27 @sendilkumarn the purpose of this issue is to instruct our current appveyor CI to publish the builds it makes as releases to our releases page here on github (https://github.com/ashleygwilliams/wasm-pack/releases). you can see on this page that we are building OSX and linux. i'd like to get the windows one going as well, as we also support windows. 

this is a help document on how to do it! https://www.appveyor.com/docs/deployment/github/ - i'll need to get it set up with a key but i thought someone might be interested in making the PR that adds everything but the key! here is an example on the `wasm-bindgen repo`: https://github.com/rustwasm/wasm-bindgen/blob/master/.appveyor.yml#L39

 let me know if there are any other questions :)

**Comment by ashleygwilliams** [comment]
ugh wait. i'm the worst.. it is building releases... or it is supposed to be building releases. seems like this is not a feature request but a bugfix! sorry ya'll.
