### ISSUE TITLE
consider checking + warning for Cargo.toml elements 

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#152]
the rustwasm template has several useful elements that we might warn folks on if they are missing as a way to teach them to use them: https://github.com/rustwasm/rust_wasm_template/blob/master/Cargo.toml

thoughts?

**Comment by mgattozzi** [comment]
LTO makes sesnse, but maybe with wasm people want to optimize for speed rather than size. I think this kind of plays into how we want to configure wasm-pack, because I know certain lints will want to be turned on or off by people, but this is a good idea.

**Comment by Pauan** [comment]
@mgattozzi Doesn't LTO *also* improve speed as well? Since it allows for cross-compilation optimizations.

As far as I know, the only downside to LTO is increased compile times.

**Comment by mgattozzi** [comment]
Yes it does! What wasn't clear in my wording is that you can tell how you want the compiler to optimize with the [opt-level](https://github.com/rustwasm/rust_wasm_template/blob/master/Cargo.toml#L46) flag!

**Comment by ashleygwilliams** [comment]
closing as we already do this! please file again if you think the current set up doesn't fully address this issue!
