### ISSUE TITLE
Move Travis to use the Checks API

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/wasm-pack#169]
We'll need to upgrade the build at some point to do this. This one is probably something you'll need to do @ashleygwilliams

**Comment by ashleygwilliams** [comment]
indeed. do we know how urgent this is? i've been waiting for an announcement from travis but haven't seen anything (though i may have missed it because of travel)

**Comment by mgattozzi** [comment]
I mean it looks like they said 2 weeks but here we are 🤷‍♂️ . It was not very clear. Don't think it needs to be done today, but maybe by like the release after this one?
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by ashleygwilliams** [comment]
i believe this has been done.
