### ISSUE TITLE
test using assert_cli

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#18]
https://github.com/killercup/assert_cli

**Comment by yoshuawuyts** [comment]
I was thinking [dir-diff](https://github.com/steveklabnik/dir-diff) might be a good one too for the output. E.g. https://github.com/ashleygwilliams/wasm-pack/pull/32 doesn't have any tests, but using dirdiff, it should be quite convenient to test the output.

**Comment by ashleygwilliams** [comment]
@yoshuawuyts yeah! i am speaking to some of the CLI-WG team on gitter and they suggested that as well. are you interested in tackling any of this testing? i could do it on my own but since you've taken some interest, i'm super down to let you take a crack at it if you'd like!

**Comment by yoshuawuyts** [comment]
@ashleygwilliams done!

**Comment by ashleygwilliams** [comment]
this has some issue with windows compat!

**Comment by ashleygwilliams** [comment]
after a regression in 0.3.0 this is top priority now

**Comment by ashleygwilliams** [comment]
@fitzgen handled this with #522 closing
