### ISSUE TITLE
Remove outdated quicli comments from `init.rs`

### ISSUE THREAD

**Issue by data-pup** [rustwasm/wasm-pack#191]
Now that `quicli` is not in the dependencies, the comments above `init::create_pkg_dir` are outdated. Further, I believe the full paths to `result::Result` are no longer needed in the various function/method definitions, since that conflict is no longer caused by `quicli::prelude`.

Assuming I'm right about all of that, I was thinking this could be a pretty straightforward thing to fix, and a good task for someone new to OSS contribution. I can take care of this tomorrow if that sounds good to you, I'll was planning to use it as a pairing exercise with someone :smile:

**Comment by ashleygwilliams** [comment]
go for it @data-pup - i saw them but just had etoomany things on the brain- this would be greatly appreciated and i love that you'll use it as a pairing sesh!
