### ISSUE TITLE
should wasm-pack clean up after itself? and if so, how?

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#203]
sometimes wasm-pack fails. currently it just leaves everything as is- should it remove files it created if the whole process fails? i find myself rm -rf the pkg directory if that happens to run it again, but in general i'm not sure if that's a workflow for me as a lib author and not something an end user would be interested in. thoughts?

**Comment by fitzgen** [comment]
My 2 cents:

Not worth the code complexity and potential for mistakes if/when there are bugs in this code (eg rm the wrong dir!).

Being able to manually `rm pkg/` is fine IMO.

**Comment by ashleygwilliams** [comment]
cool @fitzgen - i think i mostly agree. gonna leave this open for the week on the offchance we get other replies. i'll close on Friday.

**Comment by mgattozzi** [comment]
It's been over a week so I'm going to close. If people have issues with this we can reopen the thread later :D
