### ISSUE TITLE
use std::path::Path[Buf] and join for paths

### ISSUE THREAD

**Issue by Mackiovello** [rustwasm/wasm-pack#213]
```
$ cargo run -- init myproject/
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/wasm-pack init myproject/`

  [1/8] Checking crate configuration...
  [2/8] Adding WASM target...
  [3/8] Compiling to WASM...
  [4/8] Creating a pkg directory...
  [5/8] Writing a package.json...
  :-) [WARN]: Field description is missing from Cargo.toml. It is not necessary, but recommended
  :-) [WARN]: Field repository is missing from Cargo.toml. It is not necessary, but recommended
  :-) [WARN]: Field license is missing from Cargo.toml. It is not necessary, but recommended
  [6/8] Copying over your README...
  :-) [WARN]: origin crate has no README
  [7/8] Installing WASM-bindgen...
  [8/8] Running WASM-bindgen...
  :-) Done in 2 minutes
| :-) Your WASM pkg is ready to publish at myproject//pkg.
```

In the last line it says "Your WASM pkg is ready to publish at myproject//pkg.". It should probably just be "myproject/pkg".

This is on Linux.

**Comment by Mackiovello** [comment]
The issue is only when the path has a trailing forward slash. Would it make sense to trim this in [`set_crate_path`](https://github.com/rustwasm/wasm-pack/blob/master/src/command/utils.rs#L5-L12)?

Since we probably have this issue in a number of places where we do `{}/pkg`, I think that's the way to deal with it.

**Comment by fitzgen** [comment]
Long term, I think a lot of places should start using `std::path::Path[Buf]` in `wasm-pack`, and then we could use the `join` method instead of `{}/pkg`.

**Comment by ashleygwilliams** [comment]
strong agree with @fitzgen. have renamed this issue to that plan. PRs welcome!

**Comment by Mackiovello** [comment]
> PRs welcome!

I'd love to take this one! It seems to be on my level.
