### ISSUE TITLE
Add build subcommand? 

### ISSUE THREAD

**Issue by xtuc** [rustwasm/wasm-pack#234]
Hi :wave: 

It seems that the only way to build the crate is to run `wasm-pack init`, but it also initialize the project. 

Webpack plugin/loader would enable watching the code and rebuilding it if needed (probably incrementally?) in development. That's why I would suggest adding such a command.

An alternative would be to wrap `wasm-pack` in another project, consuming the API to expose the features I need (I just need to learn Rust first). What do you think?

EDIT:
How cool would it be to write the loader/plugin using `wasm-bindgen`?

**Comment by ashleygwilliams** [comment]
hey @xtuc - we actually have a PR open for exactly this ;) #216  let me know if that doesn't work for you-
