### ISSUE TITLE
--out flag that allows configuration of `./pkg` dir

### ISSUE THREAD

**Issue by xtuc** [rustwasm/wasm-pack#235]
This is a feature request; I would like to configure the output directory (currently hardcoded to `./pkg`).

When Webpack invokes `wasm-pack` in the root of the project it will create the `./pkg` directory. Unlike the normal `wasm-pack`'s use case we won't publish it and don't `.gitignore` it.

I would like to avoid generating the intermediate files in the user's repository but rather in a temporary fs, where Webpack will be able to bundle it anyway.

**Comment by data-pup** [comment]
I wouldn't mind taking this one! I'll start looking into it, and will follow up if I have any other questions :)

**Comment by ashleygwilliams** [comment]
go for it @data-pup that'd be awesome!

**Comment by xmclark** [comment]
In #263, I'm pretty close to a complete solution. What should be printed here? I could imagine writing the absolute path, or trying to use a nicer looking relative path. 

![image](https://user-images.githubusercontent.com/1364747/44619307-0d078900-a839-11e8-851c-fbb8b5f7a218.png)

**Comment by fitzgen** [comment]
> I could imagine writing the absolute path, or trying to use a nicer looking relative path.

Either one sounds good to me.

**Comment by fitzgen** [comment]
Fixed in #263
