### ISSUE TITLE
Support targeting Node

### ISSUE THREAD

**Issue by nikgraf** [rustwasm/wasm-pack#266]
## 💡 Feature description

I was trying @xtuc's [wasm-node-loader](https://github.com/wasm-tool/node-loader), but noticed the output of wasm-pack is not compatible to Node 10.

Three things I noticed:

- the file ending of the generated JS file is `.js`, but node will require a `.mjs` ending.
- import of the wasm file not ending with `.wasm`.  e.g. `import * as wasm from './app_bg';
`. With the node loader it should be `import * as wasm from './app_bg.wasm`.
- after I changed them manually node was still complaining it can't fine `"./app.js"`, but not sure where this was coming from.

I'm not sure what's the best way forward. wasm-pack could support a commnand line flag for `wasm-pack build` to target node. On the other hand maybe it needs a different node loader.

**Comment by mgattozzi** [comment]
Hey @nikgraf so this is doable. However, the major blocker is `wasm-bindgen` until that gets support for Node modules we won't be able to move this forward, because otherwise we'd be parsing JS files to do the transform rather than wasm-bindgen spitting them out automatically as `.mjs` files with the correct `import` statements.

**Comment by nikgraf** [comment]
Thanks for the clarification 👍

**Comment by ashleygwilliams** [comment]
hey @nikgraf - so wasm-pack can support node by exporting CommonJS. would this work for you? we aren't currently of the impression that es6 modules on node are stable enough to support. you would need nodejs with a flag, which also still has bugs and edgecases, and we don't have a way to give reliable commonjs fallback either, which is frustrating.

let me know if the CommonJS use case works for you! you can use it by running `wasm-pack init --target nodejs`

**Comment by xtuc** [comment]
This isn't blocking to me.

The issue is that the current ESM implementation in bundler and the future one in Nodejs, will have some differences, `.mjs` is an example.

I wouldn't work on making ESM for bundler also compatible for Nodejs.

**Comment by nikgraf** [comment]
@ashleygwilliams just tried it and works like a charm. I thought loading WASM won't work with CommonJS, but I does just fine. Thanks!

**Comment by ashleygwilliams** [comment]
Great to hear! Glad it worked for you :)
