### ISSUE TITLE
Handle versions of wasm-bindgen in lockfiles

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/wasm-pack#270]
## 💡 Feature description
We have a basic implementation of keeping up to date with wasm-bindgen. Ideally though with the local install we'd tie the version to whatever is in the lock file to avoid issues with things like `Cargo.toml` using `wasm-bindgen = 0.2` as what version of `wasm-bindgen-cli` does this mean? Having a lock file look up would solve this issue.

**Comment by fitzgen** [comment]
Finding the lock file can be interesting if the crate is in a workspace. We can leverage https://crates.io/crates/cargo_metadata to help.

**Comment by data-pup** [comment]
Digging into this now :smile_cat: 

https://github.com/oli-obk/cargo_metadata/blob/master/src/lib.rs#L156

It does look like the `Cargo.toml` dependency is what is given, rather than the lockfile. This crate should still be useful for finding the lock file though :)

**Comment by data-pup** [comment]
Sounds good to me :o) I'll follow up if I have other questions!

**Comment by data-pup** [comment]
I think I have a lot of the work on this done :smile_cat: I should be able to open a PR shortly.

As an aside, is there anywhere where the fields in `Cargo.lock` are officially specified? The closest I could find was [this](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html), in the Cargo book.

**Comment by fitzgen** [comment]
I think @ashleygwilliams or @alexcrichton would know the answer to that question.

**Comment by alexcrichton** [comment]
Ah they're not necessarily officially specified but when using TOML+Serde you can deserialize into a structure like:

```rust
#[derive(Deserialize)]
struct Lockfile {
    packages: Vec<Package>,
}

#[derive(Deserialize)]
struct Package {
    name: String,
    version: String,
    source: Option<String>,
}
```

and that should be enough to match on `wasm-bindgen`!

**Comment by data-pup** [comment]
Yay! Thanks for the help @alexcrichton, that lines up with what I had done so far. My struct looked like this:

```rust
#[derive(Deserialize)]
struct Package {
    name: String,
    version: String,
    source: Option<String>,
    dependencies: Option<Vec<String>>
}
```

Should I keep the `dependencies` field out of this, following your example?

**Comment by ashleygwilliams** [comment]
closed by the last release.
