### ISSUE TITLE
wasm-pack build subcommand not available

### ISSUE THREAD

**Issue by grisli** [rustwasm/wasm-pack#274]
## 🐛 Bug description
After installation of wasm-pack the build subcommand isn't available as expected. When i run wasm-pack in console i get following output:

`wasm-pack 0.4.2
Ashley Williams <ashley666ashley@gmail.com>
📦 ✨  pack and publish your wasm!

USAGE:
    wasm-pack [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v, --verbose    Log verbosity is based off the number of v used

SUBCOMMANDS:
    help       Prints this message or the help of the given subcommand(s)
    init       🐣  initialize a package.json based on your compiled wasm!
    login      👤  Add a registry user account! (aliases: adduser, add-user)
    pack       🍱  create a tar of your npm package but don't publish!
    publish    🎆  pack up your npm package and publish!
`

"wasm-pack init" works perfectly fine and i can get the rust-webpack-template up and running.  

#### 🤔 Expected Behavior
build subcommand is available

#### 👟 Steps to reproduce
-

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.4.2
wasm-bindgen version: 0.2.19
rustc version: rustc 1.30.0-nightly (f7202e40f 2018-08-27)

**Comment by fitzgen** [comment]
Thanks for filing an issue. The `build` subcommand is only in `master` right now, there hasn't been a release with the `build` subcommand yet, but once there is it will be available.
