### ISSUE TITLE
Error constructor methods should return `Self` instead of `Result<(), Self>`

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#279]
There are places where we want to return an error in a method that returns `Result<Something, Error>` and are forced to do nasty things like `Error::crate_config("...").map(|_| unreachable!())` to make it type check. At this point, it would be easier to just do `Err(Error::crate_config(".."))` everywhere after changing the `Error` constructors to return `Self`.

**Comment by data-pup** [comment]
I'd love to help out with this one! I remember doing this for #244, and pulling it out so the PR would be a little cleaner. I don't think it would be hard to do again :smile_cat:

**Comment by fitzgen** [comment]
Great! ^_^

**Comment by ashleygwilliams** [comment]
@fitzgen now that we've shifted to using failure nearly entirely- is this out of date?

**Comment by fitzgen** [comment]
Yeah, I think this can be closed now!
