### ISSUE TITLE
Most fallible methods should return `Result<T, failure::Error>` instead of `Result<T, wasm_pack::error::Error>`

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#280]
A `wasm_pack::error::Error` will `Into` a `failure::Error` so existing `?` locations shouldn't need any changes.

Basically, only "leaf" errors should be `wasm_pack::error::Error` and everything else should be `failure::Error`.

Then we should put `.context("..")` (or `.with_context(|e| ...)`) onto all non-leaf `?` sites, providing better error messages and cause-and-effect chains.

**Comment by stuarth** [comment]
I'd be happy to take this one!

**Comment by stuarth** [comment]
@fitzgen wanted to check my understanding on this. The idea is I'll convert a fn like

[`step_check_crate_config`](https://github.com/rustwasm/wasm-pack/blob/2ef929dc91b7e713cd4602ba69fba9fb6d4db4d0/src/command/build.rs#L161) to `Result<(), failure::Error>` and add a `context` / `with_context` to its call to `check_crate_config`

What I'm not seeing -- and apologies if I'm overlooking something obvious -- is the best way to convert that `failure:Error` to a `wasm_pack::error::Error` in a fn like [`run`](https://github.com/rustwasm/wasm-pack/blob/2ef929dc91b7e713cd4602ba69fba9fb6d4db4d0/src/command/build.rs#L107)

Thanks!

**Comment by fitzgen** [comment]
> [`step_check_crate_config`](https://github.com/rustwasm/wasm-pack/blob/2ef929dc91b7e713cd4602ba69fba9fb6d4db4d0/src/command/build.rs#L161) to `Result<(), failure::Error>` and add a `context` / `with_context` to its call to `check_crate_config`

Correct.

> What I'm not seeing -- and apologies if I'm overlooking something obvious -- is the best way to convert that `failure:Error` to a `wasm_pack::error::Error` in a fn like [`run`](https://github.com/rustwasm/wasm-pack/blob/2ef929dc91b7e713cd4602ba69fba9fb6d4db4d0/src/command/build.rs#L107)

All those should become `failure::Error`s too, so no need to convert to `wasm_pack::error::Error` ;)

> Thanks!

Thank *you!*

**Comment by stuarth** [comment]
Ah, gotcha. I think I'd misread your intent with leaf / non-leaf. 

Am I right in thinking that when you say "leaf" you mean something like a function that reads a config from disk? And a non-leaf fn is one that builds on top of it, e.g. initiating a build that depends on that config?

**Comment by stuarth** [comment]
Sorry about the inactivity -- life has crept up in a major way and I haven't had a chance to get to this yet. If anyone wants to take a stab at it, please do!

**Comment by drager** [comment]
I would like to give this a shot. I will try to start working on this soon and create a PR when I have. In the meantime if someone else would like to grab this, please do and let me know if that's the case. :)

**Comment by drager** [comment]
@fitzgen: Thank you for the information, I will branch out from your PR.
