### ISSUE TITLE
Show the output of Cargo's build

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#287]
## 💡 Feature description

Compiling a crate can often take quite a long time and it's nice to know about the progress within the build when checking up on it. Would it be possible to avoid suppressing the output of `cargo build` and have it stream to the console?

**Comment by ashleygwilliams** [comment]
i have also wanted this! i think it's possible, and i'd want it to be default, *i think*, though i do think we might want to give a flag option to turn it off. any one else have thoughts?

**Comment by fitzgen** [comment]
Personally, I'd prefer always displaying all output by default, but having a `-q` flag to `wasm-pack` which makes it not display subprocess's outputs.

It would be neat if we prefixed the output with the command that was run, eg:

```text
cargo build (stderr): a warning message or something...
cargo build (stderr): some more warnings or whatever...
cargo build (stdout): something from stdout
[4/8] Compiling to wasm...
```
