### ISSUE TITLE
Colors in rustc's error mesages are lost

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#288]
## 🐛 Bug description

When compiling code with `wasm-pack build` the compiler's error messages are not printed with colors.

#### 🤔 Expected Behavior

The compiler's colors come through!

#### 👟 Steps to reproduce

If you create a blank `src/lib.rs` with only one token in it, `x` (invalid rust code), then `wasm-pack build` will show the compiler's error but without colors

**Comment by ashleygwilliams** [comment]
this was solved by the PR that moved us toward our new output strategy :) closing.
