### ISSUE TITLE
Published documentation is from the future

### ISSUE THREAD

**Issue by srounce** [rustwasm/wasm-pack#294]
## 🐛 Bug description
The currently published crate (at time of writing) is 2 months old. Anyone installing via `cargo install wasm-pack` may be confused as to why the advice featured in the documentation isn't applicable to the version they have installed.

#### 🤔 Expected Behavior
Version of latest published `wasm-pack` crate is relevant to the published documentation.

#### 👟 Steps to reproduce
`cargo install wasm-pack`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: N/A
rustc version: N/A

**Comment by ashleygwilliams** [comment]
this will be solved by the new release- thank u for filing. despite not responding i saw this issue and have been using your clever description of this bug to refer to it. we intend to release early next monday and this should be settled. sorry for the pain, and thank u for filing

**Comment by ashleygwilliams** [comment]
this should be fixed by the new release, closing. if it is not, please comment with more details and i will reopen :) thanks again for filing.
