### ISSUE TITLE
Ensure that running `wasm-pack build` in two crates in the same workspace works

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#305]
Follow up to https://github.com/rustwasm/wasm-pack/issues/252

We want test coverage that ensure that if we have

```
workspace/
  |- crate_a/
  `- crate_b/
```

running `wasm-pack build` in `crate_a` works, and running `wasm-pack build` in `crate_b` right afterwards also works.

**Comment by alexcrichton** [comment]
I believe this was added in https://github.com/rustwasm/wasm-pack/pull/430!
