### ISSUE TITLE
wasm-pack does not find installed wasm-bindgen

### ISSUE THREAD

**Issue by pcstl** [rustwasm/wasm-pack#308]
## 🐛 Bug description
On MacOS, `wasm-pack` will always take 4 to 5 minutes to run, stopping at the "[7/8] Installing wasm-bindgen..." stage.

#### 🤔 Expected Behavior
`wasm-pack` should use an existing `wasm-bindgen` install instead of redownloading every time.

#### 👟 Steps to reproduce
On a Mac, install `wasm-pack`, NPM, the wasm `rustc` backend, and `cargo-generate`.
Run the following commands:

    cargo generate --git https://github.com/rustwasm/wasm-pack-template

In the generated project, run: 

    wasm-pack init
    rm -rf pkg
    wasm-pack init

Both runs of `wasm-pack` will take the same time.

#### 🌍 Your environment
Late 2015 MacBook Pro
MacOS High Sierra v10.13.6
wasm-pack version: 0.4.2
rustc version: 1.30.0-nightly

**Comment by pcstl** [comment]
@xmclark 

```
[dependencies]
wasm-bindgen = "0.2"
```

**Comment by xmclark** [comment]
I had the exact same issue before. The easiest way to fix is setting the patch version. e.g. `wasm-bindgen = "0.2.19"`

The wasm-bindgen version has to match the one you have installed exactly. You have a wasm-bindgen v 0.2.19 or something installed, and it is matching on 0.2, so it always fails the check.

There is a little blurb with more explanation on the issue:
https://github.com/rustwasm/wasm-pack/issues/272

**Comment by ashleygwilliams** [comment]
ideally, when https://github.com/rustwasm/wasm-pack/issues/270 is fixed (there is an open PR right now for it) this will also be fixed. our next release is blocked until that PR lands- but hopefully we should be able to get it done this week. sorry you ran into this @pcstl and thanks @xmclark for helping respond! super appreciate you both 🤗

**Comment by ashleygwilliams** [comment]
@pcstl wasm-pack will do a full install everytime to ensure that the correct version exists. if you are sure you have the correct version you can run the command with `--no-installs` and avoid the installation steps. verison 0.5.0 will mitigate all of this, hopefully we can release it this week.

**Comment by fitzgen** [comment]
@pcstl it's `-m no-install`, not `--no-install` (when in doubt, run `--help` for a full listing of flags)

**Comment by ashleygwilliams** [comment]
this should be solved by the latest 0.5.0 release, closing. if it is not fixed please comment with more details and i will reopen!
