### ISSUE TITLE
Error when running wasm-pack init with the actix as a dependency

### ISSUE THREAD

**Issue by Nfinger** [rustwasm/wasm-pack#315]
## 🐛 Bug description
Describe your issue in detail.
When I run wasm-pack init with the dependencies listed below I get an error in socket2

#### 🤔 Expected Behavior
What should have happened?
The code should build in to /pkg

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.
`[dependencies]
reql = "0.0.22"
slog = "2.0"
slog-term = "2.4.0"
tokio-core = "0.1.17"
serde = "1.0"
serde_json = "1.0"
ql2 = "1.1"
derive-error = "0.0.4"
lazy_static = "1.0"
serde_derive = "1.0"
r2d2 = "0.8"
byteorder = "1.0"
bufstream = "0.1"
futures = "0.1"
reql-macros = "0.0.18"
parking_lot = "0.5"
indexmap = "1.0"
reql-types = "0.0.3"
uuid = { version = "0.6", features = ["v4", "serde"] }
native-tls = { version = "0.1", optional = true }
actix-web = "0.7.8"
actix = "0.7"
juniper = "0.10"
env_logger = "0.5"
cfg-if = "0.1.2"
wasm-bindgen = "0.2"`

![image](https://user-images.githubusercontent.com/17767789/45771431-17882900-bc13-11e8-944c-a9774cae020d.png)

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: v0.4.2
rustc version: 1.30.0-nightly (551244f05 2018-09-10)

**Comment by fitzgen** [comment]
I'm assuming that `socket2` is some kind of wrapper around OS networking capabilities? wasm doesn't have access to those things, so it isn't going to work.

Either way, this isn't a wasm-pack bug -- if you think that actix should support targetting wasm, then bringing an issue up on their tracker to discuss the prospect is probably the best way forward (and we are happy to be looped into the discussion about how to get that working!)
