### ISSUE TITLE
`--no-modules` for wasm-pack

### ISSUE THREAD

**Issue by catsigma** [rustwasm/wasm-pack#317]
## 💡 Feature description
`--no-modules` comes with `wasm-bindgen-cli` and it's needed for some bundlers.

**Comment by ashleygwilliams** [comment]
i agree that wasm-pack should support all the options that wasm-bindgen has! i am curious which bundlers need to use `--no-modules` (just for my own edification!). thanks for filing this :)

**Comment by catsigma** [comment]
The default wasm loader of Parcel doesn’t support an export object. So I need to replace the wash loader with the no ES module js file generated by wasmbindgen.




Friday, September 21, 2018, 00:45 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by ashleygwilliams** [comment]
oh! interesting. we've been working with the Parcel team, and i am aware that the current way they handle wasm is slightly different from the webpack use case. thanks for the information. 

tagging in @jamiebuilds - is supporting for an export object in the wasm loader on the roadmap? would like to hear your general thoughts on this (and anyone else on the team that might be working on this!) thanks :D

**Comment by ashleygwilliams** [comment]
@catsigma i'm gonna work on getting this in for 0.5.0 case (regardless of how the follow up with the Parcel folks shakes out) thanks again so much for the info! it's very helpful :)

**Comment by catsigma** [comment]
Thanks so much. 👍




Friday, September 21, 2018, 23:03 +0800 from notifications@github.com  <notifications@github.com>:

**Comment by ashleygwilliams** [comment]
oh! as a followup- @catsigma what `package.json` keys would you want? any? perhaps `browser`?

**Comment by jamiebuilds** [comment]
Hey @catsigma, could you share what you're doing in https://github.com/catsigma/parcel-plugin-wasmbindgen ? Just trying to figure out what Parcel is missing

**Comment by catsigma** [comment]
@jamiebuilds What I've done is pretty simple.

1. Hook my custom `.rs` asset in Parcel.
2. Compile the imported `.rs` file in `.js` file by using `wasm-pack` or `cargo & wasm-bindgen-cli`.
3. Get the generated `no-modules` JS adaptor and modify it to be a Parcel wasm loader.
4. Hook the modified wasm loader.
5. Disguise the `.rs` file as a `.js` file coding with importing the wasm file and exporting exports functions of it.
5. Parcel does the bundle job.

The problem in Parcel is that the default wasm loader doesn't contain an `__exports` argument. 
So we can only use these `i32 i64 f32 f64` types.

**Comment by catsigma** [comment]
@ashleygwilliams sorry, but I don't know what is the key in `package.json` for?

**Comment by catsigma** [comment]
@ashleygwilliams @jamiebuilds 
I've figured out a way to overcome this issue by modifying es-modules version to no-modules version.

github: https://github.com/catsigma/parcel-plugin-wasm.rs
npm: https://www.npmjs.com/package/parcel-plugin-wasm.rs

And it supports both `wasm-pack` and `wasm-bindgen-cli` now.

Thank you both.
