### ISSUE TITLE
homepage: a lot of internal links are broken

### ISSUE THREAD

**Issue by matthiaskrgr** [rustwasm/wasm-pack#325]
I landed on https://github.com/rustwasm/wasm-pack, clicked on the link in the repo description which is
https://rustwasm.github.io/wasm-pack/

Inside this website, it looks like most of the links to other parts of the website throw `404`.
For example if I click `rust` of previously linked page, the url points to
"https://rustwasm.github.io/prerequisites/rust.html" which 404s, but the side-bar has the correct url which is
"https://rustwasm.github.io/wasm-pack/prerequisites/rust.html".

Looks like the internal links are missing `wasm-pack/` after `https://rustwasm.github.io/` ?

**Comment by ashleygwilliams** [comment]
yes! thanks for reporting. would happily take a PR for this :)

**Comment by mstallmo** [comment]
I'm currently working on a quick PR to fix this up right now but I'm new markdown books, is there anyway I can make a build of this locally to see and test my changes?

**Comment by ashleygwilliams** [comment]
yup! if you `cargo install mdbook` you can run `mdbook serve` in the `/docs` directory :) there's more info here as well: https://github.com/rust-lang-nursery/mdBook

**Comment by mstallmo** [comment]
Awesome, thanks!
