### ISSUE TITLE
what should we canonically link to as documentation for this crate?

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#358]
we have rustdoc and the book. this is really not a library that folks would use api docs for. should we make the canonical doc link (on cratesio) to the homepage?

**Comment by csmoe** [comment]
I prefer to just "forget" the api docs on homepage, if it's really needed, how about add it into the contributing docs as `[dev docs](https://docs.rs/...)`

**Comment by ashleygwilliams** [comment]
solved by the latest release
