### ISSUE TITLE
Document `wasm-pack test` subcommand

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#368]
(Does not need to block the 0.5.0 release IMO)

I can write up some quick docs for `wasm-pack test` and also link to the more in-depth `wasm-bindgen-test` documentation.

**Comment by ashleygwilliams** [comment]
@fitzgen do you think you'd be able to get this in today? it'd be nice to have for 0.7.0 if at all possible! if not let me know!

**Comment by fitzgen** [comment]
I think @chinedufn kindly fixed this in b72051d385fe178cbb95865942bc42b983665a63 !
