### ISSUE TITLE
Bundle `cargo generate` temporarily for ease of installation

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#373]
## 💡 Feature description

One of the [first steps](https://rustwasm.github.io/wasm-pack/book/project-setup/using-a-template.html) in the getting started guide is to `cargo install cargo-generate`, but this can take quite some time and also be difficult to execute in all circumstances (OpenSSL issues, libgit2 issues, etc). 

It'd be awesome if instead `wasm-pack` bundled the code for `cargo-generate` by default (by using a dependeny on the actual `cargo-generate`). That way we could have something like `wasm-pack generate` which is immediately available after downloading wasm-pack. Eventually this wouldn't be necessary if `cargo generate` becomes more first class, but we could have a note saying that it's just a temporary measure for now!

**Comment by ashleygwilliams** [comment]
i'd like to tackle this for 0.6.0 - this is blocked by getting `libgit2` out of cargo generate and just requiring git as a prerequ (this ends up removing a lot of the grossness of installing cargo-generate)

**Comment by alexcrichton** [comment]
@ashleygwilliams oh wouldn't bundling this in precompiled binaries fix those issues? Using `libgit2` is a big benefit for Windows users who don't always have `git.exe` installed in PATH

**Comment by ashleygwilliams** [comment]
oh. hrm. i think you're right. sorry. commented to early. i can have a PR for this today.

**Comment by drager** [comment]
I should be able to start working on this as soon as possible. Or are you tackling this @ashleygwilliams?

**Comment by ashleygwilliams** [comment]
@drager - i was hoping i could tackle this one? would that be ok?

**Comment by drager** [comment]
@ashleygwilliams: Yes of course!
