### ISSUE TITLE
error loading libLLVM using wasm-pack test

### ISSUE THREAD

**Issue by yoshuawuyts** [rustwasm/wasm-pack#379]
## 🐛 Bug description
I tried running `wasm-pack test` on a project, and was met with a `rust-lld` error complaining about `libLLVM7.so` not existing.

#### 🤔 Expected Behavior
I was hoping to try `wasm-pack test` without any problems.

#### 👟 Steps to reproduce
It appears to be something specific to my machine, and not necessarily the project I was working on. The minimum repro I could make was an empty `lib.rs` file, and the following `Cargo.toml`:

```toml
[package]
name = "my_project"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.23"

[dev-dependencies]
wasm-bindgen-test = "0.2.23"
```

Then run `wasm-pack test`, and the following message occurred:

<details>
<summary><b>Error log</b></summary>
 <pre>
Running wasm tests failed. stderr:

   Compiling document-ready v0.1.0 (file:///home/anon/Code/chooxide/document-ready)
error: linking with `rust-lld` failed: exit code: 127
  |
  = note: "rust-lld" "-flavor" "wasm" "-L" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.3egi8p4uiuo41swt.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.3o1pi51u34qubb7s.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.48xp5o7cy4owjz32.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.o859lkertxv1n13.rcgu.o" "-o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.wasm" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/test-c2b5623034254b9d.cw2dwg1bxzc2iln.rcgu.o" "--gc-sections" "-O0" "-L" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps" "-L" "/home/anon/Code/chooxide/document-ready/target/debug/deps" "-L" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libtest-6f140dcd9f91eba1.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libterm-1a011394a6f61d7c.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libgetopts-7ef91016f4284dab.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-b0efc82f64d03095.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libpanic_unwind-d4854a808e0cd616.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libunwind-c43a3d8cf78f9d5a.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liblibc-68373f2b6bc18151.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liballoc_system-40a64b71ec5a8f18.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-f6caffaf44cc60a0.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liballoc-863f2b2485046aef.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcore-21433d3b7663b55b.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-bf63ca2c3bc4de53.rlib" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--export-table"
  = note: rust-lld: error while loading shared libraries: libLLVM-7.so: cannot open shared object file: No such file or directory
          

error: aborting due to previous error

error: Could not compile `document-ready`.
warning: build failed, waiting for other jobs to finish...
error: linking with `rust-lld` failed: exit code: 127
  |
  = note: "rust-lld" "-flavor" "wasm" "-L" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.11oexul5yl6uyg9y.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.48xp5o7cy4owjz32.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.muh5e3xtrts3ch2.rcgu.o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.o859lkertxv1n13.rcgu.o" "-o" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.wasm" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/document_ready-fa715299e9102dc7.5cjpnf705ba90raf.rcgu.o" "--gc-sections" "-O0" "-L" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps" "-L" "/home/anon/Code/chooxide/document-ready/target/debug/deps" "-L" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libtest-6f140dcd9f91eba1.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libterm-1a011394a6f61d7c.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libgetopts-7ef91016f4284dab.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libweb_sys-5a67f0b4ef8824a4.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libjs_sys-3c6d47cd0592b3b4.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libwasm_bindgen-d8ccfac63b73a8c4.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libfailure-16f5f63d0d3a1662.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libbacktrace-d1104368a70b7180.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/librustc_demangle-ca40a27f1ca3397b.rlib" "/home/anon/Code/chooxide/document-ready/target/wasm32-unknown-unknown/debug/deps/libcfg_if-16b0a663f87a2d67.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libstd-b0efc82f64d03095.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libpanic_unwind-d4854a808e0cd616.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libunwind-c43a3d8cf78f9d5a.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liblibc-68373f2b6bc18151.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liballoc_system-40a64b71ec5a8f18.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-f6caffaf44cc60a0.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/liballoc-863f2b2485046aef.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcore-21433d3b7663b55b.rlib" "/home/anon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-bf63ca2c3bc4de53.rlib" "--no-threads" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-entry" "--export-table"
  = note: rust-lld: error while loading shared libraries: libLLVM-7.so: cannot open shared object file: No such file or directory
          

error: aborting due to previous error

error: Could not compile `document-ready`.

To learn more, run the command again with --verbose.

</pre>
</details>

I tried re-running the command with `--verbose` appended, but that was strictly less helpful than the first message, haha.
<details>
<summary><b>(Unhelpful) verbose log</b></summary>
<pre>
error: Found argument '--verbose' which wasn't expected, or isn't valid in this context
	Did you mean [32m--[0m[32mversion[0m?

USAGE:
    wasm-pack test --firefox --version

For more information try --help
</pre></details>

#### 🌍 Your environment
- wasm-pack version: 0.5.0
- rustc version: rustc 1.30.0-beta.7 (0ebb25088 2018-09-22)
- operating system: Linux 4.18.9-arch1-1-ARCH x86_64 GNU/Linux

**Comment by GabrielMajeri** [comment]
Hold one a moment, LLD believes the path to your sysroot is `nightly-x86_64-unknown-linux-gnu`, but your `rustc --version` is 1.30.0-_beta_?

**Comment by yoshuawuyts** [comment]
@GabrielMajeri oh interesting! -- I used `cargo override beta` to set the local path to beta (default is nightly). Perhaps that has something to do with it?

Going to try setting beta as default, and report back.

**Comment by yoshuawuyts** [comment]
Okay, tried a few things but none of them worked:
- set the default toolchain to `beta`
- re-installed `wasm-pack` on `beta` (`cargo install --force wasm-pack`)
- uninstalled nightly toolchain
  - this shows that wasm-pack is still looking for the nightly toolchain, but can't find it anymore. It seems it's still trying to look for nightly.
- uninstalled `wasm-pack` and manually reinstalled, all on beta (with no nightly toolchain on my machine)

But I ended up fixing it by running everything on `nightly`! It seems that running `wasm-pack test `on beta simply doesn't work? Perhaps something has been hard coded?

**Comment by alexcrichton** [comment]
@yoshuawuyts do you perhaps have an entry in `PATH` pointing to the nightly folder with `rust-lld`? Also, to confirm, you've install Rust through `rustup`?

**Comment by yoshuawuyts** [comment]
> do you perhaps have an entry in PATH pointing to the nightly folder with rust-lld? 

I do not. Just searched through my dotfiles to double check, [and came up empty](https://github.com/yoshuawuyts/dotfiles/search?q=lld&unscoped_q=lld).

> Also, to confirm, you've install Rust through rustup?

Yes, I have. Currently at version 1.13.0

**Comment by alexcrichton** [comment]
@yoshuawuyts can you confirm by using `which rust-lld` and `echo $PATH` to make sure nothing looks suspicious?

Another [stray `+nightly`](https://github.com/rustwasm/wasm-pack/blob/8e6cc1fc21b8285b81ff25765cd960dd9a0cd01e/src/test/mod.rs#L33) may be causing issues, but that in theory shouldn't cause problems here in that each rustup invocation is self-contained (although this still means that `wasm-pack test` isn't using beta like intended)

**Comment by yoshuawuyts** [comment]
@alexcrichton `cargo 1.31.0-nightly (de314a8b2 2018-09-21)`

**Comment by yoshuawuyts** [comment]
@alexcrichton `rustc 1.30.0-nightly (ae7fe84e8 2018-09-26)`

**Comment by alexcrichton** [comment]
@yoshuawuyts hm are you *extra sure* that you don't think any PATH hackery and/or other installations are sitting around?

There's a few things that look suspicious here:

* In the OP you mention you're using beta, but the error message indicates that LLD is getting executed from the nightly toolchain.
* The error message indicates that `libLLVM-7.so` is missing, but when I download your toolchain and your beta toolchain both LLDs link to `libLLVM-8svn.so`. 
* The error message indicates a version of LLVM that doesn't have "svn" in the name, which is suspicious in that I think almost all builds from rust-lang/rust have "svn" in the name.

I'm sort of baffled trying to reconstruct what I think is your world in my head to figure out what's going wrong, and subsequently I can't figure out how to reproduce :(

**Comment by yoshuawuyts** [comment]
> I'm sort of baffled trying to reconstruct what I think is your world in my head to figure out what's going wrong, and subsequently I can't figure out how to reproduce :(

Yeah, I agree this sounds like it's something that's just wrong on my machine. I did have to configure quite a bit in the past to get Rust working, and I probably messed something up.

Thanks for your time; I'll dig deeper into my configs to try to root out what's going wrong on my machine!
