### ISSUE TITLE
Support asynchronous compilation of WebAssembly modules

### ISSUE THREAD

**Issue by Nyrox** [rustwasm/wasm-pack#382]
Pulling the newest versions of wasm-pack and the hello world wasm project and trying to include the generated module in an electron project fails with the following error:

`WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.`

caused by this segment generated by the wasm-pack loader. Specifically the *_bg.js responsible for actually loading the *_bg.wasm module.

```
const path = require('path').join(__dirname, 'module_bg.wasm');
const bytes = require('fs').readFileSync(path);
let imports = {};
imports['./module'] = require('./module');

const wasmModule = new WebAssembly.Module(bytes)
```

If a workaround exists for this I'd be happy to hear it, but as the error itself suggests the proper solution to this is to use the asynchronous WebAssembly factory methods and return a promise, which should be relatively straight forward to implement.

I'd like to know if interest in an option to generate asynchronous loaders exists, potentially as an option to "wasm-pack build" and if there is plans to support this.

**Comment by Nyrox** [comment]
Closed, because this seems to be an issue in wasm-bindgen not wasm-pack.

**Comment by roccomuso** [comment]
how did you solve it?

**Comment by sunjay** [comment]
@roccomuso see: https://github.com/rustwasm/wasm-bindgen/issues/905
