### ISSUE TITLE
generated wasm has "duplicate function names"?

### ISSUE THREAD

**Issue by kazcw** [rustwasm/wasm-pack#391]
## 🐛 Bug description
I'm using wasm-pack to build a fairly big wasm project (generated .wasm is over 800KB) and I'd like to try to smallen it with binaryen's wasm-opt, but all of binaryen's tools reject my .wasm with an error like: `[parse exception: duplicate function name: core::ptr::drop_in_place::h658d70c8d1119250]Fatal: error in parsing input`. Using wasm-nm, I can see a lot of symbols seem duplicated 5 or more times, especially basic libstd functions. The wasm file is working correctly in the browser though.

#### 🤔 Expected Behavior
I'd expect binaryen to be able to parse wasm-pack's wasm output

#### 👟 Steps to reproduce
Here's a minimal project based on the wasm-pack-template where `wasm-pack build` produces a `.wasm` in `pkg/` that binaryen doesn't like: https://github.com/kazcw/dup-ex

It just includes `syn` as a dependency and has a function that does something with `syn` so everything doesn't optimize away.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.0
rustc version: rustc 1.30.0-nightly (ae7fe84e8 2018-09-26)

**Comment by fitzgen** [comment]
How old is your `wasm-opt` install? I remember hitting something similar that got fixed in `wasm-opt` a couple months ago or so.

FWIW, duplicate functions are not good to have, but are not technically incorrect per-spec.

**Comment by alexcrichton** [comment]
Thanks for the report! I think I recall seeing these errors a long time ago with wabt/binaryen, but I think that it's a bug in those tools which has sine been fixed? Do you know what version of `wasm-opt` you're using?

**Comment by kazcw** [comment]
Oh, I was using binaryen-42. It looks like it's working with binaryen-45!
