### ISSUE TITLE
`wasm-pack test` doesn't add $MY_CRATE/.cargo/config automatly

### ISSUE THREAD

**Issue by huangjj27** [rustwasm/wasm-pack#395]
## 🐛 Bug description
When I follow [this guide](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#configure-cargoconfig-to-use-the-test-runner), it tells me to skip that step while `wasm-pack test` will do this for me, but when I run `cargo test --target=wasm32-unknown-unknown`, it gives me this error
```
error: could not execute process `C:\Users\34937\Desktop\learning-rust\wasm-pack-learn\target\wasm32-unknown-unknown\debug\deps\wasm_pack_learn-439f502539aed329.wasm` (never executed)

Caused by:
  %1 不是有效的 Win32 应用程序。 (os error 193)  # %1 is not a valid win32 program.   (os error 193)
```
after I manually added $MY_CRATE/.cargo/config, it compiles the test and work fine

#### 🤔 Expected Behavior
The `wasm-pack test` should add the `.cargo/config` file as  [the guide](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#configure-cargoconfig-to-use-the-test-runner) is said

#### 👟 Steps to reproduce
1. run `cargo generate --git https://github.com/rustwasm/wasm-pack-template`, and imput a name( In my case is "wasm-pack-learn"
2. add a sample test in  $MY_CRATE/tests:
```
// test_answer.rs
use wasm_bindgen_test::*;
// use wasm_pack_learn;

#[wasm_bindgen_test]
fn it_answers() {
    assert_eq!(42, 42);
}
```
3. run `wasm-pack test`. This step should run the test
4. run `cargo test --target=wasm32-unknown-unknown`. This step should give error
#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.0
rustc version: 1.30.0-nightly (bb0896af1 2018-09-29)

**Comment by fitzgen** [comment]
To clarify, does step (3) successfully run the test? You shouldn't need to run (4) at all, (3) is doing it for you with the configuration knobs dialed in correctly.

**Comment by huangjj27** [comment]
@fitzgen Yes, Step (3) works, but according to [the guide](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#configure-cargoconfig-to-use-the-test-runner), I can also run tests with `cargo test --target=wasm32-unknown-unknown` after once the `wasm-pack test` had run?

**Comment by fitzgen** [comment]
I need to clarify the docs a bit, but here is the take away: you should just run `wasm-pack test`.

`cargo test --target wasm32-unknown-unknown` will only work if you set up the config yourself. What `wasm-pack test` is doing is running it configured ephemerally (through env vars). But you *don't* need to run `cargo test` after `wasm-pack test` -- `wasm-pack test` is running `cargo test` for you.

Going to close this issue since everything seems to be working as expected, except the docs are confusing. Thanks for opening this issue!
