### ISSUE TITLE
can't `use $MY_CRATE` for $MY_CRATE/tests/$SOME_TEST.rs

### ISSUE THREAD

**Issue by huangjj27** [rustwasm/wasm-pack#398]
## 🐛 Bug description
In fact, I don't know if this is a bug of wasm-pack. It seems like a bug of cargo but only appear in my wasm-pack project.

when I use the template and [add test](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#write-some-tests) it works but keeps failing after I add a `use $MY_CRATE`.

#### 🤔 Expected Behavior
It should recognize $MY_CRATE!

#### 👟 Steps to reproduce
1. make a template project follow [this](https://rustwasm.github.io/wasm-pack/book/project-setup/using-a-template.html), input a crate name(in my case, it's `wasm-pack-learn`)
2. add `edition = "2018"` to Cargo.toml
3. [add test](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html#write-some-tests)  to `$MY_CRATE/tests/wasm.rs` and run `wasm-pack test --node`, it should work.
4. add a `use wasm_pack_learn` to `wasm.rs`. Then the cargo complaint it doesn't find the `wasm_pack_learn` in root.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.0
rustc version: 1.30.0-nightly (bb0896af1 2018-09-29)

**Comment by huangjj27** [comment]
add a `rlib` type to `[lib]` makes the crate imported, but still can't run the test.

**Comment by fitzgen** [comment]
Are you literally include "$MY_CRATE" in the directory path? To be clear, $MY_CRATE is supposed to be replaced by your own crate, so it would be `wasm-pack-learn` in this case.

**Comment by huangjj27** [comment]
Yes，those vars are replaced with the actual directories

**Comment by fitzgen** [comment]
Hey @huangjj27 -- I tried to reproduce by following the steps you laid out and everything seems to work as expected for me.

Can you clone https://github.com/fitzgen/wp-issue-398 and run `wasm-pack test --node` locally? Does it work for you?

Can you push your repo where `wasm-pack test --node` is failing to github so I can clone it and try reproducing locally?

Thanks!

**Comment by huangjj27** [comment]
Good Evening(From China)! I'm sorry for late to reply. I just upload [the project causing error](https://github.com/huangjj27/wasm-pack-learn), and I'm trying to download your project to test. I'll feedback as soon

**Comment by huangjj27** [comment]
I can't repeat the error now. But the only thing I did is that I made a commit to git while before I had even made one. Does it matter?

**Comment by fitzgen** [comment]
Found the problem!

The `tests/wasm.rs` file contains this:

```rust
use wasm-pack-learn;
```

but identifiers in Rust can't have "-" in them, so you reference them via snake case. Changing it to the following makes imports work.

```rust
// Note: if not using 'edition = "2018"' in Cargo.toml, need to have extern crate imports
extern crate wasm_pack_learn;

// Note: can't simply `use wasm_pack_learn` if not using 2018 edition, as that tries to
// import the crate twice with the same name.
use wasm_pack_learn::whatever;
```

The Cargo.toml also didn't have `rlib` as a crate type, which is also necessary to import it as library from rust.

I think that should resolve this issue, if you run into anything else, let me know! :)
