### ISSUE TITLE
wasm-pack should check if it's the latest version and warn if not

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#403]
when you run build, wasm-pack should check and see what version is latest on crates.io and if the current installed version is latest. if not, it should suggest the user update.

**Comment by daubaris** [comment]
I would love to work on this one!

**Comment by drager** [comment]
@daubaris: Hey, I discussed this very briefly on IRC with @ashleygwilliams. One approach to this is to check the behavior of the [npm client](https://npme.npmjs.com/docs/cli/installation.html) or [yarn](https://yarnpkg.com) and see what they output for outdated packages. Npm outputs something like: "npm WARN ..." with a yellow background and black text. Yarn outputs something like: "warning ..." in yellow text. So maybe, the text could be something like: "warning (in yellow) :warning: There's a newer version of wasm-pack available, the new version is x.x.x and you're using version x.x.x". 

Regarding the approach to this issue. I first had the idea of using something like [hyper](https://crates.io/crates/hyper) for this. Make a request to the [crates api](https://crates.io/api/v1) and fetch the latest version of the crate and then compare that to installed one. However, `wasm-pack` already depends on the [curl crate](https://crates.io/crates/curl) so I think that's a better choice. So, use curl to fetch the latest version of the crate from the crates api and then compare that version with the locally installed one, then output a warning if there's a newer one available.

This is my understanding of the feature request, so anyone, please correct me if I'm wrong.

**Comment by ashleygwilliams** [comment]
closed by #409
