### ISSUE TITLE
wasm-pack build should copy over the license file

### ISSUE THREAD

**Issue by tschneidereit** [rustwasm/wasm-pack#407]
Currently, license files aren't copied over. It's not entirely clear to me how best to do this, given that license files can have different names. Perhaps do (the equivalent of) `cp LICENSE* pkg`?

**Comment by ashleygwilliams** [comment]
oh dang, good catch! do you think it would be reasonable enough to copy over whatever the LICENSE key in Cargo.toml points to? that'd be my first impl strategy...

**Comment by tschneidereit** [comment]
Ah, yes—I think that'd be entirely adequate.

**Comment by mstallmo** [comment]
If no one has jumped on this one yet I'd like to take a crack at implementing this!

**Comment by ashleygwilliams** [comment]
you got it @mstallmo - go for it! thanks so much!
