### ISSUE TITLE
Document that wasm-pack supports --target no-modules in --help

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#416]
## 💡 Feature description

wasm-pack should expose wasm-bindgen's no-modules mode as a `--target no-modules` option.

More info:

* https://rustwasm.github.io/wasm-bindgen/reference/no-esm.html
* https://rustwasm.github.io/wasm-bindgen/examples/no-modules.html
* https://rustwasm.github.io/wasm-bindgen/reference/cli.html#a--no-modules-and----no-modules-global-var

#### 💻 Basic example

```
wasm-pack build --target no-modules
```

**Comment by mstallmo** [comment]
@fitzgen I was just taking a look at this and as far as I can tell it looks like this is implemented in `bindgen.rs` it's just not documented when running `wasm-pack build --help`. Is this correct or did I miss some more work that needs to be done?

**Comment by ashleygwilliams** [comment]
lol whoops, i totally implemented this. we just need to doc it 😅 https://github.com/rustwasm/wasm-pack/commit/64c5a22ff6f20a9b20790b50480dceb1c5e1d28d

**Comment by ashleygwilliams** [comment]
actually also it's documented: https://rustwasm.github.io/wasm-pack/book/commands/build.html#target

closing

**Comment by mstallmo** [comment]
Would this be something we want to add to the —help print out for the build command or is it okay as is? 

Currently the help flag only displays browser and nodejs as valid options for target.

**Comment by fitzgen** [comment]
> Would this be something we want to add to the —help print out for the build command or is it okay as is?
> 
> Currently the help flag only displays browser and nodejs as valid options for target.

Oh yes, we totallly need to do this.

This is why I thought it wasn't supported and had this weird deja vu feeling :-p

**Comment by kylejlin** [comment]
I'd be happy to help. However, I'm having trouble finding the file responsible for printing the help text. Could somebody tell me where that is?
