### ISSUE TITLE
Safari test panics and fails

### ISSUE THREAD

**Issue by C-Saunders** [rustwasm/wasm-pack#418]
## 🐛 Bug description
When running `cargo test` with a fresh, unmodified, clone of the repository, the test `test::it_can_run_browser_tests` panics and fails (message below).

It seems possible this is a similar issue to https://github.com/SeleniumHQ/selenium/issues/6026, but I don't really know.

If I set `safari = false` [here](https://github.com/rustwasm/wasm-pack/blob/master/tests/all/test.rs#L68), the tests all pass.

#### 🤔 Expected Behavior
The test should have been able to execute successfully (and pass).

#### 👟 Steps to reproduce
```
> git clone https://github.com/rustwasm/wasm-pack.git
> cd wasm-pack
> cargo [+nightly] test
```

Message:
```
thread 'test::it_can_run_browser_tests' panicked at 'should run test command OK: Cli { message: "`cargo test` did not exit successfully", stdout: "no tests to run!
Executing bindgen...
Running headless tests in Safari with `/System/Library/CoreServices/SafariSupport.bundle/Contents/MacOS/safaridriver`
Spawning Geckodriver...
Starting new webdriver session...
driver status: signal: 9
stderr: "Finished dev [unoptimized + debuginfo] target(s) in 0.21s
Running /Users/charlie/Sites/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/wbg_test_browser-c13678d3d70b53cd.wasm
Running /Users/charlie/Sites/rust/wasm-pack/target/wasm32-unknown-unknown/debug/deps/browser-e14d52d7b333ecc7.wasm
error: non-200 response code: 500
{
    "value": {
        "error":"session not created",
        "message":"Request body does not contain required parameter 'capabilities'.",
        "stacktrace":""
    }
}
error: test failed, to rerun pass '--test browser'
exit_status: ExitStatus(ExitStatus(256))"}
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.5.1
rustc version: rustc 1.31.0-nightly (4699283c5 2018-10-13)
cargo version: 1.31.0-nightly (5dbac9888 2018-10-08)
MacOS version: 10.14 (18A391)
Safari version: 12.0 (14606.1.36.1.9)

**Comment by fitzgen** [comment]
Safari requires some sort of flag or something be run at least once to enable WebDriver automation. I don't have a mac handy at the moment to double check. But yeah we should figure out what this flag is and then document it.

**Comment by C-Saunders** [comment]
Thanks for your reply, @fitzgen! I found [this Apple documentation](https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari) that says what you said to do:

> Run `safaridriver --enable` once

I did this (with and without `sudo`), but unfortunately it didn't fix the issue.

-- Below is my understanding so far. It seems I should close this issue and open one on wasm-bindgen instead. Please let me know if you disagree, otherwise I will do that in a couple of days once I have some time.

I dug around for a while until I figured out that these test are running through [wasm-bindgen-test-runner](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli/src/bin/wasm-bindgen-test-runner).

Further testing (see below) confirmed the key piece is [this part](https://github.com/rustwasm/wasm-bindgen/blob/master/crates/cli/src/bin/wasm-bindgen-test-runner/headless.rs#L284) of the code - the Safari driver's `request` JSON data doesn't include a `capabilities` object, whereas the Gecko one does. [Geckodriver](https://github.com/mozilla/geckodriver) is a W3C driver, as is [Safari 12](https://developer.apple.com/documentation/webkit/macos_webdriver_commands_for_safari_12_and_later), whereas earlier versions of Safari do not use the W3C protocol.

I was able to reproduce the issue by cloning wasm-bindgen and running the tests:
```
Running headless tests in Safari with `safaridriver`
driver status: signal: 9
error: non-200 response code: 500
{"value":{"error":"session not created","message":"Request body does not contain required parameter 'capabilities'.","stacktrace":""}}
```
Updating the payload to include a `capabilities` object resulted in a different error:
```
Running headless tests in Safari with `safaridriver`
driver status: signal: 9
error: missing field `sessionId` at line 1 column 198
```
I think this means a 200 status code was returned, but the response data wasn't in the expected shape.

To me this says that either
1. wasm-bindgen-test-runner should run `safaridriver` with `--legacy`, but I haven't yet figured out how to make that happen
1. wasm-bindgen-test-runner should run `safaridriver` with a W3C payload, but I haven't gotten it to work yet, likely because it's missing some important configuration, and I can't find docs for Safari

I also have concerns about this only working with Safari 12, but `safaridriver` doesn't seem to surface version information.
