### ISSUE TITLE
Support README.txt and README.rst etc

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-pack#421]
## 💡 Feature description

Add support for various kinds of README files, not hard-coding only README.md. Right now we will only copy README.md into the package, not any other kind of README file. We can iterate over the files in the crate directory, find all files whose name (without extension) is "README" and copy those over.

#### 💻 Basic example

* `README.rst` -- restructured text
* `README.txt` -- plain text
* `README.html` -- html
* `README` -- plain text with no extension
* etc...

**Comment by ashleygwilliams** [comment]
Are we sure we want to do this? npm doesn't support these so I'm not sure it makes sense for us to support them.

**Comment by ashleygwilliams** [comment]
i think we have decided we are only going to support README.md for now. willing to revisit later.
