### ISSUE TITLE
Compiler output doesn't have colors

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#423]
## 🐛 Bug description

I just now realized that there wasn't an issue filed for this! But compiler diagnostics (from rustc and Cargo) both don't have color when executed through `wasm-pack`, due to the piping that `wasm-pack` currently does which disables the auto-detection of colors and such.

**Comment by fitzgen** [comment]
Is there a way to force colors? If we let the child process inherit our own stdout/stderr, then we can't also log the output, nor can we return stdout/stderr or stuff them into the `Error` if the child exits nonzero.

**Comment by alexcrichton** [comment]
I think the same trick cargo uses for rustc may be able to work with wasm-pack? Cargo basically always passes `--color always` to rustc and always captures the output. This causes rustc to use ansi escape codes on all platforms, and then cargo uses the [fwdansi crate](https://crates.io/crates/fwdansi) to translate the ansi codes to native APIs on Windows

**Comment by alexcrichton** [comment]
er actually this is a dupe of https://github.com/rustwasm/wasm-pack/issues/288
