### ISSUE TITLE
Terminal spam on windows

### ISSUE THREAD

**Issue by tbillington** [rustwasm/wasm-pack#429]
## 🐛 Bug description

Output is spammed when running `wasm-pack build` in git bash on windows.

![image](https://user-images.githubusercontent.com/2771466/47995336-11112a80-e149-11e8-8047-eb20c6f38aa5.png)

#### 🤔 Expected Behavior

Less spam.

#### 👟 Steps to reproduce

Run `wasm-pack build` in a project from git bash on windows.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: `0.5.1`
rustc version: `rustc 1.32.0-nightly (e6c5cf923 2018-11-04)`

**Comment by fitzgen** [comment]
See also https://github.com/rustwasm/wasm-pack/issues/298

**Comment by tbillington** [comment]
@fitzgen Ah, I scanned for existing issues but didn't pick up on that one, cheers.

**Comment by alexcrichton** [comment]
In addition to #298 I think this is covered by https://github.com/rustwasm/wasm-pack/issues/284 as well, so I'm going to close this in favor of those two issues
