### ISSUE TITLE
How to uninstall wasm-pack

### ISSUE THREAD

**Issue by LEXUGE** [rustwasm/wasm-pack#449]
title.
How to uninstall wasm-pack which was installed by `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`

**Comment by drager** [comment]
If you're on a unix-like os then you should be able to do: `rm $(which wasm-pack)`.

**Comment by LEXUGE** [comment]
OK, thank you very much.

**Comment by f1am3d** [comment]
> If you're on a unix-like os then you should be able to do: `rm $(which wasm-pack)`.

windows
