### ISSUE TITLE
Allow passing extra command-line flags to cargo

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-pack#455]
## 💡 Feature description
I'm often building my packages on CI with `--locked` / `--frozen` after the dependencies have been downloaded.

I'd like to do the same with `wasm-pack` but currently there is no way to pass extra args to underlying `cargo` command.

#### 💻 Basic example

I think it would make sense to be able to pass extra arbitrary args after `--` as many other wrappers do, so that one could run:

```bash
$ wasm-pack build wasm-folder -- --frozen
```

**Comment by ibaryshnikov** [comment]
I would like to use it too

**Comment by ashleygwilliams** [comment]
i'm amenable to this for sure and once i get 0.6.0 out the door we can plan this for the next release!

**Comment by ashleygwilliams** [comment]
thanks to an unforeseen issue with the release last night which gave us some time to think on design, we'll be able to get this into 0.6.0.
