### ISSUE TITLE
Any examples without the use of bundlers?

### ISSUE THREAD

**Issue by overlandandseas** [rustwasm/wasm-pack#456]
Does this tool support or if not plan to support importing modules without the use of a tool like webpack or parcel? To my understanding is it not officially supported in browsers as they will reject modules with type `application/wasm` so an example with `fetch` would be nice to see in the documentation. Sorry if that is not the intention of this product.

**Comment by fitzgen** [comment]
You can use `wasm-pack build --target no-modules` to build for plain old `<script>` tags and `fetch`. See https://rustwasm.github.io/wasm-bindgen/examples/no-modules.html

**Comment by ashleygwilliams** [comment]
@overlandandseas were you able to check out what @fitzgen suggested? i agree that we can do better on making the nodejs and no-module use cases clearer and will be doing some work on the docs/website to help with that!

**Comment by overlandandseas** [comment]
It certainly helps, I did not see these docs previously as I was only looking at wasm-pack. Thanks!
