### ISSUE TITLE
error: failed to read `target/wasm32-unknown-unknown/release/cargo.wasm`

### ISSUE THREAD

**Issue by hajsf** [rustwasm/wasm-pack#458]
I got the below error:

```
 [9/9] 🏃‍♀️  Running WASM-bindgen...
  error: failed to read `target/wasm32-unknown-unknown/release/cargo.wasm`
|       caused by: No such file or directory (os error 2)
Running the wasm-bindgen CLI
Caused by: Process exited with exit code: 1: `wasm-bindgen` did not exit successfully.

stdout:

stderr:

error: failed to read `target/wasm32-unknown-unknown/release/cargo.wasm`
        caused by: No such file or directory (os error 2)

```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: "0.2.29"
rustc version: 1.31.0

**Comment by fitzgen** [comment]
Are you using cargo workspaces? We have support for workspaces in master, but not in the latest release quite yet.

Also, 0.2.X wasm-pack is pretty old! I suggest updating :)

**Comment by fitzgen** [comment]
>  wasm-pack version: "0.2.29"

er wait, I don't think there ever was a wasm-pack 0.2.29 -- is this your wasm-bindgen?

**Comment by hajsf** [comment]
Sorry @fitzgen  it is my mistake, the "2.2.29" is `wasm-bindgen` and looks I was having error somewhere else, now my code is running. thanks
