### ISSUE TITLE
Rust language services complains about code being unsafe

### ISSUE THREAD

**Issue by cromefire** [rustwasm/wasm-pack#459]
I'm using the hello world example from the Readme and my IDE (aka. the rust language service) is complaining about `alert()` being unsafe.

- without unsafe the IDE complaines, but build works
- with unsafe the IDE ist okay, but the build warns about unnecessary unsafe

Is there anything I forgot to adjust?
Or should I just use unsafe an ignore it?

**Comment by alexcrichton** [comment]
I wonder if perhaps your IDE isn't expanding macros? The expansion of `#[wasm_bindgen]` is needed to show how it's not an unsafe function.

**Comment by fitzgen** [comment]
This is a bug in the RLS where it is not looking at the macro-expanded code. Extern functions are always unsafe, but wasm-bindgen expands the `alert` into a safe, non-external function that handles the raw unsafe call for you.

**Comment by fitzgen** [comment]
Jinx ;)

I'd recommend filing a bug upstream in the RLS issue tracker.

**Comment by cromefire** [comment]
Oh yes, it actually seems like the IntelliJ plugin doesn't even use rls, despite the fact that the was a note somewhere that this is used by the IDE plugins.
Found a matching bug.
Sorry I'm still new to rust and normally use scripting languages.

**Comment by cromefire** [comment]
But I guess this additional unsafe doesn't break anything?
