### ISSUE TITLE
Clarify intent of wasm-pack and commands

### ISSUE THREAD

**Issue by grovesNL** [rustwasm/wasm-pack#466]
The description of wasm-pack in this repository:
> wasm-pack helps you build and publish rust-generated WebAssembly to the npm registry to be used alongside any other javascript package in workflows that you already use, such as webpack or greenkeeper.

This seems to indicate wasm-pack is only used when publishing the output to a registry, but wasm-pack appears to be usable for other use cases. The front page at https://rustwasm.github.io/wasm-pack/ also doesn't contain many details which makes it difficult to understand the intended use cases. This is a bit confusing for users that don't want to publish to npm (for example, running `wasm-pack build` for internal use in their project).

I wanted to raise this here because rustwasm/wasm-bindgen#1120 mentioned that wasm-pack is an appropriate replacement for the example build scripts there. It seems to be working great and gives me the expected output, but I'm unsure if I'm misusing the CLI (`Your wasm pkg is ready to publish at "/Users/josh/Projects/js-hello-world/pkg".` even though I don't want to publish anything).

**Comment by grovesNL** [comment]
The [commands](https://rustwasm.github.io/wasm-pack/book/commands/index.html) section in the book describes the commands pretty well and does clarify that publishing is optional. So I guess there could be some improvements here:

- Add more details about possible use cases for wasm-pack on both gh-pages and repository readme could be useful.
- Maybe `wasm-pack build` should note that publishing is optional or rephrase the current message.
- Describe how to setup a project to match the examples in wasm-bindgen. For example, whenever I run `wasm-pack build` the package.json is overwritten, so it's unclear how to add a `serve` script to the `pkg/package.json` without it being replaced each time. Maybe there's another way to do it but glancing through the documentation it wasn't obvious.

Let me know if there are established best practices already, I'd be happy to send a PR to try to clarify.

**Comment by ashleygwilliams** [comment]
this is going to be handled partially by a PR in this repo and partially in a set of others! i'm closing because we'll file more granular issues for the to do items, thank you so much for this thoughtful issue! it was very helpful :)

**Comment by grovesNL** [comment]
Sounds great, thank you!
