### ISSUE TITLE
Fix clippy warnings in the codebase

### ISSUE THREAD

**Issue by mstallmo** [rustwasm/wasm-pack#477]
While working on a different refactor I ran clippy on the codebase and noticed that it gave a handful of warnings about various parts of the code. We should probably refactor the flagged code to be in line with the clippy lints. 

Along this line are there any clippy lints that we want to ignore/diverge from or should we follow all of the linting rules?

**Comment by ashleygwilliams** [comment]
hey @mstallmo thanks for tackling this! in general, i'm open to the clippy defaults, my primary concern is balancing the clippy lints with code readability (for maintainability sake). i'll take a look at your PR and comment there!
