### ISSUE TITLE
Cargo command calls don't output color to the terminal

### ISSUE THREAD

**Issue by otaviopace** [rustwasm/wasm-pack#480]
## 💡 Feature description
When `wasm-pack` runs `cargo build` for example, under the hood, the output of it has no color.

#### 💻 Basic example
In the image down below, this part should have color just like using `cargo build` directly on the terminal.
![screenshot from 2019-01-03 19-55-23](https://user-images.githubusercontent.com/15306309/50663813-0bda2b80-0f92-11e9-81a7-0616466695b1.png)

Part without color:
```shell
  [4/9] Compiling to WASM...
      Finished release [optimized] target(s) in 0.04s
```

I honestly would like to have color because it eases to understand errors on the terminal :slightly_smiling_face: 

Example of error without color:

![screenshot from 2019-01-03 20-55-41](https://user-images.githubusercontent.com/15306309/50666016-097bcf80-0f9a-11e9-822c-6a3270bb0b6f.png)

Example with color:

![screenshot from 2019-01-03 20-57-06](https://user-images.githubusercontent.com/15306309/50666029-1ac4dc00-0f9a-11e9-9380-4f84f2417d76.png)

**Comment by ibaryshnikov** [comment]
is it still an issue? @otaviopace @ashleygwilliams 
wasm-pack output for current version (0.8.1) is colored enough, it looks like it was fixed in one of the releases

**Comment by otaviopace** [comment]
Honestly I don't know because I don't have that computer anymore 😕 . Maybe we can close the issue, and later if I or anyone suffers from it, we can re open it.

**Comment by ashleygwilliams** [comment]
closing- sorry to hear about your computer @otaviopace ! please file a new issue if this is still a problem.
