### ISSUE TITLE
move binary install crate to its own repo?

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#500]
the "workspace" setup for binary install atm is... not ideal. i think i would, once we feel it's sufficiently decoupled from active dev in wasm-pack (which may be now since the global cache work landed?) to move it to its own repo in the org, completely working around the confusion around workspaces. this will also allow us to do release notes, etc, with no added noise to this repo. do folks have thoughts?

cc @drager

**Comment by drager** [comment]
I agree that it would be a good idea to move it to it's own repo, since it is no longer coupled to wasm-pack and could potentially be used by other projects as well.

**Comment by ashleygwilliams** [comment]
looks like we're dealing with some issues with binary install panicking so we shouldn't move too quickly on this- but once we've done that moving it to it's own repo and giving it some unit tests seems like a good idea.

**Comment by drager** [comment]
@ashleygwilliams How's the status here? Is the panic resolved? If it's solved I think we could move this now, since #517 is merged.

**Comment by ashleygwilliams** [comment]
@drager i think we can do this now! i'll make a repo and add you as a contrib! (assuming you want to take this on?)

**Comment by drager** [comment]
@ashleygwilliams That sounds good!

**Comment by drager** [comment]
New repository for binary-install can be found here: https://github.com/rustwasm/binary-install
