### ISSUE TITLE
Redirecting Error in Book

### ISSUE THREAD

**Issue by DebugSteven** [rustwasm/wasm-pack#513]
### 🐛 Bug description
When you click on the `documentation` link from the [wasm pack URL](https://rustwasm.github.io/wasm-pack/), the [documentation URL](https://rustwasm.github.io/wasm-pack/book/) has the path `/wasm-pack/book/`. This breaks the links listed in the body of the page for Rust & NPM which are expecting a path of `/wasm-pack/book/prerequisites/`.

#### 🤔 Expected Behavior
The links for Rust & NPM should be redirected to regardless of how you navigate to the prerequisites section in the wasm pack book.

#### 👟 Steps to reproduce
Start from the [repo](https://github.com/rustwasm/wasm-pack) 
Click on the [tutorial URL](https://rustwasm.github.io/wasm-pack/) linked in the description
Click on the `documentation` nav-bar element
Notice the URL shows https://rustwasm.github.io/wasm-pack/book/
In the page, click the link for Rust
You are redirected to https://rustwasm.github.io/wasm-pack/book/rust.html
OR 
In the page, click the link for NPM
You are redirected to https://rustwasm.github.io/wasm-pack/book/npm.html
Both result in a 404 page not found

#### Environment
This was on firefox 64.0.2. I think this issue is browser agnostic.

#### Possible Fix
I believe the code that sets the current path for the wasm pack book is here:
https://github.com/rustwasm/wasm-pack/blob/c8410f2de71e4b024e8b9a6d356d50c90d035e03/docs/index.html#L28

This could be possibly be changed to 
`<a href="/wasm-pack/book/prerequisites/">Documentation</a>`
or 
`<a href="/wasm-pack/book/prerequisites/index.html">Documentation</a>`

I tested those solutions & both seemed to work.

**Comment by drager** [comment]
Thank you for this report @DebugSteven! I pushed a fix in #514 that I hope will fix this as well as some other broken links.
