### ISSUE TITLE
bump up the wasm-bindgen version in test?

### ISSUE THREAD

**Issue by huangjj27** [rustwasm/wasm-pack#519]
## 💡 Feature description
I notice that different test use a different version of  wasm-bindgen, I think we can use the same version(I mean always the newest version) of wasm-bindgen, so that ALL THE TEST would use the same cache

#### 💻 Basic example
the test that use fixture has locked the `wasm-bindgen` and `wasm-bindgen-test` to version `0.2.21`,(for example, `it_should_build_js_hello_world_example`) while other test that generates its fixture (for exmaple, `build_with_and_without_wasm_bindgen_debug`) may use just the auto-patching version config of `0.2`.
that means we have to download at least 2 version of wasm-bindgen cache for testing, and that spends a lot of time (especially for worker in country with network inspection where slow down github).

but if we bump up the `wasm-bindgen` version of fixture to `0.2`, we can use the same cache and will only fetch `wasm-bindgen` only one time.

related to #447

**Comment by ashleygwilliams** [comment]
@huangjj27 i'd happily accept a PR for this- this is a good catch! thanks for filing an issue!

**Comment by ashleygwilliams** [comment]
closing as we've landed #526 via #554
