### ISSUE TITLE
Pass arbritrary arguments from wasm-pack test to wasm-bindgen-test

### ISSUE THREAD

**Issue by chinedufn** [rustwasm/wasm-pack#525]
I started using wasm-pack at 0.6.0 and it's been great - thanks!

---

My biggest point of friction so far is trying to TDD with `wasm-pack` test. Needing to run an entire test suite when I'm focused one one function is no fun.

In #524 I had an idea for how to fix that, but I'm realizing that it adds a one off flag that might not really need to exist.

Instead, what if you could just pass anything through to `cargo test`?

```sh
# Anything after `--` gets passed to the `cargo test`
wasm-pack test --firefox --headless -- --package my-workspace-crate my_test_name --color=always
```

```rust
[wasm_bindgen_test]
fn my_test_name() {
  assert_eq!(2, 2);
}
```

In this way `wasm-pack` wouldn't need to support every little request that someone might have. We just expose `cargo test` and call it a day.

---

Could this work in theory? Any holes in my thinking? How difficult would this be (I'm unfamiliar with the codebase)?

Cheers!

\cc @fitzgen since you know a good bit about `wasm-pack test`

**Comment by chinedufn** [comment]
I've used `wasm-bindgen-test` to run individual tests / tests matching a given string many times - but maybe we're both talking about different things or I'm just misunderstanding?

An example of what I mean:

```sh

GECKODRIVER=geckodriver cargo test --manifest-path crates/web-sys/Cargo.toml --target wasm32-unknown-unknown --all-features test_olist_element 
```

The above runs only the `test_olist_element` test in the `web-sys` crate.

---

So I don't think that `wasm-bindgen-test` needs to be touched here. I think we'd just need to pass everything after `--` as arguments to `cargo test` wherever we're building that command.

How does that sound to you?

---

And yes, regardless I'd be happy to PR an attempt! Just want to get on the same page about implementation.

**Comment by fitzgen** [comment]
Ah, ok then I am misinformed!

> I think we'd just need to pass everything after `--` as arguments to `cargo test` wherever we're building that command.

:+1:

**Comment by alexcrichton** [comment]
@chinedufn's spot on, I've got nothing else to add!
