### ISSUE TITLE
Wrong error message for missing chromedriver binaries and missing fallback

### ISSUE THREAD

**Issue by jscheffner** [rustwasm/wasm-pack#535]
## 🐛 Bug description
When running `wasm-pack test --chrome` on a 64 bit Windows machine I get the error message `geckodriver binaries are unavailable for this target`.

#### 🤔 Expected Behavior
I would expect a fallback to win32 if a win64 binary is not available. In case there are some arguments against this, I'd still expect the error message to be `chromedriver binaries are unavailable for this target`. This is possibly a copy/paste error.

#### 👟 Steps to reproduce
Run `wasm-pack test --chrome` on a 64 bit Windows machine.

#### 🌍 Your environment
wasm-pack version: 0.6.0
rustc version: 1.32.0

**I'd like to submit a PR for this issue, but first I want to know if it should only fix the error message or actually implement the fallback to the win32 binary, so I'd really appreciate some feedback.**

**Comment by ashleygwilliams** [comment]
hey @jscheffner thanks for filing this! i am running on a 64-bit mac machine and am not seeing this behavior- so this may be a windows only bug- which is very interesting!

i'd like to get someone to reproduce this, just to confirm, before we move forward. i think a PR that does the fallback seems very reasonable and would be something we want, but i do want to make sure we have a clear understanding of the scope of the problem before we act on a solution!

i have a 64-bit windows machine that i will try this out on now!

**Comment by ashleygwilliams** [comment]
can confirm that i reproduced this on windows!

**Comment by ashleygwilliams** [comment]
so- i get:

```
| [5/6] Getting chromedriver...
Error: geckodriver binaries are unavailable for this target
PS C:\Users\ashley\Projects\wasm-pack-template>
```

https://github.com/mozilla/geckodriver/releases -> this has a win64 binary...
my understanding is that chromedriver doesn't release a separate 32 vs 64 bit binary... https://sites.google.com/a/chromium.org/chromedriver/downloads

it's doubly weird that i asked it to test chrome and the error message says it's looking for the geckodriver :/

@fitzgen any thoughts on this? otherwise i can dig into the code and figure out why this is failing.

**Comment by jscheffner** [comment]
[This](https://github.com/rustwasm/wasm-pack/blob/dc97112908196529d5ba181d37c2a750e465cdfe/src/test/webdriver.rs#L26) is the function that is causing the problems. First of all, it provides the wrong error message and secondly, it only installs a binary if its linux64, mac64 or win32. So implementing a fallback to win32 for win64 would be straightforward. I guess for linux32 and mac32 the error is reasonable (if the "typo" is fixed).

**Comment by ashleygwilliams** [comment]
@jscheffner ah yeah- given that the chromedriver purportedly does not care about arch we shouldn't check arch at all. there's simply one binary per platform (https://chromedriver.storage.googleapis.com/index.html?path=2.45/)

so yes- please fix this logic to simply detect platform and not arch, update the error message, and if you wouldn't mind, seems like we should update the chromedriver version to 2.45!

@fitzgen as the original implementer- is there a specific reason you did it like this? if so- please weigh in! thanks :)

**Comment by fitzgen** [comment]
* Yep, "geckodriver" is just a copy-paste bug, as theorized

* Yeah, they don't seem to release 64-bit webdriver clients

* I only checked for exact arch matches since I wasn't sure about how exactly falling back to 32 bit works. If it should Just Work, then I am+1 for Just Doing It :)

**Comment by sanisoclem** [comment]
Is there any workaround for now?

**Comment by jscheffner** [comment]
@sanisoclem: You can download the binary yourself and then use the `--chromedriver` option with the path to your binary.

**Comment by jscheffner** [comment]
This is the download link for the binary: https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip
