### ISSUE TITLE
Is support wasm-merge?

### ISSUE THREAD

**Issue by unordered** [rustwasm/wasm-pack#541]
Is support wasm-merge or any way to link other .wasm file?

**Comment by ashleygwilliams** [comment]
hi @unordered ! we do not currently support wasm-merge but i am curious and open to learning more about it. could you talk more about the way you would imagine it work? sharing the workflow you currently have, or an example, would help me understand and evaluate this feature request! thanks for writing it :)

**Comment by ashleygwilliams** [comment]
this issue has been open for more than a month with no answer. @unordered if you'd like to continue discussing this, please comment and i'll reopen!
