### ISSUE TITLE
Anyone stucking in [9/10] ⬇️  Installing wasm-bindgen...? is it downloading sth? my network not too good...

### ISSUE THREAD

**Issue by zzz6519003** [rustwasm/wasm-pack#548]

**Comment by ashleygwilliams** [comment]
@zzz6519003 if you are stuck, one thing you can do is install wasm-bindgen directly (either using `cargo install wasm-bindgen` or by downloading [one of the releases](https://github.com/rustwasm/wasm-bindgen/releases)) once you have manually installed wasm-bindgen, you can use `wasm-pack build` and it should leverage your preinstalled `wasm-bindgen`. if that doesn't work you can run `wasm-pack build --no-install` to force `wasm-pack` to use the version you already installed. let me know how that works for you!

**Comment by zzz6519003** [comment]
good idea!

**Comment by zzz6519003** [comment]
seems not problem of wasm-bindgen

**Comment by ashleygwilliams** [comment]
@zzz6519003 are you still having an issue? can you let me know any more details? thanks!

**Comment by ashleygwilliams** [comment]
this issue is stale, so i'm closing. @zzz6519003 if you are still having an issue please comment or open a new issue!
