### ISSUE TITLE
Unexpected panics should still print the full panic message

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#562]
Unexpected panics are unfortunate but they're currently covered up and written out to an auxiliary file. This makes [panics in CI](https://dev.azure.com/rustwasm/wasm-weight-tracker/_build/results?buildId=33) difficult to debug, especially at a glance, as CI builders are likely not uploading those files.

`wasm-pack` should still print something to the console indicating what sort of error just happened.

**Comment by drager** [comment]
I will start working on this.
