### ISSUE TITLE
wasm-pack can't install wasm32-unknown-unkonwn target on DragonFly BSD

### ISSUE THREAD

**Issue by strangelittlemonkey** [rustwasm/wasm-pack#589]
## 🐛 Bug description
Following the hello world tutorial example, I seem to hit 32bit requirements on a 64bit only operating system.

The following was observed, and annotated in another issue here:

I tried building off commit badbe1c, as well as off the 0.6.0 tag and the 0.7.0 tag, all failed. This was as well with the hello world example.

In order:     0.6.0, 0.7.0, master 

```
zach@dev03 ~/wasm-pack-template> wasm-pack build

  [1/10] Checking `rustc` version...
  [2/10] Checking crate configuration...
| [3/10] Adding WASM target...
Error: Adding the wasm32-unknown-unknown target with rustup
Caused by: No such file or directory (os error 2)
zach@dev03 ~/wasm-pack-template> ../wasm-pack/target/release/wasm-pack build
[INFO]: Checking for the Wasm target...
Error: wasm32-unknown-unknown target not found!
zach@dev03 ~/wasm-pack-template> ../wasm-pack/target/release/wasm-pack build
[INFO]: Checking for the Wasm target...
Error: wasm32-unknown-unknown target not found!
```

#### 🤔 Expected Behavior
I expected that the hello world example would work out of the box, but it's possible that the documentation is not explicit that only 32bit compilation is supported and/or that 32bit libraries are required and/or that rustup support is required with 32bit binaries and libraries for this.

#### 👟 Steps to reproduce
I did a git clone of the wasm-pack-template (my version of cargo does not support generate), so I then edited the Cargo.toml for an arbitrary author name and project name.

I installed the latest release of wasm-pack by cargo (0.6.0 as of this morning) and tried to do wasm-pack build, after not working and finding an issue exhibiting what I thought was the issue, checked out the source and did a git checkout of 0.7.0, with the a similar error. I then checked out master and tried on master with the same error as on 0.7.0.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.6.0,0.7.0, master (badbe1c37a752963243da526b6fb01b66e7889bd)
rustc version: 1.31.1

**Comment by Pauan** [comment]
> I seem to hit 32bit requirements on a 64bit only operating system.

What OS are you using that is 64-bit only and doesn't support rustup?

> but it's possible that the documentation is not explicit that only 32bit compilation is supported and/or that 32bit libraries are required and/or that rustup support is required with 32bit binaries and libraries for this.

I use Windows 10 64-bit, and I've also used Linux 64-bit, and they work fine.

To be clear, `wasm32-unknown-unknown` does *not* mean that your system must be 32-bits, instead it means that the *wasm runtime* must be 32-bits (and currently *all* wasm runtimes are 32-bits).

So you can use `wasm32-unknown-unknown` on 64-bit systems perfectly fine.

So I suspect this isn't related to the fact that you're using a 64-bit system, instead I think it's a misconfiguration somewhere else.

**Comment by strangelittlemonkey** [comment]
I am running it on DragonFly BSD, which removed all 32bit support, and has no rustup support. You cannot run 32bit binaries on DragonFly BSD anymore, since at least the last few years.

What you're not taking into account is that while you may be running a 64bit Windows or 64bit Linux, that you have 32bit compatibility layers, and for simplicity sake of the OS those have been stripped out of DragonFly BSD.

This basically means that wasm, in its current form, will never work with DragonFly BSD. What is the constraint making it 32bit in 2019? Is there intent to move to 64bit?

**Comment by strangelittlemonkey** [comment]
Either way, the documentation should be explicit that wasm is 32bit only and requires a 32bit system, whether that be the host or the compatibility layer, the lack thereof means it will not work.

**Comment by Pauan** [comment]
I'm very hesitant to conclude that wasm-pack requires 32-bits. Nothing in your error logs suggests a lack of 32-bits. So I think we should first figure out what is causing the errors.

**Comment by ashleygwilliams** [comment]
Yeah, i‘m p certain this is likely related to the new non rustup env support- it was a great first pass but i imagine we‘ll need to do more work to make it more robust to the wide range of long tail unorthodox setups. the 32/64 bit part is likely less a concern and mor elikely tied to path issues, if i had to guess at first glance.

**Comment by strangelittlemonkey** [comment]
I’m not sure you’re getting me. Most 64bit OSes have 32bit compat layers and toolchains to build 32bit targets for the same OS. DragonFly specifically removed all of those. You cannot build anything 32bit at all on DragonFly. Whether I’m pulling a prebuilt binary or building it myself, there is no 32bit support in DragonFly any longer.

**Comment by strangelittlemonkey** [comment]
/// Ensure that `rustup` has the `wasm32-unknown-unknown` ta\rget installed for                                           /// current toolchain                                        pub fn check_for_wasm32_target() -> Result<(), Error> {
    let msg = format!("{}Checking for the Wasm target...", e\moji::TARGET);
    PBAR.info(&msg);

// Check if wasm32 target is present, otherwise bail.        match check_wasm32_target() {
        Ok(true) => Ok(()),
        Ok(false) => bail!("wasm32-unknown-unknown target no\t found!"),
Err(err) => Err(err),
    }
}



Reading that which produces the error does seem to imply that rustup support and 32bit are hard requirements for the project though.

**Comment by Pauan** [comment]
@strangelittlemonkey I am fully aware of how 32-bit compat libraries work on Linux and BSD, and I am saying that I do not think it is related to this issue.

Have you tried [manually installing the `wasm32-unknown-unknown` target](https://www.reddit.com/r/rust/comments/9t95fd/howto_setting_up_webassembly_on_stable_rust/)? I think that will help us get to the bottom of this.

**Comment by strangelittlemonkey** [comment]
Well, as mentioned, this is with an OS that is not supported by rustup. rustc binaries thus aren't readily available for the OS to just install, so I can fetch the wasm32 from there, but it's built against rustc 1.30.0, and my Rust option is 1.31.1, because that version had the necessary porting patches fleshed out to be able to build successfully.

If you can provide a working 1.31.1 wasm32 or a 1.30.0 rustc for DragonFly, I can continue down the manual path to test, but with DragonFly validation of this will be difficult because it's still basically under the assumption of rustup working but just not being used to be able to fetch prebuilt binaries like this. There is no x86_64-unknown-dragonfly built and hosted.

**Comment by Pauan** [comment]
You can just change the URL to point to your version:

https://static.rust-lang.org/dist/rust-std-1.31.1-wasm32-unknown-unknown.tar.gz

Then running `install.sh` *should* work, but since you're on DragonFly it might not, in which case we'll have to install it manually.

**Comment by strangelittlemonkey** [comment]
I could've sworn I had a 404 on that yesterday.

In any event,

zach@dev03 ~/wasm_test> cargo build --release --target=wasm32-unknown-unknown --verbose
   Compiling wasm_test v0.1.0 (/home/zach/wasm_test)
     Running `rustc --edition=2018 --crate-name wasm_test src/lib.rs --color always --crate-type cdylib --crate-type rlib --emit=dep-info,link -C opt-level=3 -C metadata=4b32409b131872e9 --out-dir /home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps -L dependency=/home/zach/wasm_test/target/release/deps`
error[E0514]: found crate `std` compiled by an incompatible version of rustc
  |
  = help: please recompile that crate using this compiler (rustc 1.31.1)
  = note: the following crate versions were found:
          crate `std` compiled by rustc 1.31.1 (b6c32da9b 2018-12-18): /usr/local/lib/rustlib/wasm32-unknown-unknown/lib/libstd-921f6025b6b0ca40.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0514`.
error: Could not compile `wasm_test`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name wasm_test src/lib.rs --color always --crate-type cdylib --crate-type rlib --emit=dep-info,link -C opt-level=3 -C metadata=4b32409b131872e9 --out-dir /home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps -L dependency=/home/zach/wasm_test/target/release/deps` (exit code: 1)

**Comment by alexcrichton** [comment]
I agree with @Pauan and @ashleygwilliams that the error here is likely related, if at all, to https://github.com/rustwasm/wasm-pack/pull/552. I see a few issues here with the OP:

The first error is:

```
Error: Adding the wasm32-unknown-unknown target with rustup
Caused by: No such file or directory (os error 2)
```

My guess is that this "no such file or directory" is `rustup` itself and we failed to spawn a `rustup` process. @strangelittlemonkey you're not using `rustup` right?

The second two errors:

```
Error: wasm32-unknown-unknown target not found!
```

indicate that `wasm-pack` detected that rustup was not in use, but also detected that the wasm32-unknown-unknown target was not installed, so it gave an error. Currently there's not a good documentation link for installing on non-rustup setups, but this is where it would go!

@strangelittlemonkey also to confirm, you didn't previously have 0.6.0 working, right? Or if you did, how did you acquire and install the wasm32-unknown-unknown target?

**Comment by strangelittlemonkey** [comment]
This is DragonFly BSD. There is no rustup support for it. I pulled and built wasm-pack 0.6.0, 0.7.0, and master.

In the end I fetched https://static.rust-lang.org/dist/rust-std-1.31.1-wasm32-unknown-unknown.tar.gz as pauan asked, though I assume the error there is as much the ABI mismatch as it is architecture and no 32bit compat in the OS, but I don't know, to be honest.

**Comment by strangelittlemonkey** [comment]
I could add some debugging code to wasm-pack to get more specifics about when/where it's hitting what if you want, but it'll have to wait until tonight.

**Comment by alexcrichton** [comment]
@strangelittlemonkey and to confirm, this wasn't working previously with 0.6.0 and before, right?

Matching binary release of Rust is sort of hard right now, so I'm not entirely surprised that the 1.31.1 binaries for wasm don't work with your compiler. It may be that your compiler is patched slightly or something like that (or just somehow built differently than upstream rust-lang/rust) to make them incompatible, but that's not a big worry.

FWIW the error is [coming from here](https://github.com/rustwasm/wasm-pack/blob/15974fec17b15b513b008b3a7e752cea6259b446/src/build.rs#L119), which indicates that we don't know how to install the wasm32-unknown-unknown target on your system.

I've also gone ahead and updated the title of the issue to what I believe the underlying problem is

**Comment by strangelittlemonkey** [comment]
Yeah that was what I copied in link https://github.com/rustwasm/wasm-pack/issues/589#issuecomment-473934474

DragonFly tends to fall behind in versions of Rust a bit because of the level of patching needed on our end so we were on 1.29.2 until this weekend and thus I was excited to test wasm out, which led to this. I’ve never had it work yet.

**Comment by ashleygwilliams** [comment]
@strangelittlemonkey thanks so much for your patience on this. we'll be making a release today (0.8.0) that should contain a better error message for your situation. we've also added some documentation on non-rustup setups here: https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html

in order to run wasm-pack you'll need rust 1.30 or later, so it may be that you are also running into trouble with that. if you've still got some energy for this i'd love to try to see if we can figure something out! i'd love to at least hear your feedback on the docs and the new error message, though ideally we can get stuff working for you.

**Comment by strangelittlemonkey** [comment]
So, back when Pauan made the suggestion to run install.sh, it mostly worked. I had to patch it slightly for the shebang (FreeBSD and DragonFly BSD put third party binaries into /usr/local, so it's /usr/local/bin/bash).

I'm running with rustc 1.31.1

This was the output after following the instructions though and the readme, but having to build with the instructions from earlier in here.

zach@dev03 ~/wasm_test> cargo build --release --target=wasm32-unknown-unknown --verbose
   Compiling proc-macro2 v0.4.27
   Compiling unicode-xid v0.1.0
     Running `rustc --crate-name build_script_build /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.27/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=d81874f1ff771e25 -C extra-filename=-d81874f1ff771e25 --out-dir /home/zach/wasm_test/target/release/build/proc-macro2-d81874f1ff771e25 -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
     Running `rustc --crate-name unicode_xid /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.1.0/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' -C metadata=f45a5719b9efc769 -C extra-filename=-f45a5719b9efc769 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling syn v0.15.29
     Running `rustc --crate-name build_script_build /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-0.15.29/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="proc-macro2"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=73aee550b51f56aa -C extra-filename=-73aee550b51f56aa --out-dir /home/zach/wasm_test/target/release/build/syn-73aee550b51f56aa -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling wasm-bindgen-shared v0.2.40
     Running `rustc --crate-name build_script_build /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-shared-0.2.40/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=de1cdde14cf8d04a -C extra-filename=-de1cdde14cf8d04a --out-dir /home/zach/wasm_test/target/release/build/wasm-bindgen-shared-de1cdde14cf8d04a -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling cfg-if v0.1.7
     Running `rustc --crate-name cfg_if /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.7/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=d4a6b71dcb858e94 -C extra-filename=-d4a6b71dcb858e94 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling lazy_static v1.3.0
     Running `rustc --crate-name lazy_static /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=7c0d3ee427a1de46 -C extra-filename=-7c0d3ee427a1de46 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling bumpalo v2.3.0
     Running `rustc --edition=2018 --crate-name bumpalo /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-2.3.0/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="collections"' --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=4fd89b3c9aa3f916 -C extra-filename=-4fd89b3c9aa3f916 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling wasm-bindgen v0.2.40
     Running `rustc --crate-name build_script_build /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.40/build.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="spans"' --cfg 'feature="std"' --cfg 'feature="wasm-bindgen-macro"' -C metadata=86a0173b7803c2d5 -C extra-filename=-86a0173b7803c2d5 --out-dir /home/zach/wasm_test/target/release/build/wasm-bindgen-86a0173b7803c2d5 -L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
     Running `/home/zach/wasm_test/target/release/build/proc-macro2-d81874f1ff771e25/build-script-build`
     Running `/home/zach/wasm_test/target/release/build/syn-73aee550b51f56aa/build-script-build`
   Compiling log v0.4.6
     Running `rustc --crate-name log /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.6/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=db8cc8c3a4a379c8 -C extra-filename=-db8cc8c3a4a379c8 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern cfg_if=/home/zach/wasm_test/target/release/deps/libcfg_if-d4a6b71dcb858e94.rlib --cap-lints allow`
     Running `/home/zach/wasm_test/target/release/build/wasm-bindgen-shared-de1cdde14cf8d04a/build-script-build`
     Running `/home/zach/wasm_test/target/release/build/wasm-bindgen-86a0173b7803c2d5/build-script-build`
     Running `rustc --crate-name proc_macro2 /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.27/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=d54dbe3eb5cd7cbf -C extra-filename=-d54dbe3eb5cd7cbf --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern unicode_xid=/home/zach/wasm_test/target/release/deps/libunicode_xid-f45a5719b9efc769.rlib --cap-lints allow --cfg u128 --cfg use_proc_macro --cfg wrap_proc_macro`                                                                    
     Running `rustc --crate-name wasm_bindgen_shared /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-shared-0.2.40/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=d929b4ae35d0c157 -C extra-filename=-d929b4ae35d0c157 --out-dir /home/zach/wasm_test/target/release/deps
-L dependency=/home/zach/wasm_test/target/release/deps --cap-lints allow`
   Compiling quote v0.6.11
     Running `rustc --crate-name quote /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-0.6.11/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="proc-macro"' --cfg 'feature="proc-macro2"' -C metadata=db689de2f5f5b5e2 -C extra-filename=-db689de2f5f5b5e2 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern proc_macro2=/home/zach/wasm_test/target/release/deps/libproc_macro2-d54dbe3eb5cd7cbf.rlib --cap-lints allow`                                                                                                        
     Running `rustc --crate-name syn /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-0.15.29/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="proc-macro2"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=b84ec93e7f2e9339 -C extra-filename=-b84ec93e7f2e9339 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern proc_macro2=/home/zach/wasm_test/target/release/deps/libproc_macro2-d54dbe3eb5cd7cbf.rlib --extern quote=/home/zach/wasm_test/target/release/deps/libquote-db689de2f5f5b5e2.rlib --extern unicode_xid=/home/zach/wasm_test/target/release/deps/libunicode_xid-f45a5719b9efc769.rlib --cap-lints allow --cfg syn_can_use_thread_id --cfg syn_can_call_macro_by_path`               
   Compiling wasm-bindgen-backend v0.2.40
     Running `rustc --crate-name wasm_bindgen_backend /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-backend-0.2.40/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="spans"' -C metadata=20f61dd4426e8eea -C extra-filename=-20f61dd4426e8eea --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern bumpalo=/home/zach/wasm_test/target/release/deps/libbumpalo-4fd89b3c9aa3f916.rlib --extern lazy_static=/home/zach/wasm_test/target/release/deps/liblazy_static-7c0d3ee427a1de46.rlib --extern log=/home/zach/wasm_test/target/release/deps/liblog-db8cc8c3a4a379c8.rlib --extern proc_macro2=/home/zach/wasm_test/target/release/deps/libproc_macro2-d54dbe3eb5cd7cbf.rlib --extern quote=/home/zach/wasm_test/target/release/deps/libquote-db689de2f5f5b5e2.rlib --extern syn=/home/zach/wasm_test/target/release/deps/libsyn-b84ec93e7f2e9339.rlib --extern wasm_bindgen_shared=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_shared-d929b4ae35d0c157.rlib --cap-lints allow`
   Compiling wasm-bindgen-macro-support v0.2.40
     Running `rustc --edition=2018 --crate-name wasm_bindgen_macro_support /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-support-0.2.40/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="spans"' --cfg 'feature="wasm-bindgen-backend"' -C metadata=2e5f5a6e90763270 -C extra-filename=-2e5f5a6e90763270 --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern proc_macro2=/home/zach/wasm_test/target/release/deps/libproc_macro2-d54dbe3eb5cd7cbf.rlib --extern quote=/home/zach/wasm_test/target/release/deps/libquote-db689de2f5f5b5e2.rlib --extern syn=/home/zach/wasm_test/target/release/deps/libsyn-b84ec93e7f2e9339.rlib --extern wasm_bindgen_backend=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_backend-20f61dd4426e8eea.rlib --extern wasm_bindgen_shared=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_shared-d929b4ae35d0c157.rlib --cap-lints allow` 
   Compiling wasm-bindgen-macro v0.2.40
     Running `rustc --crate-name wasm_bindgen_macro /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-0.2.40/src/lib.rs --color always --crate-type proc-macro --emit=dep-info,link -C prefer-dynamic -C opt-level=3 --cfg 'feature="spans"' --cfg 'feature="wasm-bindgen-macro-support"' -C metadata=9ed308615f58739f -C extra-filename=-9ed308615f58739f --out-dir /home/zach/wasm_test/target/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern quote=/home/zach/wasm_test/target/release/deps/libquote-db689de2f5f5b5e2.rlib --extern wasm_bindgen_macro_support=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_macro_support-2e5f5a6e90763270.rlib --cap-lints allow`
     Running `rustc --crate-name wasm_bindgen /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.40/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="spans"' --cfg 'feature="std"' --cfg 'feature="wasm-bindgen-macro"' -C metadata=eee6d2bd09a2053d -C extra-filename=-eee6d2bd09a2053d --out-dir /home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern wasm_bindgen_macro=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_macro-9ed308615f58739f.so --cap-lints allow`
error[E0514]: found crate `core` compiled by an incompatible version of rustc
  |
  = help: please recompile that crate using this compiler (rustc 1.31.1)
  = note: the following crate versions were found:
          crate `core` compiled by rustc 1.31.1 (b6c32da9b 2018-12-18): /usr/local/lib/rustlib/wasm32-unknown-unknown/lib/libcore-bc99d396b91fe14a.rlib

error: aborting due to previous error

For more information about this error, try `rustc --explain E0514`.
error: Could not compile `wasm-bindgen`.

Caused by:
  process didn't exit successfully: `rustc --crate-name wasm_bindgen /home/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.40/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="spans"' --cfg 'feature="std"' --cfg 'feature="wasm-bindgen-macro"' -C metadata=eee6d2bd09a2053d -C extra-filename=-eee6d2bd09a2053d --out-dir /home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/home/zach/wasm_test/target/wasm32-unknown-unknown/release/deps -L dependency=/home/zach/wasm_test/target/release/deps --extern wasm_bindgen_macro=/home/zach/wasm_test/target/release/deps/libwasm_bindgen_macro-9ed308615f58739f.so --cap-lints allow` (exit code: 1)



zach@dev03 ~/wasm_test> rustc --version
rustc 1.31.1

I don't see wasm-pack 0.8.0 available yet to install.

**Comment by ashleygwilliams** [comment]
wasm-pack 0.8.1 is out- could you let me know if it helps at all @strangelittlemonkey ?

**Comment by ashleygwilliams** [comment]
@strangelittlemonkey are you still having this issue?

**Comment by ashleygwilliams** [comment]
closing as inactive- please reopen if there's more progress to be made here!
