### ISSUE TITLE
Consider making wasm-pack a cargo subcommand

### ISSUE THREAD

**Issue by dvc94ch** [rustwasm/wasm-pack#591]
## Cargo subcommand
It would be nice if the wasm workflow was close to the non wasm workflow. So `cargo build`, `cargo test` and `cargo run` should work out of the box. wasm specific commands would be under `cargo wasm publish-npm` or something like that.

#### 💻 Basic example
I made a simple `wasm-bindgen-runner` which wraps `wasm-bindgen-test-runner` and also works for `cargo run` and `cargo run --example {}`.

**Comment by ashleygwilliams** [comment]
hey! i have discussed this with @nrc a bunch while we planned for the year. not sure where we're at with that convo but i'll follow up with him. this is a very long term goal that doesn't look *exactly* like a subcommand- but maybe more like a cargo "extension" that's made more discoverable by crates.io. i don't think here is the best place to track is as i don't think we're close enough to a fine grained planned for this type of tracking- but know we're working on it!
