### ISSUE TITLE
move tests and release to github actions

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#594]
after submitting a PR to wasm-bindgen, i'm really impressed with azure pipelines. the speed is really awesome and will really improve the experience here, especially the release process. i would really like to move us over. cc @rylev

**Comment by alexcrichton** [comment]
I've set up https://dev.azure.com/rustwasm/wasm-pack for when this is ready to go!

**Comment by rylev** [comment]
🎉🎉 I'm happy to help with the move. Let me know what you'd like me to do.
