### ISSUE TITLE
Pass `--target web` to wasm-bindgen instead of `--web`

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/wasm-pack#597]
This is intended to be a tracking issue for integration https://github.com/rustwasm/wasm-bindgen/pull/1369 fully into `wasm-pack`. That PR to wasm-bindgen "deprecated" old target flags like `--web`, `--no-modules`, etc. The deprecated flags are still accepted without warning, but all documentation shoul ideally point towards `--target` now.

Currently `wasm-pack` passes the old flags for `--web` and such, and I think that it will want to continue doing so for the near future as well. Once enough users have upgraded `wasm-bindgen` and older versions start getting naturally phased out, we'll want to switch `wasm-pack` to passing down the `--target` flag as well (probably just passing it through directly to `wasm-bindgen`).

**Comment by nicksrandall** [comment]
is there a workaround for this? Currently `wasm-pack --web` and `wasm-pack --target web` both say they have invalid arguments.

**Comment by ashleygwilliams** [comment]
thanks for commenting @nicksrandall ! can you file this as a separate ticket? i am trying to reproduce your error and am not running into it- i suspect that the problem you are having is unrelated to this ticket! (it may be that your wasm-bindgen dep in your project needs to be updated? just a guess)

**Comment by nicksrandall** [comment]
You were right @ashleygwilliams. Thank you!! Please disregard my comment.

**Comment by ashleygwilliams** [comment]
we should update wasm-pack to use the new `--target` flag here: https://github.com/rustwasm/wasm-pack/blob/master/src/bindgen.rs#L44

**Comment by ashleygwilliams** [comment]
version this was released in was 0.2.40

**Comment by ashleygwilliams** [comment]
clsoed by #682
