### ISSUE TITLE
Can we set proxy or use a environment variable of download url when download the prebuilt binary 

### ISSUE THREAD

**Issue by rrandom** [rustwasm/wasm-pack#605]
## 💡 Feature description
When the network condition is not good, could wasm-pack set the proxy of `curl`, or using a environment variable of the download url? just like `SASS_BINARY_SITE`  for `node-sass`

#### 💻 Basic example
Include a basic code example if possible. Omit this section if not applicable.

**Comment by ashleygwilliams** [comment]
hi @rrandom ! are you familiar with the --mode no-install? this will allow you to skip your install and will simply expect that the required tools are in path. would this fulfill your requirements?

**Comment by rrandom** [comment]
@ashleygwilliams Thanks for pointing out. I thinks it enough now

**Comment by ashleygwilliams** [comment]
great to hear! i'll close, but please file again if you have any ideas on making that experience better!

**Comment by toymil** [comment]
Hi @ashleygwilliams , in the case of headless chrome what should I do?

`wasm-pack` can't download `chromedriver_linux64.zip`, I think it did not pick up my `http(s)_proxy` environment variable.

**Comment by toymil** [comment]
> in the case of headless chrome what should I do

If `chromium-driver` is already installed from the system package manager, wasm-pack doesn't seems to need to download its own _chromedriver_.
