### ISSUE TITLE
wasm-pack test --node starts safari

### ISSUE THREAD

**Issue by ibaryshnikov** [rustwasm/wasm-pack#634]
## 🐛 Bug description
`wasm-pack test --node` runs tests in safari instead of (or in addition to) node.js

#### 🤔 Expected Behavior
It should run tests only in node.js

#### 👟 Steps to reproduce
Run some tests with `wasm-pack test --node` on mac

#### 🌍 Your environment
wasm-pack version: 0.8.0
rustc version: 1.34.0

**Comment by drager** [comment]
@ibaryshnikov Thanks for the report! I believe this was fixed in #630. So this should make it into the `0.9.0` release.

**Comment by ibaryshnikov** [comment]
Oh, I didn't see it. @drager thank you! I'll close this since the pr has already been merged
