### ISSUE TITLE
Error: File not found

### ISSUE THREAD

**Issue by ThomasdenH** [rustwasm/wasm-pack#637]
## 🐛 Bug description
When running `wasm-pack build`, I get the following error message:

```
Error: Het systeem kan het opgegeven bestand niet vinden. (os error 2)
```

(The system can't find the given file.)

#### 🤔 Expected Behavior
No error and the project builds.

#### 👟 Steps to reproduce
This error occurs any project I've tested. The simplest way to reproduce is to create a new project and follow the guide in the readme from there.

`Cargo.toml`
```Cargo.toml
[package]
name = "wasm-pack-test"
version = "0.1.0"
authors = ["Thomas <denhollander.thomas@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
```

`src/lib.rs`
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn main() {
    println!("Hello, world!");
}

```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: wasm-pack 0.8.1
rustc version: rustc 1.34.1 (fc50f328b 2019-04-24)
(Windows 10 Pro - Version: 1803 - Build: 17134.706)

**Comment by ThomasdenH** [comment]
I should note that the `wasm-pack` command itself is working. I get the version correctly with `wasm-pack --version`. Running `wasm-pack build --dev` also crashes without additional output.

**Comment by ThomasdenH** [comment]
I'd gladly help if I can provide additional information or test something!

**Comment by fitzgen** [comment]
> ```rust
> 
> #[wasm_bindgen]
> pub fn main() {
>     println!("Hello, world!");
> }
> ```

Does it still happen if you name this something other than `main`? The symbol `main` is a bit special and I could see there being conflicts here.

Aside: `println!` won't work on wasm by default because there is no `stdout`. You probably want to use something like https://github.com/iamcodemaker/console_log instead.

**Comment by ThomasdenH** [comment]
I have changed the contents of `lib.rs` to the following, but unfortunately that didn't fix the issue.
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn add(a: u32, b: u32) -> u32 {
    a + b
}
```

**Comment by ThomasdenH** [comment]
Using `dbg!` I have found the offending line:

```
[src\manifest\mod.rs:349] cargo_metadata::metadata(Some(&manifest_path)) = Err(
    Error(
        Io(
            Os {
                code: 2,
                kind: NotFound,
                message: "Het systeem kan het opgegeven bestand niet vinden."
            }
        ),
        State {
            next_error: None,
            backtrace: InternalBacktrace {
                backtrace: None
            }
        }
    )
)
```

**Comment by ThomasdenH** [comment]
The manifest path is `".\\Cargo.toml"`, which correctly prints using the command `cat .\\Cargo.toml`.

**Comment by ThomasdenH** [comment]
I have figured it out. My `cargo` variable was pointing to an invalid location.
