### ISSUE TITLE
wasm-pack provides no output when its version check fails

### ISSUE THREAD

**Issue by sgrif** [rustwasm/wasm-pack#652]
## 🐛 Bug description
When wasm-pack checks to see if a more recent version is released, the error is silently swallowed. Since this is an optional behavior, it makes sense to not bother the user if they're not online or something, but (as documented in #651) -- this check *always* fails, which has been the case for a few days, and gone unnoticed.

It's unlikely that a request to crates.io will complete with a non-200 status code, it seems reasonable to at least inform the user something happened in this case.

**Comment by drager** [comment]
I think it makes sense, I submitted a fix in #660.
