### ISSUE TITLE
wasm-pack does not rate limit its version check if the request fails

### ISSUE THREAD

**Issue by sgrif** [rustwasm/wasm-pack#653]
## 🐛 Bug description
When wasm-pack looks for a more recent version, it limits this check to once every 24 hours normally. When the request fails, however, it will try again on the next run. Based on our logs, there are folks who are running wasm-pack in a loop on their home network. Since all of these version checks are currently being blocked (#651), this has resulted in a substantial enough spike in 4xx traffic to be noticeable on our graphs.

 If the reason this failed is because crates.io has gone down due to being overloaded, this can amplify the problem. There should be some form of exponential backoff in the case of an error.

#### 🤔 Expected Behavior
wasm-pack should not immediately retry its version check if the last one failed.

**Comment by fitzgen** [comment]
It seems fine to me to apply the 24 hours rate limiting regardless if the check succeeded or failed.

**Comment by fitzgen** [comment]
+cc @drager @daubaris

**Comment by drager** [comment]
Thanks for bringing this up @sgrif! I will try to get a PR that fixes this.

**Comment by drager** [comment]
Fixed in #660.
