### ISSUE TITLE
Unrecognized platform

### ISSUE THREAD

**Issue by carlomilanesi** [rustwasm/wasm-pack#661]
I am trying to install Wasm from https://rustwasm.github.io/wasm-pack/
running an Italian version of Windows 10. The "ver" command prints:
Microsoft Windows [Versione 10.0.17134.765]
Other info:
navigator.platform: Win32
navigator.appVersion: 5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
When I click on "INSTALL WASM-PACK 0.8.1", I get the message: I don't recognize your platform.

**Comment by ibaryshnikov** [comment]
@carlomilanesi so you are running 32-bit windows? It looks like there are only 64-bit binaries are provided at the moment, and it's likely that the web page is not able to recognize the 32-bit platform. Is running `cargo install wasm-pack` an option for you?

@ashleygwilliams any plans to support 32-bit systems so far?

**Comment by ashleygwilliams** [comment]
@carlomilanesi thanks for filing! were you able to install using `cargo install` ?

**Comment by ashleygwilliams** [comment]
closing as there has been no response for a long time. please open a new issue if you continue to have this problem!
