### ISSUE TITLE
Generated package doesn't include snippets folder

### ISSUE THREAD

**Issue by Redrield** [rustwasm/wasm-pack#663]
## 🐛 Bug description
The generated package.json when running `wasm-pack build` only contains the top level `.js`, `.ts`, and `.wasm` in the `"files"` array. However, the generated module requires more code under snippets/ that isn't included in the array. Hence, when the generated code is packaged, snippets/ is excluded and the code will fail to run (webpack fails to package the code entirely).

#### 🤔 Expected Behavior
All the required files for execution should be included in the package

#### 👟 Steps to reproduce
Using a simple template, run `wasm-pack build`. While the top level js file will reference files under snippets, the `"files"` array will only contain the top level files.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.8.1
rustc version: rustc 1.37.0-nightly (6ffb8f53e 2019-06-03)

The simplest way to fix this would simply be to add "snippets/" to the generated package.json, under the files array.

**Comment by ibaryshnikov** [comment]
Related to #557

**Comment by ibaryshnikov** [comment]
According to npm [documentation](https://docs.npmjs.com/files/package.json#files), we can use `files: ["*"]` to include everything. What do you think? @ashleygwilliams  @fitzgen

**Comment by ashleygwilliams** [comment]
this relates to #557 - closing in favor of that- we'll discuss this at the next rustwasm meeting!
