### ISSUE TITLE
debug flag not passed to wasm-bindgen-cli

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#677]
```
failures:

---- build::build_with_and_without_wasm_bindgen_debug stdout ----
Created fixture at /Users/ag_dubs/OpenSource/rustwasm/wasm-pack/target/t/.tmpdZ5X82/wasm-pack
thread 'build::build_with_and_without_wasm_bindgen_debug' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`: Should only contain moved value assertions when debug assertions are enabled', tests/all/build.rs:195:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by ashleygwilliams** [comment]
any thoughts @fitzgen or @alexcrichton ?

**Comment by ashleygwilliams** [comment]
getting these on master now too https://travis-ci.com/rustwasm/wasm-pack/jobs/216579394#L538

**Comment by ashleygwilliams** [comment]
per in chat convo with @fitzgen- looks like we are testing on the contents of the error message.. which may have changed https://github.com/rustwasm/wasm-pack/blob/master/tests/all/build.rs#L197 i'll run it manually and see.

**Comment by fitzgen** [comment]
I don't see any difference between the JS glue when build with `debug-js-glue = true` or `debug-js-glue = false`.

**Comment by fitzgen** [comment]
I verified via `strace` that `wasm-pack` is not invoking `wasm-bindgen` with the `--debug` flag regardless whether `debug-js-glue` is set or not. Furthermore, if I manually invoke `wasm-bindgen` with `--debug` then the move assertion does appear in the JS glue.

**Comment by fitzgen** [comment]
False alert: I was building with the release profile and the test/configuration was for the dev profile.

`wasm-pack` is passing `--debug` to `wasm-bindgen` but `wasm-bindgen` is no longer emitting the assertion.
