### ISSUE TITLE
Packages fail to build on Raspberry PI 3B+

### ISSUE THREAD

**Issue by Sakul6499** [rustwasm/wasm-pack#688]
## 🐛 Bug description
When building a simple wasm-pack project on a Raspberry PI 3B+ it fails to compile multiple packages.

Probelmatic packages:
 - unicode-xid
 - libc
 - proc-macro2
 - cc

Interestingly, the issue only occurs when using wasm-pack.
Executing `cargo build` works perfectly fine!

#### 🤔 Expected Behavior
The project should compile just fine as it does on other system/environments.

#### 👟 Steps to reproduce
Create a simple wasm-pack project and build it on a Raspberry PI 3B+.
No special environment or flags are used.

Multiple packages fail to build with the 'same' error message:
```
error: Could not compile `unicode-xid`.

Caused by:
  process didn't exit successfully: `rustc --crate-name unicode_xid /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-xid-0.1.0/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C opt-level=s --cfg 'feature="default"' -C metadata=5fc21202269c1c07 -C extra-filename=-5fc21202269c1c07 --out-dir /srv/http/preview.sakul6499.de/src/rust/dots/target/release/deps -L dependency=/srv/http/preview.sakul6499.de/src/rust/dots/target/release/deps --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
```
Most notably: `signal: 11, SIGSEGV: invalid memory reference`
wasm-pack build log: [wasm-build-log.txt](https://github.com/rustwasm/wasm-pack/files/3411935/wasm-build-log.txt)

However, again: Utilizing `cargo build` works just fine!
cargo build log: [cargo-build-log.txt](https://github.com/rustwasm/wasm-pack/files/3411943/cargo-build-log.txt)

I also tried to debug it with `rust-gdb` without any real success ...
Maybe it helps?
[rust-gdb-log.txt](https://github.com/rustwasm/wasm-pack/files/3411945/rust-gdb-log.txt)

I think the issue might is related to the limited resources on a Raspberry PI 3B+.
When monitoring, CPU utilization goes up to 100% (zero iowait though) and the free/available-RAM goes down to nearly nothing.
It also takes a notable time after each error to continue ...
Thus, it might be connected to e.g. [rust-issue 56501](https://github.com/rust-lang/rust/issues/56501).

#### 🌍 Your environment
Raspberry PI 3B+, with [ArchLinux ARM](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3).

wasm-pack version: `0.8.1`
rustc version: `rustc 1.36.0 (a53f9df32 2019-07-03)`
cargo version: `cargo 1.36.0 (c4fcfb725 2019-05-15)`
linux version: `Linux rpi3 4.19.58-1-ARCH #1 SMP PREEMPT Tue Jul 16 01:25:23 UTC 2019 armv7l GNU/Linux`

**Comment by ashleygwilliams** [comment]
i am a little out of my depth on Rust embedded knowledge... any thoughts @jamesmunns?

**Comment by humb1t** [comment]
Using `cargo install wasm-pack` on Raspberry I found the following issue:
```
error[E0277]: the trait bound `[u8; 2]: std::convert::From<&[u8]>` is not satisfied                                                                                          
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.3.2/src/inflate/core.rs:342:44                                                                 
    |                                                                                                                                                                        
342 |         let two_bytes = iter.as_ref()[..2].try_into().unwrap();                                                                                                        
    |                                            ^^^^^^^^ the trait `std::convert::From<&[u8]>` is not implemented for `[u8; 2]`                                             
    |                                                                                                                                                                        
    = note: required because of the requirements on the impl of `std::convert::TryFrom<&[u8]>` for `[u8; 2]`                                                                 
    = note: required because of the requirements on the impl of `std::convert::TryInto<[u8; 2]>` for `&[u8]`                                                                 
                                                                                                                                                                             
error: aborting due to 12 previous errors                                                                                                                                    
                                                                                                                                                                             
Some errors occurred: E0277, E0658.                                                                                                                                          
For more information about an error, try `rustc --explain E0277`.                                                                                                            
error: Could not compile `miniz_oxide`.                                                                                                                                      
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.8.1`, intermediate artifacts can be found at `/tmp/cargo-installFC3jzB`       
```

So it's also not an option.

**Comment by humb1t** [comment]
@Sakul6499 I updated Rust using `--force` and tried `cargo install wasm-pack` one more time. After additional fixes of libssl wasm-pack has been built successfully. Please try and post the result.

**Comment by Sakul6499** [comment]
Updating didn't work, but completely removing rust (including rustup) and reinstalling everything did. Build now succeeds.
Unfortunately, the root cause is still unknown.
