### ISSUE TITLE
wasm-opt not working on latest master

### ISSUE THREAD

**Issue by torch2424** [rustwasm/wasm-pack#696]
relates to #625 

## 🐛 Bug description

The installed `wasm-opt` with `wasm-pack` on the [current master](https://github.com/rustwasm/wasm-pack/commit/439e523192676fb481b14a79ea88d03a953164e0) isn't working an exits with signal 6:

![Screenshot from 2019-07-29 07-36-12](https://user-images.githubusercontent.com/1448289/62056996-9525a980-b1d3-11e9-9b52-f5d6a804f21f.png)

#### 🤔 Expected Behavior

`wasm-opt` should run, optimize the wasm file, and not error/stop building the package with `wasm-pack`

#### 👟 Steps to reproduce

1. Clone the repo
2. `cargo run build [path to your rust wasm module]`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: [current master](https://github.com/rustwasm/wasm-pack/commit/439e523192676fb481b14a79ea88d03a953164e0)
rustc version: 1.34.1

cc @alexcrichton :smile:

**Comment by alexcrichton** [comment]
What OS are you running on? (e.g. Ubuntu/Debian/etc)

Additionally can you upload the wasm file which causes this segfault?

**Comment by torch2424** [comment]
@alexcrichton 

> What OS are you running on? (e.g. Ubuntu/Debian/etc)

Oops totally forgot that :joy: 

![Screenshot from 2019-07-31 01-11-56](https://user-images.githubusercontent.com/1448289/62195149-39246780-b330-11e9-9ca3-5fcf6a8af836.png)

pop_OS! is a derivative of Ubuntu :smile: 

> Additionally can you upload the wasm file which causes this segfault?

So here is the terminal output:

![Screenshot from 2019-07-31 01-14-41](https://user-images.githubusercontent.com/1448289/62195361-b18b2880-b330-11e9-9e22-4061f4f8e569.png)

So from that, I assume I need to get the `pkg/wasmboypluginhqx_bg.wasm`. Which you can [download here](https://files.aaronthedev.com/$/qhvs3).

Let me know if that helps! :smile:

**Comment by alexcrichton** [comment]
Ok using the `release_78` binaries locally myself I can get `-O3` to segfault when running over that wasm file. Additionally using the latest `release_87` it segfaults. I've opened https://github.com/WebAssembly/binaryen/issues/2273 as an upstream issue.

**Comment by torch2424** [comment]
@alexcrichton Awesome! Thank you very much! 😄 Stoked I can help!

**Comment by anp** [comment]
Now that [version_89](https://github.com/WebAssembly/binaryen/releases/tag/version_89) is released, would it make sense to attempt updating the [wasm-opt installer version](https://github.com/rustwasm/wasm-pack/blob/master/src/wasm_opt.rs#L87)?

**Comment by ashleygwilliams** [comment]
@anp i know this is a super late message but did you happen to try version 90? want to release wasmpack1.9.0 soon and do not want to break all linux users

**Comment by ashleygwilliams** [comment]
i'm going to close this because i do believe that today's release will fix it. if it does not- please open a new issue!
