### ISSUE TITLE
emit memory.grow events

### ISSUE THREAD

**Issue by aminroosta** [rustwasm/wasm-pack#700]
## 💡 Feature description
TypedArrays underlying `memory.buffer` will get detached on a successful `memory.grow()` call.

 In other words any view into webassembly memory needs to be recreated on memory.grow.

I want to make this automated, so anytime that memory grows, all those views get refreshed automatically.

#### 💻 Basic example

```rust
pub fn offset(&self) -> *mut u8 { self.vec.as_ptr() }
pub fn len(&self) -> usize { self.vec.len() }
pub fn push(&mut self, n: u8) { self.vec.push(n) }
```

```js
const vec_u8view = new Uint8Array(memory.buffer, t.offset(), t.len());
t.push(1);
// vec_u8view is now possibly invalidated (if the vec had to resize)
// TODO: find out a way to keep this view up to date on memory grows
```

**Comment by Pauan** [comment]
A memory grow event has [some tricky issues](https://github.com/WebAssembly/design/issues/1210).

Instead, it's standard to just do a quick check and recreate the typed array if needed:

```js
let cachegetUint8Memory = null;

function getUint8Memory() {
    if (cachegetUint8Memory === null || cachegetUint8Memory.buffer !== memory.buffer) {
        cachegetUint8Memory = new Uint8Array(memory.buffer);
    }

    return cachegetUint8Memory;
}
```

wasm-bindgen has both a [safe](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#impl-From%3C%26%27a%20%5Bu8%5D%3E) and [unsafe](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#method.view) way of sending Rust slices to JS.

What is your use case?

**Comment by aminroosta** [comment]
The cached version will work for my use case, 
Thanks Pauan!
