### ISSUE TITLE
webidl-bindings table does not contain valid function indices

### ISSUE THREAD

**Issue by yurydelendik** [rustwasm/wasm-pack#711]
## 🐛 Bug description

The wasm-pack executes step wasm_opt after wasm_bindgen. The wasm_bindgen generates 'webidl-bindings' table with specific function ids in it. When wasm_opt is run, the function ids changed, e.g. some import or local functions are removed, thus breaking the webidl-bindings references.

#### 🤔 Expected Behavior

The 'webidl-bindings' table contains right indices.

#### 👟 Steps to reproduce

(Too deep a bug chain, depends on fixes at https://github.com/rust-lang/rust/issues/64187 and #654)

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.8.1
rustc version:

/cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yes right! For now you'll have to disable `wasm-opt` when using wasm interface types. @yurydelendik are you using a master-built version of `wasm-pack` or a prebuilt version? (I don't think the prebuilt versions run `wasm-pack` yet)

**Comment by yurydelendik** [comment]
> are you using a master-built version of wasm-pack or a prebuilt version?

I'm using the master since I need workarounds for the wasm32-wasi target.

**Comment by alexcrichton** [comment]
Ah ok, if you do:

```toml
# ... at the end of Cargo.toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

does that fix the issue?

**Comment by yurydelendik** [comment]
> does that fix the issue?

I commented the step in the [code](https://github.com/rustwasm/wasm-pack/blob/52e7539590d692ea6663dcef3f1b2bc45efd00b3/src/command/build.rs#L380), and it fixed the issue and allowed me to create an output wasm where wasmtime properly gets the export metadata. (I observe next issue during running of wasmtime, but I think it is unrealed)

**Comment by alexcrichton** [comment]
Ah ok, great!

I think in the long term we would want to automatically disable `wasm-opt` if interface types are enabled (at least until `wasm-opt` has interface types support), but until that happens are you ok closing this in the meantime?

**Comment by yurydelendik** [comment]
> are you ok closing this in the meantime?

yes. closing
