### ISSUE TITLE
--target nodejs won't load in Electron

### ISSUE THREAD

**Issue by swilcox3** [rustwasm/wasm-pack#713]
## 🐛 Bug description
I'm trying to load in a wasm-pack module into Electron 3.1.12, Node 10.15.3.  I compiled my module with wasm-pack build --release --target nodejs, but when I go to require the generated .js file in pkg, I get an error saying "Unable to import WebAssembly modules bigger than 4KB on main thread".  When I look inside the generated .js, it's just calling require on the .wasm.

#### 🤔 Expected Behavior
Either load the .wasm async by default for --target nodejs or provide documentation on loading the generated artifacts in pkg asynchronously.  Should I use a worker thread?  

#### 👟 Steps to reproduce
Try to load a non-trivial .wasm into Electron with require.  

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: latest (downloaded this morning)
rustc version: latest stable

**Comment by Pauan** [comment]
Electron is a browser environment, so you should be using `--target bundler` or `--target web`.

I highly recommend using `--target bundler` and [our Webpack template](https://github.com/rustwasm/rust-webpack-template).

Then you can set [`target: "electron-main"`](https://webpack.js.org/configuration/target/#string) in `webpack.config.js`.

**Comment by swilcox3** [comment]
Oh OK.  Shows what I know, I'm just a recovering C++ developer trying to slap a UI on my flashy new Rust crate.  I'll try that when I get back to my machine tonight.

**Comment by swilcox3** [comment]
All right, I've managed to royally confuse myself.  I've successfully bundled my wasm with Webpack, it's there in the dist folder now.  How do I use it locally, without starting a server or publishing to npm?  I just want to load it in by relative path.  Do I require the index.js in the dist folder?  But then what about that lovely .d.ts file in pkg I want to use in my TypeScript?  Can I still somehow get those types if I bundle with Webpack?  I know this isn't really an issue with wasm-pack, per se, it's just my inexperience with web technologies.  If you want to move this somewhere else that's fine with me.

**Comment by swilcox3** [comment]
So if I copy/paste the .d.ts file into the dist folder, TypeScript is happy, so that's easy enough.  So now I've got a script element like this: 
`<script type = 'text/javascript' src='../data-model-wasm/dist/index.js'></script>`
But that produces these errors:
Failed to load resource: net::ERR_FILE_NOT_FOUND
cd91465a6dcffad88b9b.module.wasm:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
TypeError: Failed to fetch

Am I pointing to the wrong thing?

**Comment by swilcox3** [comment]
Turns out that if I change the Webpack target back to node and then copy the artifacts in dist to the current working directory, all my imports succeed, but then when I try to call a function from it I get a TypeError saying it's not a function.  Is that because I need to wait for the module to finish loading?  Can I still use `import {stuff} from "../myModule"` syntax, or do I have to use `import("myModule").then()`?  Sorry for all the questions, I'm way out of my field here.

**Comment by Pauan** [comment]
> How do I use it locally, without starting a server or publishing to npm?

For running in Electron, you would set up your `package.json` like this:

```json
{
  "author": "You <you@example.com>",
  "name": "rust-webpack-template",
  "version": "0.1.0",
  "scripts": {
    "build": "rimraf dist pkg && webpack",
    "start": "rimraf dist pkg && webpack && electron dist",
    "test": "cargo test && wasm-pack test --headless"
  },
  "devDependencies": {
    "@wasm-tool/wasm-pack-plugin": "^0.4.2",
    "copy-webpack-plugin": "^5.0.3",
    "electron": "^6.0.9",
    "rimraf": "^2.6.3",
    "webpack": "^4.33.0",
    "webpack-cli": "^3.3.3",
    "webpack-dev-server": "^3.7.1"
  }
}
```

Then you can run `npm install` to install `electron`, and `npm start` to actually run the app.

The important part is the `electron dist`, which causes electron to load the files in the `dist` folder.

> Also, what about that lovely .d.ts file in pkg I want to use in my TypeScript? Can I still somehow get those types if I bundle with Webpack?

I'm not sure what you mean: those types are used exclusively by TypeScript, so if you're not writing TypeScript code then it won't have any effect.

On the other hand, if you are using TypeScript, then the types should work automatically, you just have to import the `.js` file from the `pkg` folder using a regular `import`. And in that case yes you need to use `ts-loader` in order to use TypeScript with Webpack.

> Turns out that if I change the Webpack target back to node and then copy the artifacts in dist to the current working directory, all my imports succeed

Yes, after trying it out myself, it seems `electron-main` doesn't work, but `node` does. It's very strange, since `electron-main` should work. But at least you can get it working with `target: "node"`

> when I try to call a function from it I get a TypeError saying it's not a function.

Can you please copy-paste the exact error that you're getting (including stack trace, if it exists)?

**Comment by swilcox3** [comment]
I'm trying to do something...ambitious.  I have an existing Typescript code base that I've got running in Electron, and two Rust crates.  One crate contains the types and high level interfaces, the other crate contains the heavyweight business logic.  The goal is to have two configurations for this product: a desktop version and a browser version.  The desktop version will be in Electron with both crates loaded into it directly.  I've already got a working version with [neon](https://github.com/neon-bindings/neon).  
The browser version will be just the Typescript with the lighter types Rust crate loaded in wasm and Webpack.  The business logic will be hosted on a Rust server using actix-web over websocket.  
I'm trying to keep the two configurations as close as possible, so I'm experimenting with loading the Rust types crate with wasm in both Electron and the browser.  Right now I have the wasm wrapper around my crate as a separate project from my Typescript and I'm trying to require it as another module.  
I'm calling import on the webpack-created index.js in dist, by relative path.  When I do that, that file seems to be assuming that the other files are in the current working directory, which they're not, so I've gotten around that by copying those build artifacts to the cwd.  My imports succeed.  I then try to call a function that I've imported from that .js file, which results in this error:

...\ui\app\operations\operations.js:21 Uncaught TypeError: index_1.getUserId is not a function
    at Object.<anonymous> (...\ui\app\operations\operations.js:21)
    at Object.<anonymous> (...\ui\app\operations\operations.js:283)
    at Module._compile (internal/modules/cjs/loader.js:711)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at index.html:27

Maybe this whole thing is dumb or overly complicated.  How should I change my setup?

**Comment by Pauan** [comment]
Can I see your code? I can't really help much otherwise, since your problem seems specific to your setup.

**Comment by swilcox3** [comment]
I'm going to try something else first, I think I'm starting to understand how all the pieces should fit.  I'll let you know how it goes.

**Comment by swilcox3** [comment]
OK, I've come full circle to directly importing the generated .js file in pkg, with the --target nodejs passed into wasm-pack.  I'm not using Webpack.   I'm importing the module like this:
`import("../../data-model-wasm/pkg/data_model_wasm").then(module => {
    user = module.getUserId();
})`
This then gives me this error:  
...\ui\data-model-wasm\pkg\data_model_wasm_bg.js:7 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at Object.<anonymous> (...\ui\data-model-wasm\pkg\data_model_wasm_bg.js:7)
    at Object.<anonymous> (...\ui\data-model-wasm\pkg\data_model_wasm_bg.js:11)
    at Module._compile (internal/modules/cjs/loader.js:711)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at Object.<anonymous> (...\ui\data-model-wasm\pkg\data_model_wasm.js:718)

Which brings me back to the original reason I filed this issue:  Shouldn't wasm-pack be generating JS that uses an asynchronous compiling/loading function?  I'm seeing WebAssembly.Module on line 7 of data_model_wasm_bg.js, which the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module) says should almost never be used, and WebAssembly.compileStreaming is preferable.

**Comment by swilcox3** [comment]
Yeah, I've hacked at that data_model_wasm.js file and come up this:
```const path = require('path').join(__dirname, 'data_model_wasm_bg.wasm');
const bytes = require('fs').readFileSync(path);
let imports = {};
imports['./data_model_wasm.js'] = require('./data_model_wasm.js');

module.exports.promise = WebAssembly.instantiate(bytes, imports).then(wasmObj => {
    wasm = wasmObj.instance.exports;
    wasm.__wbindgen_start();
    return wasm;
})```
I've put this at the bottom of the file, then I .then on the `.promise` export in my including Javascript and it works fine.  Obviously this is a hacky, weird way to do it because I have no clue what I'm doing in Javascript, but shouldn't wasm-pack have a feature for async instantiation?

**Comment by swilcox3** [comment]
OOOOOH I just understood that the [web target with no bundler](https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html) is probably what I need.  My earlier hack basically replicates what that target does, except nowhere near as robustly.  Now I just need to transpile that generated data_model_wasm.js into CommonJS and I should be good to go...

**Comment by Pauan** [comment]
> Shouldn't wasm-pack be generating JS that uses an asynchronous compiling/loading function?

Node does not have asynchronous WebAssembly loading. The `WebAssembly.compileStreaming` and `WebAssembly.instantiateStreaming` functions simply don't exist. Therefore, Node can only load WebAssembly synchronously.

That's okay, because Node has no problem with loading large WebAssembly files synchronously.

The problem is that Electron is *not* Node, it is using Chrome. And Chrome *does* have limits on loading WebAssembly synchronously, but it also provides asynchronous APIs.

That's why you have to use `--target bundler` or `--target web` (which use asynchronous loading).

> Now I just need to transpile that generated data_model_wasm.js into CommonJS and I should be good to go...

That's exactly what Webpack does. In fact, that's basically the entire purpose of Webpack.

That's why I said you need to use the [Rust Webpack template](https://github.com/rustwasm/rust-webpack-template), because that is simply the correct way to do things.

When I use the template, I can get an Electron app working fine, so the issue is with your specific setup. Could you please show me your code so I can see what the problem is?

**Comment by swilcox3** [comment]
OK, I added you as a collaborator on the repo.  The relevant import is in ui/operations/operations.ts, the wasm wrapper is in ui/data-model-wasm.

**Comment by swilcox3** [comment]
I've just did a bunch of work this, and I think I'm close.  Here's what I've done:  I'm now Webpacking everything that's on the electron renderer process into one bundle, using ts-loader and WasmPackPlugin.  I've almost got it working, but there's one hiccup: We have to have dynamic imports to load the WebAssembly.  That's fine, I've got that in my Typescript, but when my Typescript targets commonjs I get this error: 

ERROR in ./data-model-wasm/pkg/index_bg.wasm
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
* ./src/index.ts --> ./src/operations/operations.ts --> ./data-model-wasm/pkg/index.js --> ./data-model-wasm/pkg/index_bg.wasm

In my Typescript, I'm loading it like this:
```
export type WasmMod = typeof import("../../data-model-wasm/pkg/index");
export var dataModelWasm: WasmMod = null;

var loaded = import("../../data-model-wasm/pkg/index").then( mod => {
    dataModelWasm = mod;
    user = dataModelWasm.getUserId();
});
```
But my target is CommonJS, which doesn't have dynamic imports.  Ok fine, I changed my tsconfig to target "esnext" with the "node" module resolution.  That compiles, but now Electron syntax errors on the transpiled Javascript.  

Is there a way to manually tell Webpack to codesplit the chunks?  I think it'll work if I can get past Webpack's static analysis.

**Comment by swilcox3** [comment]
You know what, I don't think all this is worth it when I've already got neon working with Electron.  The setup is easier and the performance is better.  It just has more boilerplate and doesn't autogenerate types for me 😢.  I'll just use wasm-pack for my browser setup and maintain the two configurations, it'll be easier and simpler.
