### ISSUE TITLE
Remove icons from wasm-pack terminal command output

### ISSUE THREAD

**Issue by ivmazurenko** [rustwasm/wasm-pack#715]
##  Bug description
Icons in terminal in output of wasm-pack command

####  Expected Behavior
No icons in terminal.

**Comment by drager** [comment]
Hey @ibaryshnikov! Can you describe your issue a bit more?

**Comment by ibaryshnikov** [comment]
The question was addressed to @ivmazurenko I guess

**Comment by drager** [comment]
@ibaryshnikov Oh sorry! Yes, question for @ivmazurenko

**Comment by ibaryshnikov** [comment]
It looks like a duplicate of #632
