### ISSUE TITLE
missing new subcommand in 0.8.1

### ISSUE THREAD

**Issue by mswift42** [rustwasm/wasm-pack#722]
## 🐛 Bug description
I've installed wasm-pack in version 0.8.1 (Linux x86_64).
according to the [Readme](https://github.com/rustwasm/wasm-pack) it lists the available commands as 

- new: Generate a new RustWasm project using a template
- build: Generate an npm wasm pkg from a rustwasm crate
- test: Run browser tests
- pack and publish: Create a tarball of your rustwasm pkg and/or publish to a registry.

However, running 

`wasm-pack --help`

shows the following output:

```
SUBCOMMANDS:
    build      🏗️  build your npm package!
    help       Prints this message or the help of the given subcommand(s)
    login      👤  Add an npm registry user account! (aliases: adduser, add-user)
    pack       🍱  create a tar of your npm package but don't publish!
    publish    🎆  pack up your npm package and publish!
    test       👩‍🔬  test your wasm!
```

#### 🤔 Expected Behavior
Either wasm-pack should include a `new` command or its entry should be removed from the docs, and an "How-To setup a new project" entry be added.

#### 👟 Steps to reproduce
install wasm-pack 0.8.1

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.8.1
rustc version: 1.40.0-nightly

**Comment by drager** [comment]
Hey @mswift42, thanks for the report!

The readme is for the latest master which has not been released yet (should be released in 0.9.0). The sub-commands in master reflects what the readme says. If you want the `new` command at the moment, then you could clone this repo and build `wasm-pack` yourself.

Also, our published docs for the latest release (0.8.1) can be found [here](https://rustwasm.github.io/docs/wasm-pack/), which reflects that release commands. (i.e. no `new` command).

**Comment by mswift42** [comment]
@drager 
O.K. But how do I generate a new rustwasm project now ?

**Comment by drager** [comment]
@mswift42 You can do it by using [cargo-generate](https://github.com/ashleygwilliams/cargo-generate). Instructions can be found in the [tutorial](https://rustwasm.github.io/docs/wasm-pack/tutorials/npm-browser-packages/getting-started.html)

**Comment by mswift42** [comment]
Thanks, I'm closing this now.

**Comment by shijunti19** [comment]
https://rustwasm.github.io/wasm-pack/book/commands/new.html
