### ISSUE TITLE
RuntimeError: unreachable executed

### ISSUE THREAD

**Issue by mikedilger** [rustwasm/wasm-pack#724]
## 🐛 Bug description
I'm using wasm-pack to build a wasm that generates an SVG on the fly.  Code compiles with no error. The resulting wasm worked fine up until I added a line (and included chrono), and now the browser gives me "RuntimeError: unreachable executed" and I can inspect into the wasm to an unreachable statement.

#### 🤔 Expected Behavior
Shouldn't be generating a wasm that can hit an unreachable statement.

#### 👟 Steps to reproduce
See https://github.com/mikedilger/circular_calendar which I have just pushed for this bug report.

#### 🌍 Your environment
wasm-pack version: 0.8.1
rustc version: 1.38.0

**Comment by mikedilger** [comment]
Now that I think of it, it's probably related to `chrono` and time.

**Comment by Pauan** [comment]
@mikedilger You should be using [`console_error_panic_hook`](https://crates.io/crates/console_error_panic_hook), which will dramatically improve the error messages.

For `chrono` you need to enable the `wasmbind` feature.

**Comment by mikedilger** [comment]
Oh man is that valuable information!  Thanks.

**Comment by Songkeys** [comment]
I'm trying to use `SystemTime::now()` and gettuing the same error. Do I have to use `chrono` for this?

**Comment by Pauan** [comment]
@Songkeys There is currently no way to use `SystemTime` with `wasm32-unknown-unknown`.

However you can use [`js_sys::Date::now()`](https://docs.rs/js-sys/0.3.47/js_sys/struct.Date.html#method.now) which calls the JavaScript `Date.now()` and returns an `f64`.

Or you can use [`js_sys::Date::new_0()`](https://docs.rs/js-sys/0.3.47/js_sys/struct.Date.html#method.new_0) if you want a JavaScript `Date` object instead.

**Comment by sdykae** [comment]
For the record, was doing network requests with https://github.com/seanmonstar/reqwest in rust and after enabling https://crates.io/crates/console_error_panic_hook compiled catches 
![image](https://user-images.githubusercontent.com/50224521/129286588-d396553f-8a93-44a3-a061-d25b43d0305a.png)
```
panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: "JsValue(ReferenceError: Headers is not defined\nReferenceError: Headers is not defined\n    at /home/iuslkae/lib-test/pkg/lib_test.js:270:15\n    at handleError (/home/iuslkae/lib-test/pkg/lib_test.js:217:18)\n    at module.exports.__wbg_new_cf4002932f67522d (/home/iuslkae/lib-test/pkg/lib_test.js:269:65)\n    at null.<anonymous> (wasm://wasm/001b906e:1:200279)\n    at null.<anonymous> (wasm://wasm/001b906e:1:65901)\n    at null.<anonymous> (wasm://wasm/001b906e:1:155650)\n    at null.<anonymous> (wasm://wasm/001b906e:1:139731)\n    at null.<anonymous> (wasm://wasm/001b906e:1:177221)\n    at null.<anonymous> (wasm://wasm/001b906e:1:144986)\n    at null.<anonymous> (wasm://wasm/001b906e:1:184052))" }', src/lib.rs:26:6
```
Apparently it required this way and worked fine.
![image](https://user-images.githubusercontent.com/50224521/129286637-675deb57-2d74-469e-9dc5-873eb97a4dba.png)
```
import { default as fetch, Headers, Request, Response } from 'node-fetch';
// declare global;
// @ts-ignore
global.fetch = fetch;
// @ts-ignore
global.Headers = Headers;
// @ts-ignore
global.Request = Request;
// @ts-ignore
global.Response = Response;
greet().then(console.log);
```


Patch node-fetch on nodejs to get my lib work.
