### ISSUE TITLE
wasm-pack does not seem to properly install. And produces OS Error 5 Access denied

### ISSUE THREAD

**Issue by niilz** [rustwasm/wasm-pack#727]
## 🐛 Bug description
1. wasm-pack does not show any of the described logging after installation (installation seems to go a big to quick: only milliseconds)
2. wasm-pack shows a version number (after typing wasm-pack -version) but does not work with any other command.
Instead I always get the message:
Error: Access Denied (os error 5)

#### 🤔 Expected Behavior
It should install and afterward show instruction with emojis on how to use it.
It should be usable with "wasm-pack new pojectname" or "wasm-pack build"

#### 👟 Steps to reproduce
I've downloaded the wasm-pack-init.exe from the website.
Installed it which immediately delivered:
"sucessfully installed. press enter to close the window"
No emojis or instructions

#### 🌍 Your environment
Windows 10 (64bit machine)
wasm-pack version: 0.8.1
rustc version: 1.38.0

**Comment by niilz** [comment]
The Problem seemed to have been related to a wrongly setted OS-path-variable for CARGO.
I close this issue.

**Comment by pmkroeker** [comment]
@niilz I'm getting a similar error. Could you describe what exactly was wrong and how you fixed it?

**Comment by niilz** [comment]
@pmkroeker I don't really recall what I did. But from the looks of it, I most likely did not have the path to cargo in my environment path-variable-list. So currently I'm on a mac and cargo's binaries are under `~/.cargo/bin`, which is the default path. So this is what I added to my environment-path-variable list. Under windows the default is probably `%HOME%\.cargo\bin`.

**Comment by pmkroeker** [comment]
@niilz Thanks! This seems to have resolved it for me as well.

**Comment by sarsamurmu** [comment]
Reference for others who are facing the same error, try to exclude your project's directory from the antivirus' scanner/real-time scanner. You can also check if it is caused by your antivirus - pause the antivirus for a limited time and run the wasm-pack command. For me, it was the antivirus.
