### ISSUE TITLE
Allow skipping `.gitignore` generation

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-pack#728]
## 💡 Feature description

Since implementing self-`.gitignore` generation in https://github.com/rustwasm/wasm-pack/issues/473, I've come across few codebases that prefer not to publish npm artifacts elsewhere nor integrate Rust build into their build process, but keep any artifacts in the Git repo.

I suggest adding `--no-gitignore` option for such usecases.

## Alternative

Since in such cases module is not intended to be published anywhere, another alternative could be to implement this (omit `.gitignore`) as part of `--no-pack` implementation proposed here https://github.com/rustwasm/wasm-pack/issues/691.

cc @ashleygwilliams

**Comment by RReverser** [comment]
Actually... I realised that this is easily worked around by using one-off `git add --force pkg/...` and it's even better because you can selectively include only files you need in the repo (e.g. omit `package.json` or `.d.ts`).

**Comment by David-OConnor** [comment]
I still think this would be nice to have; came here to post the same thing.

**Comment by olanod** [comment]
Same, I'd like to generate only the wasm and js and skip all the extra stuff since I'm not using npm

**Comment by johnnybenson** [comment]
`--force` is kinda icky, `.gitignore` lives in a repository to codify these things for a reason. Skipping the generation of this file entirely scales better for multiple collaborators and teams because the appropriate information exists at rest.

**Comment by kixelated** [comment]
I ran into this issue when trying to publish a wrapper around the generated wasm-pack output.

`src/index.ts` imports `../pkg`. I want to package both `src` and `pkg` into an npm package and publish it. However, `bun` sees the `.gitignore` file in `pkg` and skips adding it to the artifact, despite `files: [ "pkg", "src" ]`. 

```
$ bun pm pack --verbose
ignore [.gitignore:*] pkg/moq_web.d.ts
ignore [.gitignore:*] pkg/README.md
ignore [.gitignore:*] pkg/.gitignore
ignore [.gitignore:*] pkg/moq_web.js
ignore [.gitignore:*] pkg/moq_web_bg.js
ignore [.gitignore:*] pkg/moq_web_bg.wasm
```
I accidentally published a few broken versions, oops. My current work-around is to `rm pkg/.gitignore` after running wasm-pack.
