### ISSUE TITLE
wasm-pack new is documented but not working

### ISSUE THREAD

**Issue by PSeitz** [rustwasm/wasm-pack#742]
## 🐛 Bug description
`wasm-pack new`
error: Found argument 'new' which wasn't expected, or isn't valid in this context

#### 🤔 Expected Behavior
This should work as of the documentation here: https://github.com/rustwasm/wasm-pack

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.8.1
rustc version:  1.39.0-nightly

The install link in the github readme should match the documentation in the readme.

**Comment by logankeenan** [comment]
This has been discussed in #722

**Comment by PSeitz** [comment]
The issue is that the installation instructions on the github page don't reflect the documentation on the github page

**Comment by drager** [comment]
@PSeitz Yes, but the `new` command is only available in `master` and should be released in `0.9.0`.

**Comment by ashleygwilliams** [comment]
this release has happened so new is now released. closing.
