### ISSUE TITLE
wasm-pack build fail

### ISSUE THREAD

**Issue by Taoja** [rustwasm/wasm-pack#758]
`[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling imagequant-sys v2.12.5
   Compiling wasm-bindgen-backend v0.2.55
error: failed to run custom build command for `imagequant-sys v2.12.5`

Caused by:
  process didn't exit successfully: `/Users/huangwutao/work/wx/rust/compress/target/release/build/imagequant-sys-34adba6d4e6d8a33/build-script-build` (exit code: 1)
--- stdout
OPT_LEVEL = Some("s")
TARGET = Some("wasm32-unknown-unknown")
HOST = Some("x86_64-apple-darwin")
CC_wasm32-unknown-unknown = None
CC_wasm32_unknown_unknown = None
TARGET_CC = None
CC = None
CFLAGS_wasm32-unknown-unknown = None
CFLAGS_wasm32_unknown_unknown = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
cargo:include=/Users/huangwutao/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/imagequant-sys-2.12.5
running: "clang" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-std=c99" "-DNDEBUG=1" "-o" "/Users/huangwutao/work/wx/rust/compress/target/wasm32-unknown-unknown/release/build/imagequant-sys-bc036356db92ca34/out/libimagequant.o" "-c" "libimagequant.c"
cargo:warning=libimagequant.c:9:10: fatal error: 'stdio.h' file not found
cargo:warning=#include <stdio.h>
cargo:warning=         ^~~~~~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr

error occurred: Command "clang" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-unknown-unknown" "-std=c99" "-DNDEBUG=1" "-o" "/Users/huangwutao/work/wx/rust/compress/target/wasm32-unknown-unknown/release/build/imagequant-sys-bc036356db92ca34/out/libimagequant.o" "-c" "libimagequant.c" with args "clang" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: build failed
`

how to install llvm or clang with WASM support?

**Comment by csmoe** [comment]
`/usr/include` missing is a common issue on macos.
```bash
xcode-select --install
```
might help, if not, search with `fatal error: 'stdio.h' file not found macos`, you should find some solutions.

**Comment by Taoja** [comment]
@csmoe  thx. i will try first

**Comment by Taoja** [comment]
@csmoe thx for ur help, i find the way to solution it.
https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave
