### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by expenses** [rustwasm/wasm-pack#768]
Hi, the version of `wasm-pack` on crates.io hasn't been updated since April 2019. There have been a decent about of changes since then, especially the renaming of the `browser` build target to `bundler`. This makes reading the documentation confusing, and I suggest a new `0.8.2` version be published.

**Comment by drager** [comment]
Hey @expenses, there is a `0.9.0` in the making, that hopefully will be released soon! See for example #760. In the meantime the docs for `0.8.1` can be found here: https://rustwasm.github.io/docs/wasm-pack/

**Comment by ashleygwilliams** [comment]
i really hope to get the release out this week. @expenses you are very correct and i'm trying my best!

**Comment by expenses** [comment]
Oh ok, great!!

**Comment by MaxBittker** [comment]
woohoo! thanks wasm-packers <3 (and no rush, i'm sure this isn't the only thing you are thinking about this week!)

that being said, here's a demo made with wasm-pack to celebrate! https://maxbittker.github.io/wasm-noise-example/index.html

**Comment by ashleygwilliams** [comment]
this happened :) twice even. hoping to get back into a rhythm of doing this on a more regular basis. really appreciate the patience and kind words in this thread! ya'll are awesome <3<3
