### ISSUE TITLE
Please support webbundle

### ISSUE THREAD

**Issue by wu-jun-jie** [rustwasm/wasm-pack#777]
## 💡 web bundle

webbundle is a new tool for native web bundle.

[webbundle crate](https://github.com/google/webbundle) 

[w3c specific](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html)

**Comment by Pauan** [comment]
WebBundle is extremely experimental (the draft was created just this month), it is not standardized, it is not complete, and it isn't implemented by any browser.

We will probably implement it when it is stabilized, but not right now.

If you just want to play around with it, you can use [`go/bundle`](https://github.com/WICG/webpackage/tree/master/go/bundle) on your own projects, with the understanding that it will only work on your local machine.

**Comment by ashleygwilliams** [comment]
since we will not be implementing this any time soon, i'm going to close. i agree with @Pauan - once this feature is standardized i would be happy to add support in wasm-pack!
