### ISSUE TITLE
wasm-opt exits with signal 6

### ISSUE THREAD

**Issue by xldenis** [rustwasm/wasm-pack#782]
Related: #696

## 🐛 Bug description
Running `wasm-pack build` in in a Github action after running the installer fails 

```
Error: failed to execute `wasm-opt`: exited with signal: 6
  full command: "/home/runner/.cache/.wasm-pack/wasm-opt-37dc6b0d9960f622/wasm-opt" "/home/runner/work/crdocs/crdocs/frontend/pkg/crdocs_bg.wasm" "-o" "/home/runner/work/crdocs/crdocs/frontend/pkg/crdocs_bg.wasm-opt.wasm" "-O"
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

To see a failed build: https://github.com/xldenis/crdocs/runs/421370544?check_suite_focus=true

#### 🤔 Expected Behavior

`wasm-opt` should run successfully.

#### 👟 Steps to reproduce

Rerunning CI on that specific commit should cause a failure reliably. 

#### 🌍 Your environment

Include the relevant details of your environment.
wasm-pack version: 0.9.0

**Comment by tobni** [comment]
I have experienced the same error signal, but locally. I suspect this to be related to cargo workspaces, as my setup use this feature as well.

**Comment by BradyKoehler** [comment]
I just ran into the same problem. Turns out all I needed to do was install wasm-opt using:
`npm install wasm-opt -g`

Source: https://github.com/MrRefactoring/wasm-opt

**Comment by otaviopace** [comment]
We are experiencing the same issue on both Ubuntu and CircleCI with Rust Docker image 😞

**Comment by ashleygwilliams** [comment]
really sorry that folks are running into  this- i'll look into it today! if you want- you can pin wasm-pack at 0.8.1 by using the npm installer.

alternatively, you can disable wasm-opt temporarily by setting `wasm-opt = false` in your cargo.toml, while i figure out what's happening

**Comment by jshrake** [comment]
I can reproduce this and #781 in `Ubuntu 18.04` (running in Windows Subsystem for Linux):

```
Error: failed to execute `wasm-opt`: exited with signal: 6
  full command: "/home/justin/.cache/.wasm-pack/wasm-opt-37dc6b0d9960f622/wasm-opt" "lib/pkg/landlord_bg.wasm" "-o" "lib/pkg/landlord_bg.wasm-opt.wasm" "-O"
```

Running the command manually, I get an `Aborted (core dumped)` or `Segmentation fault (core dumped)`. I assume one corresponds to this issue, and one to #781, but I'm not sure which -- both reproduce randomly with `wasm-pack build` and no other changes. Running without the the `-O` flag seems to resolve both issues and the program successfully completes and writes out `lib/pkg/landlord_bg.wasm-opt.wasm`.

**Comment by xldenis** [comment]
I just changed my installation command in CI to `cargo install wasm-pack --version 0.8.1` since I didn't want to also install npm.

**Comment by Michael-F-Bryan** [comment]
I'm also encountering this on my Ubuntu 19.10 machine. The segmentation fault happens every time using the `wasm-opt` that comes with `wasm-pack`.

<details>
<summary>Version Numbers and Environment</summary>

```console
$ rustc --version --verbose
rustc 1.42.0-nightly (cd1ef390e 2020-01-31)
binary: rustc
commit-hash: cd1ef390e731ed77b90b11b1f77e2c5ca641b261
commit-date: 2020-01-31
host: x86_64-unknown-linux-gnu
release: 1.42.0-nightly
LLVM version: 9.0
$ cargo --version --verbose
cargo 1.42.0-nightly (9d32b7b01 2020-01-26)
release: 1.42.0
commit-hash: 9d32b7b01409024b165545c568b1525d86e2b7cb
commit-date: 2020-01-26
$ wasm-pack --version
wasm-pack 0.9.0
```

It looks like `wasm-opt` doesn't have a `--version` flag, so I'm not sure which version is on my machine.
</details>

I tried getting a backtrace using `gdb` but the binary is stripped and statically linked, so the backtrace was kinda useless.

I also tried compiling `wasm-opt` from source with optimisations and debug info, but it didn't want to segfault :disappointed:

<details>
<summary>Installing from source</summary>

```console
$ cd /tmp
$ git clone git@github.com:WebAssembly/binaryen.git
$ git rev-parse HEAD
33f92aa06fe5de7bcf9f6b7fe2e74ba5e8e1e782
$ mkdir build && cd build
$ cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ ninja
$ ls bin
asm2wasm  wasm-as  wasm-ctor-eval  wasm-dis  wasm-emscripten-finalize  wasm-metadce  wasm-opt  wasm-reduce  wasm-shell  wasm2js
$ cd ~/Documents/arcs
$ /tmp/binaryen/build/bin/wasm-opt demo/pkg/arcs_demo_bg.wasm -o demo/pkg/arcs_demo_bg.wasm-opt.wasm -O
$ echo $?
0
```
</details>

I'm going to keep using this binary locally for now. If it segfaults again I'll update this comment with a backtrace and more info.

**Comment by artemv** [comment]
> Turns out all I needed to do was install wasm-opt using npm install wasm-opt -g
I can confirm that it did help me too (Ubuntu at CircleCI, wasm-pack 0.9.0, rust 1.41.0)

**Comment by alexlapa** [comment]
Using wasm-opt 90 instead of 78 fixed this issue for me (Ubuntu 19.04). Changed version [here](https://github.com/rustwasm/wasm-pack/blob/master/src/wasm_opt.rs#L87).

**Comment by ashleygwilliams** [comment]
i'm going to cut a point release today that ups the version of wasm-opt! i'll mention on this issue as soon as i do

**Comment by xldenis** [comment]
thanks for the prompt response!

**Comment by otaviopace** [comment]
Thanks for fixing the issue guys ❤️
