### ISSUE TITLE
Making webpack much faster, displaying progress bars to users and just making wasm-pack more awesome.

### ISSUE THREAD

**Issue by wdanilo** [rustwasm/wasm-pack#790]
## 😱Problem Description
Hi! I'm using wasm-pack to generate `app.js` (glue code) and `app_bg.wasm` (WASM binary). I've got 2 problems which are pretty often reported here. **The interesting thing is, however, that I also have solutions to them**:

1. Webpack is slow on big WASM files. After changing code in Rust, the Rust compiler needs 2 seconds to generate new WASM, while webpack needs over 10 seconds to pack it. **The solution presented below removes this 10 second overhead completely.**
2. As my Rust code uses 3rd party emscripten compiled code, the `app.js` with its import is pretty heavy (1MB). I want my users to see some kind of progress bar when loading the things, however, currently, everything is structured this way it is not possible easily.

After making the proposed changes below, the time needed between hitting `ctrl+s` and seeing results in browser dropped from 15s to around 2s. Moreover, everything is loaded with a nice progress-bars for the end-user :)

## 🤓Solution to the problem

1. We can remove the overhead from Webpack by just ... not passing WASM to it. Instead, we can just `fetch` the WASM from server and use `WebAssembly.instantiateStreaming` to compile it. No need to ever pass it trough webpack.
2. Currently, `app.js` gathers all imports from Rust code in a single place and also creates fancy `fetch` mechanisms to initialize WASM module. In order to remove the overhead and load upfront as small amount of bytes as possible, this file (bundled with dependencies) should also be fetched from server.

## 🤯What is wrong with the currently generated glue code

1. The generated glue code `app.js` (or whatever your Rust project is named) contains a line `module = import.meta.url.replace(/\.js$/, '_bg.wasm');`. In order not to mangle the WASM binary with webpack, this line has to be removed. So either we should make it optionally generated with some flag (simple solution), or just extract it to a separate file (see point 2).
2. The next place where `module` variable from point 1 is used is the place of initialization the WASM module - line `if ((typeof URL === 'function' && module instanceof URL) ...`. The initialization is done in the function `init` which first gathers all imports and then initializates the WASM module. This prevents from custom module initialization (and getting information about progress from `fetch`).

## 😁Required changes

The good news is that everything can be fixed really, really easily - by extracting all the code which prepares imports to a separate file, e.g. `app.imports.js`.

So, after this change, we will have two generated files:

1. `app.imports.js` which will contain `imports` function which will result in all imports needed by the WASM binary. This file can be used if you want to customize your WASM module loading strategy (as we do). This file can be compiled by webpack separately and loaded by using `fetch` next to another `fetch` of WASM binary.
2. `app.js` which will use `app.imports.js` to get the imports and will also initialize the WASM module accordingly.

## 💪How to contribute?
I can contribute! But please approve these changes and tell me where to look in order to make them :)

**Comment by Pauan** [comment]
> We can remove the overhead from Webpack by just ... not passing WASM to it.

By default wasm-pack uses `--target bundler`, which is designed for Webpack.

However, you can use `--target web`, which bypasses Webpack and loads the `.wasm` with `instantiateStreaming`. So, you can already do this!

> In order to remove the overhead and load upfront as small amount of bytes as possible, this file (bundled with dependencies) should also be fetched from server.

You can already do this by using dynamic `import`, like this:

```js
async function loadWasm() {
    let wasm = await import("./path/to/pkg/foo.js");

    await wasm("./path/to/pkg/foo_bg.wasm");

    // Use wasm functions...
}
```

> The generated glue code app.js (or whatever your Rust project is named) contains a line `module = import.meta.url.replace(/\.js$/, '_bg.wasm');`.

Yes, we've had issues with using `import.meta.url` in Webpack. Webpack will [eventually support it](https://github.com/webpack/webpack/issues/6719), but for now it's rather tricky. I think it's reasonable to have a flag to disable it, but that change has to be made in wasm-bindgen.

In the meantime, I've created a [Rollup plugin](https://github.com/Pauan/rollup-plugin-rust) which fixes all of the issues you found. It also improves a bunch of other things from the Webpack plugin. My compile times and bundle size went down quite a bit by using Rollup.

> The good news is that everything can be fixed really, really easily - by extracting all the code which prepares imports to a separate file, e.g. app.imports.js.

This requires changes in [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen), wasm-pack can't make those changes. So could you please file an issue there instead?

**Comment by wdanilo** [comment]
@Pauan thanks for reply, I'll file issue there instead. 

Regarding the first point, however, I'm already using `--raget web`. The issues mentioned by me are connected to this mode exactly. Unfortunately, I'm afraid the solutions provided by you (dynamic import) does not allow me to display a nice download progress bar to the user, do they? Moreover, as I described in my issue, the generated file `app.js` (not `app_bg.wasm`) has imports which are really big and I want to download it with a progress bar as well. I think your solution does not cover these points, am I correct?

**Comment by Pauan** [comment]
> Unfortunately, I'm afraid the solutions provided by you (dynamic import) does not allow me to display a nice download progress bar to the user, do they?

I don't think there's any way of retrieving the progress for `import` or `fetch`. So you would have to ask the WHATWG to add in that feature to `fetch`, and [TC39](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) to add in that feature to `import`.

It seems there is already an [issue filed](https://github.com/whatwg/fetch/issues/607) about progress in `fetch`. I [don't see any proposals](https://github.com/tc39/proposals/) for progress in `import`.

You can however display a loading screen, it just won't show a % of progress.
