### ISSUE TITLE
updates to reqwest 0.10

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/wasm-pack#798]
per a comment on the discord  from @ibaryshnikov we should see some perf improvements!

<img width="661" alt="Screen Shot 2020-02-21 at 1 45 45 PM" src="https://user-images.githubusercontent.com/1163554/75066457-7c068200-54b0-11ea-9a23-9ab47f598de5.png">

**Comment by ashleygwilliams** [comment]
blocked by #801

**Comment by saks** [comment]
FYI: it looks like wasm-pack uses [unsupported crate net2](https://rustsec.org/advisories/RUSTSEC-2020-0016) through an old version of reqwest (0.9.24)
```
net2 0.2.37
├── miow 0.2.2
│   └── mio 0.6.23
│       ├── tokio-tcp 0.1.4
│       │   ├── tokio 0.1.22
│       │   │   └── hyper 0.12.36
│       │   │       ├── reqwest 0.9.24
│       │   │       └── hyper-tls 0.3.2
│       │   │           └── reqwest 0.9.24
```
Is there anything I can help with to facilitate migration to a more recent version of reqwest?
