### ISSUE TITLE
CompileError: WebAssembly.Module(): return count of 2 exceeds internal limit of 1 @+20

### ISSUE THREAD

**Issue by hasangenc0** [rustwasm/wasm-pack#815]
## 🐛 Bug description
I'm using rust's ` std::process::Command` to run some git commands. But running wasm from node gives me this error: 
````
UnhandledPromiseRejectionWarning: CompileError: WebAssembly.Module(): return count of 2 exceeds internal limit of 1 @+20
````
Probably it is not a bug. It seems like there is a limit to something but I can't understand it.

#### 🤔 Expected Behavior
I'm expecting to use `Command`.

#### 👟 Steps to reproduce
My lib.rs:
````
use wasm_bindgen::prelude::*;
use std::process::Command;

#[wasm_bindgen]
pub fn four() -> String {
    let output = Command::new("git").arg("log").arg("--oneline").output();
    match output {
        Ok(o) =>
            if o.status.success() {
                String::from_utf8(o.stdout).unwrap()
            } else {
                panic!("{:?}" , o.stderr)
            }
        ,
        Err(e) => panic!("{:?}", e),
    }
}
````

My lib.js:
````
const fs = require('fs').promises;
const resolve = require('path').resolve;

async function readWasmFile(dir) {
  const path = resolve(__dirname, dir);
  return await fs.readFile(path);
}

async function createWebAssembly(buffer) {
  const module = new WebAssembly.Module(buffer);
  return WebAssembly.instantiate(module);
}

async function instantiate(dir) {
  const buffer = await readWasmFile(dir);
  const result = await createWebAssembly(new Uint8Array(buffer));
  return result.instance.exports;
}

async function run() {
  const wasm = await instantiate('./my_lib.wasm');
}

run();
````

How I built rust to wasm:
`export WASM_INTERFACE_TYPES=1 && wasm-pack build -d src/wasm --target nodejs`

How I run javascript file:
`node --experimental-wasm-anyref src/lib.js`

#### 🌍 Your environment
MacOs 10.14
wasm-pack version: 0.6.0
rustc version: 1.40.0

**Comment by Pauan** [comment]
You cannot use OS APIs (like `std::process::Command` or `std::fs`) with Wasm. Instead you will need to use the Node APIs, like [`child_process`](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html) or [`fs`](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html).

Also, your way of initializing the Wasm code is incorrect, you need to do this instead:

```js
const wasm = require('./my_lib.js');

wasm.four();
```

The JS glue code which is created by wasm-pack is *necessary*, it will automatically load the `.wasm` file, so you must load the JS glue code, not the `.wasm` file.

**Comment by hasangenc0** [comment]
Hi @Pauan,
Thanks for your answer, Actually it is a basic JS glue code. I can initialize wasm in this way, it works well. But I didn't know that cannot use OS APIs.

**Comment by Pauan** [comment]
> I can initialize wasm in this way, it works well. 

Except that won't work, because you must pass in shim functions into the `.wasm` file, but your code isn't doing that. You *need* the JS glue code, because it generates shim functions and passes them into the `.wasm` file. Those shim functions are *mandatory*, which is why wasm-pack always generates *both* a `.js` file and `.wasm` file, the `.js` file is not optional.

**Comment by hasangenc0** [comment]
Hi @Pauan, can you show me that in this code? `(my_lib.js)`

```js
let wasm;
const { TextDecoder } = require(String.raw`util`);

let cachegetInt32Memory0 = null;
function getInt32Memory0() {
    if (cachegetInt32Memory0 === null || cachegetInt32Memory0.buffer !== wasm.memory.buffer) {
        cachegetInt32Memory0 = new Int32Array(wasm.memory.buffer);
    }
    return cachegetInt32Memory0;
}

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });

cachedTextDecoder.decode();

let cachegetUint8Memory0 = null;
function getUint8Memory0() {
    if (cachegetUint8Memory0 === null || cachegetUint8Memory0.buffer !== wasm.memory.buffer) {
        cachegetUint8Memory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachegetUint8Memory0;
}

function getStringFromWasm0(ptr, len) {
    return cachedTextDecoder.decode(getUint8Memory0().subarray(ptr, ptr + len));
}
/**
* @returns {string}
*/
module.exports.four = function() {
    try {
        wasm.four(8);
        var r0 = getInt32Memory0()[8 / 4 + 0];
        var r1 = getInt32Memory0()[8 / 4 + 1];
        return getStringFromWasm0(r0, r1);
    } finally {
        wasm.__wbindgen_free(r0, r1);
    }
};

wasm = require('./my_lib_bg');
```

**Comment by Pauan** [comment]
@hasangenc0 I'm sorry, I don't understand your question.

That code is the JS glue code which I had mentioned earlier. In order to load it, you would do this:

```js
const wasm = require('./my_lib.js');

console.log(wasm.four());
```

That is all the code that you need, you do not need to load the `.wasm` file.
