### ISSUE TITLE
Ability to package custom JS in the glue code

### ISSUE THREAD

**Issue by virtualgraham** [rustwasm/wasm-pack#825]
## 💡 Feature description
It would be nice if there was an option to append some custom JS code to the end of the glue code during the build process. I need to add some functions to glue code class prototypes. In my case I am adding functions that can take variable number of arguments and arguments with mixed types, then pass them to the appropriately typed method. 

#### 💻 Basic example
Here is an example of some code I would like to be able to append:
```javascript

    Foo.prototype.bar = function() {
        return this._bar(Array.prototype.slice.call(arguments));
    }

    function is_foo(args) {
        args.length >= 1 && 
        (((args[0] || {}).prototype || {}).constructor || {}).name == "Foo"
    }

    Foo.prototype.baz = function() {
        if (is_foo(arguments)) {
            return this._in_foo(arguments[0])
        } else {
            return this._in_value(arguments[0])
        }
    }
```

**Comment by virtualgraham** [comment]
Solved by wrapping the module without too much difficulty

**Comment by Ciantic** [comment]
How did you wrap the custom glue JS?

(I need to access `import.meta.url` from the WASM module, but since the glue code doesn't pass it, it's not available.)
