### ISSUE TITLE
`cargo-generate` installed binary not detected correctly when running `wasm-pack new`

### ISSUE THREAD

**Issue by ahoetker** [rustwasm/wasm-pack#828]
**note**: This is caused by a typo, I am adding this issue so that I can reference it in the PR to fix the typo.

## 🐛 Bug description
When running `wasm-pack new`, the currently-installed binary for `cargo-generate` is not detected due to a typo.

#### 🤔 Expected Behavior
If `cargo-generate` is already installed in `$root/bin`, it should be detected and renamed at `$root` during install.

#### 👟 Steps to reproduce
Install `cargo-generate` at `$root/bin`, and then run `wasm-pack new`.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.44.0-nightly

**Comment by 0xd4d** [comment]
You should send your PR to this repo. You created a PR in your fork.

**Comment by ahoetker** [comment]
> You should send your PR to this repo. You created a PR in your fork.

I... wow, thank you! Correct PR is forthcoming 😅

**Comment by richiksc** [comment]
@ahoetker Can you submit the same change to this repo, rust-wasm/wasm-pack? Thanks!
