### ISSUE TITLE
wasm32 target not install on Ubuntu 20LTS

### ISSUE THREAD

**Issue by mbwhite** [rustwasm/wasm-pack#834]
## 🐛 Bug description
Using the standard curl command to install wasm-pack - primarily to get the target - it appears not to add it on Ubuntu 20LTS

#### 🤔 Expected Behavior
Should have installed

#### 👟 Steps to reproduce

```
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
rust target list 
```
List does not include the wasm32-unknown-unknown target

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version:0.9.1
rustc version: rustc 1.43.0 (4fb7144ed 2020-04-20)

**Comment by cdvv7788** [comment]
I am not sure if this is an issue.
I installed it normally, and then ran `wasm-pack build`
![image](https://user-images.githubusercontent.com/5531776/81757576-f2e66200-9484-11ea-94b1-22d5a62766a3.png)
The build process installs the target.
After building it, running `rustup target list` shows that `wasm32-unknown-unknown` is installed:
![image](https://user-images.githubusercontent.com/5531776/81757926-0219df80-9486-11ea-978a-db2d94f2c7af.png)

I tested in ubuntu18 and ubuntu20, the behaviour is the same. I don't think this is a bug.

**Comment by cdvv7788** [comment]
@mbwhite maybe what you are interested in is https://github.com/rust-lang/rustup#cross-compilation ? I think you don't need wasm-pack if you only need to download the target.

**Comment by mbwhite** [comment]
@cdvv7788 yes that's exactly what I was (am!) interested in.  

I thought that when I'd previously installed wasm-pack on Ubuntu 18 it had installed the target for me. https://rustwasm.github.io/docs/wasm-pack/prerequisites/non-rustup-setups.html suggest that it does - but may I wasn't using rustup

**Comment by Pauan** [comment]
@mbwhite If you're not planning to use wasm-pack, you should just do `rustup target add wasm32-unknown-unknown` (which is what wasm-pack does). Wasm-pack is only needed if you want to communicate between Rust and JS.
