### ISSUE TITLE
Use of `wasm-bindgen` from git/path/registry may fail

### ISSUE THREAD

**Issue by hajifkd** [rustwasm/wasm-pack#852]
If the `wasm-bindgen` is not globally installed, these codes

https://github.com/rustwasm/wasm-pack/blob/203a5f270fde46ec0b44b01709f01c1584ded961/src/command/build.rs#L351-L352

https://github.com/rustwasm/wasm-pack/blob/203a5f270fde46ec0b44b01709f01c1584ded961/src/install/mod.rs#L260-L266

try to install it based on the Cargo.lock. (This may happen other commands, but in practice, only `wasm-bindgen` causes the problem.)

However, if the project specifies the version using the git, path, or registry section, this may fail, because the lock file does not reflect it. The workaround is to install `wasm-bindgen-cli` globally.

Well, I understand this is an extremely rare problem, but I found it when I was working on https://github.com/rustwasm/wasm-bindgen/pull/2105 and I think at least this should be noted somewhere.

**Comment by ctaggart** [comment]
It would be nice if the git version of wasm-bindgen is specified, then the matching version of wasm-bindgen-cli be used

``` toml
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
```
```
cargo install --git https://github.com/rustwasm/wasm-bindgen wasm-bindgen-cli
```

I installed wasm-bingen-cli globally like that, but the cached version is still being run. I don't know why it decided to pick to use 0.2.19 for August of 2018 https://github.com/rustwasm/wasm-bindgen/commit/d9bc0a3176d06d6ad4bd0c843d32a346e3ecc99e.

```
$HOME/Library/Caches/.wasm-pack/wasm-bindgen-57f6f6a265a0d2ec/wasm-bindgen --version
wasm-bindgen 0.2.19 (d9bc0a317)
```

I tried to clear it out with `rm -rf $HOME/Library/Caches/.wasm-pack`, but it downloaded the same old version. I'm confused how to make it use the `was-bindgen-cli` that I installed.

**Comment by Pauan** [comment]
This seems like the same issue as https://github.com/rustwasm/wasm-pack/issues/853, and the solution is to [use `[patch]`](https://github.com/rustwasm/wasm-pack/issues/853#issuecomment-638624480) to override the version of wasm-bindgen.

Specifying `wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }` won't work, because it won't affect any of your dependencies, whereas `[patch]` does.
