### ISSUE TITLE
`wasm-pack build` creates incomplete file list in package.json

### ISSUE THREAD

**Issue by PSeitz** [rustwasm/wasm-pack#866]
## 🐛 Bug description
`wasm-pack build` creates incomplete file list in package.json.

`lz4_wasm_bg.js` is missing in package.json, but is referenced in `lz4_wasm.js` (`export * from "./lz4_wasm_bg.js"`)

#### 👟 Steps to reproduce

`git clone https://github.com/PSeitz/lz4_flex`
`cd lz4-wasm`
`wasm-pack build`
`wasm-pack pack`

"lz4_wasm_bg.js" is missing in package.json, but is referenced in "lz4_wasm.js" (`export * from "./lz4_wasm_bg.js"`). 
Manually adding the file to the list solves the issue.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: wasm-pack 0.9.1
rustc version: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)

**Comment by lucashorward** [comment]
Same issue as #881, and should also be resolved through #839, but that hasn't been released as a new version yet.
