### ISSUE TITLE
wasm-pack test not finding any tests in github actions

### ISSUE THREAD

**Issue by quodlibetor** [rustwasm/wasm-pack#867]
## 🐛 Bug description
I'm trying to migrate chrono to github actions (travis has been slow and occasionally not running tests at all) and `wasm-pack test` is stating that it cannot find any tests to run, in general with output like:

```text
Running target/wasm32-unknown-unknown/debug/deps/chrono-2353a41ba80b30bd.wasm
  no tests to run!
                                                    
       Running target/wasm32-unknown-unknown/debug/deps/wasm-f535679846a85bc5.wasm
  no tests to run!
```

These tests _do_ run when I run wasm-pack locally.

Here's a minimal run that demonstrates the issue: https://github.com/chronotope/chrono/runs/814496812?check_suite_focus=true

#### 🤔 Expected Behavior

`wasm-pack test` should execute my tests.

#### 👟 Steps to reproduce

My github-actions config is in https://github.com/chronotope/chrono/pull/436 , it seems straightforward, I'm happy to work to try and figure out why no tests are discovered. I've been trying to narrow it down and can't find anything. My sanity-check wasm test is in [`tests/wasm.rs`](https://github.com/chronotope/chrono/blob/master/tests/wasm.rs)

#### 🌍 Your environment
github-actions runner: macos-latest and ubuntu-latest
wasm-pack version: 0.9.1
rustc version: stable - 1.44.1

**Comment by schell** [comment]
I _was_ seeing this as well, and it _was_ happening locally. It didn't seem to matter where I put my tests - they were never found. Bumping `wasm_bindgen_test` from `0.3.0` to `0.3.17` fixed it.

**Comment by quodlibetor** [comment]
Ah, yes I forgot that I filed this: wasm-bindgen *0.2* requires wasm-bindgen-test *0.3*.
