### ISSUE TITLE
wasm-pack fails to locate wasm-opt in PATH

### ISSUE THREAD

**Issue by Erk-** [rustwasm/wasm-pack#869]
## 🐛 Bug description
wasm-pack does not search PATH for wasm-opt, at least not on targets where there is no prebuilt binary

#### 🤔 Expected Behavior
wasm-pack should find wasm-opt in PATH

#### 👟 Steps to reproduce
Not sure if this is specific to FreeBSD or if it also happens on other operating systems.
- run wasm-pack
- observe it fails because wasm-opt is not available
- install wasm-opt
- run wasm-pack
- observe that it does not find wasm-opt even though it is in path.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.44.1 (FreeBSD ports version)
FreeBSD version: FreeBSD 12.1-RELEASE-p3 GENERIC  amd64
wasm-opt version: 93

**Comment by hyd-dev** [comment]
Same for me (on Fedora). I believe it does not search for `wasm-opt` [at all](https://github.com/rustwasm/wasm-pack/blob/9f9634ca9ffa9147c044f947a31808f02715aa44/src/wasm_opt.rs#L57-L68). The comment that is above that finding function seems to be out of date, and the function itself seems not to be complete.

**Comment by ctron** [comment]
This is pretty annoying as the download for wasm-opt fails now on linux (amd64)

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
