### ISSUE TITLE
Error running 'wasm-pack-init.exe'

### ISSUE THREAD

**Issue by diassynthesis** [rustwasm/wasm-pack#878]
![wasm-pack](https://user-images.githubusercontent.com/3822648/87835479-8a08d500-c88d-11ea-8fa6-e30b5d150caf.PNG)
error message: Failed to find an installation of 'rustup' in 'path'. is rustup already installed? 

Known that rustup is installed.

**Comment by funkyfliam** [comment]
I had the same issue. Confirmed r`ustup.exe` is installed and the directory is included in system and user path.
A workaround for me was to copy `wasm-pack-init.exe` into the directory with `rustup.exe` and run it there

**Comment by Vanilagy** [comment]
@funkyfliam Thanks! Worked for me.

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
