### ISSUE TITLE
wasm-pack install issue

### ISSUE THREAD

**Issue by pravinparab** [rustwasm/wasm-pack#884]
Hi,

While running cargo install wasm-pack command, I am facing below issue

  Updating crates.io index
warning: spurious network error (2 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)
warning: spurious network error (1 tries remaining): [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)
error: failed to download from `https://crates.io/api/v1/crates/wasm-pack/0.9.1/download`

Caused by:
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.)

**Comment by pravinparab** [comment]
Hi,

Any update

**Comment by drager** [comment]
Please try out v0.12.0 from one of the following ways:
* https://github.com/rustwasm/wasm-pack/releases/tag/v0.12.0
* https://crates.io/crates/wasm-pack/0.12.0
* https://www.npmjs.com/package/wasm-pack/v/0.12.0
