### ISSUE TITLE
DevServer doesn't serve sub paths

### ISSUE THREAD

**Issue by DerKnerd** [rustwasm/wasm-pack#890]
## 🐛 Bug description
When I try to access the url `http://localhost:8000/content` the JavaScript files get served correctly as seen in this screenshot:

[![Correctly served javascript files][1]][1]

On the other hand, when I try to access `http://localhost:8000/content/files` the JavaScript files are not served and the dev server returns a 404. Again see the screenshot:

[![Not served javascript files][2]][2]

This is my webpack configuration:

```
const path = require('path');
const WasmPackPlugin = require('@wasm-tool/wasm-pack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const distPath = path.resolve(__dirname, "dist");
module.exports = (env, argv) => {
  return {
    devServer: {
      contentBase: distPath,
      compress: argv.mode === 'production',
      port: 8000,
      historyApiFallback: true,
    },
    entry: './bootstrap.js',
    output: {
      path: distPath,
      filename: "jinya.js",
      webassemblyModuleFilename: "jinya.wasm"
    },
    plugins: [
      new CopyWebpackPlugin([
        { from: './static', to: distPath }
      ]),
      new WasmPackPlugin({
        crateDirectory: ".",
        extraArgs: "--no-typescript",
      })
    ],
    watch: argv.mode !== 'production'
  };
};

```

  [1]: https://i.stack.imgur.com/Xb8Kz.png
  [2]: https://i.stack.imgur.com/LmQIZ.png

#### 🤔 Expected Behavior
Sub path should served.

#### 👟 Steps to reproduce
You can check out [this repo](https://github.com/DerKnerd/yew-router-sample) and then access the route http://localhost:8000/some/route

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.44.1
webpack: 4.42.0
webpack-dev-server: 3.10.3

**Comment by robertIngrum** [comment]
@DerKnerd did you ever end up finding a fix/workaround for this? I'm running into the same issue now.

**Comment by DerKnerd** [comment]
@robertIngrum sadly not, I replaced webpack with rollup and use an nginx to serve the files. Works like a charm. You can check the config here: https://github.com/Jinya-CMS/jinya-designer

**Comment by robertIngrum** [comment]
Thanks @DerKnerd, I'll take a look. Started implementing a router in rust, but it's slow going.
