### ISSUE TITLE
build failed when converting .rs to .wasm

### ISSUE THREAD

**Issue by SimonWang9610** [rustwasm/wasm-pack#900]
## 🐛 Bug description
When I followed the official document `Rust and WebAssembly` and coded the example `Conway's Game of Life`, I failed to  run `wasm-pack build`. Error Message as below:

`Fatal: error in validating input`
`Error: failed to execute ``wasm-opt``: exited with exit code: 1`
  `full command: "C:\\Users\\Simon\\AppData\\Local\\.wasm-pack\\wasm-opt-171374efd61df962\\wasm-opt.exe" "C:\\projects\\learn-rust\\wasm-game-of-life\\pkg\\wasm_game_of_life_bg.wasm" "-o" "C:\\projects\\learn-rust\\wasm-game-of-life\\pkg\\wasm_game_of_life_bg.wasm-opt.wasm" "-O"
To disable ``wasm-opt``, add ``wasm-opt = false`` to your package metadata in your ``Cargo.toml`.`

Even though I disabled `wasm-opt = false`, the compiled process was passed but it failed to work with the glue code. I mean, run `npm run start` it did not work as expected.

the Rust code is the same as the example in the Doc `Rust and WebAssembly`.

#### 🤔 Expected Behavior
I want to know it is a bug? or something wrong I did?
I am totally a beginner on Rust & WebAssembly, hope you guys can help me.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: `wasm-pack 0.9.1`
rustc version: `rustc 1.45.0 (5c1f21c3b 2020-07-13)`
`wee_alloc` version: `0.4.5`
`wasm-bindgen` version: `0.2.63`
`opt-level`: `'s'`

Platform: `Windows 10`
IDE: `VS code`

**Comment by fermezz** [comment]
+1 here. Also very new to Rust/WASM. I was able to track down the error as coming from the `render` function for `Universe`. Apparently it's crashing because we return a String into Javascript? I tried commenting that function and it compiles fine. Also, I tried adding a totally unrelated 

```
#[wasm_bindgen]
pub fn greet() -> String {
    format!("Hello")
}
```
function and the compilation error returned.

If you remove the `#[wasm_bindgen]` attribute, compilation goes back to normal.

**Comment by fermezz** [comment]
Problably related to https://github.com/rustwasm/wasm-bindgen/issues/2279

**Comment by fermezz** [comment]
@SimonWang9610 you should be able to run `cargo install --version 0.8.1 wasm-pack --force` to go back to `wasm-pack` `0.8.1` version, that's the last one I find this to be compiling correctly.

**Comment by SimonWang9610** [comment]
> @SimonWang9610 you should be able to run `cargo install --version 0.8.1 wasm-pack --force` to go back to `wasm-pack`'s `0.8.1` version, that's the last one I find this to be compiling correctly.



> @SimonWang9610 you should be able to run `cargo install --version 0.8.1 wasm-pack --force` to go back to `wasm-pack`'s `0.8.1` version, that's the last one I find this to be compiling correctly.

Yeah, I tried your method. The compile process is passed, but the program did not work as expected. Like you said, probably because the returned value is `String`. 
Thanks!

**Comment by fermezz** [comment]
@SimonWang9610 It should work if compiled successfully. It works for me, at least.

**Comment by SimonWang9610** [comment]
@fermezz but actually no. If I comment ` pun fn render() -> String {}`, the compile is successful, and other functions work well. 
if the function is `pub` and returns `String` type, the compiler will terminate at `error in validating input`.
if the function is not `pub` and return `String` type, the compiler works well.
all functions that return `number` like `i32, u32, u8, f32` also work well.

So i am pretty sure there are some problems related to convert `String` from rust to wasm to JavaScript.

**Comment by fermezz** [comment]
@SimonWang9610 oh, yeah, totally. I meant that if you leave the render function untouched but downgrade the version for wasm-pack to 0.8.1 (instead of 0.9.1) you can compile successfully _and_ have it working as expected.

**Comment by alvinhochun** [comment]
This is probably the same issue as https://github.com/rustwasm/wasm-pack/issues/886. A workaround is mentioned in https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-667669802.

**Comment by ashleygwilliams** [comment]
closing as duplicate
