### ISSUE TITLE
OS error 13 on installing.

### ISSUE THREAD

**Issue by PortStone** [rustwasm/wasm-pack#905]
## 🐛 Bug description
I can't install it.

```
failed to copy executable to `/usr/bin/wasm-pack`
Caused by: Permission denied (os error 13)
```

#### 🤔 Expected Behavior
It should have moved the binary to /usr/bin/wasm-pack

#### 👟 Steps to reproduce
`sudo curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: I guess that link installs the latest version
rustc version: rustc 1.45.2 (d3fb005a3 2020-07-31)

**Comment by jeffvandyke** [comment]
Same, here's my output:
```
info: downloading wasm-pack
failed to copy executable to `/usr/bin/wasm-pack`
Caused by: Permission denied (os error 13)
./init.sh: line 20: 185011 Segmentation fault      (core dumped) "$_wasmpackinit" "$@" < /dev/tty
```

**Comment by timburrows** [comment]
As a current alternative you could install via your package manager.
For example:

`yay -S wasm-pack`

**Comment by jeffvandyke** [comment]
I ended up using `cargo install wasm-pack` - re-built binary, took around 5 minutes, but worked. If this script can't be fixed (which seems like a permission or an install location issue), then wasm-pack's install page (<https://rustwasm.github.io/wasm-pack/installer/>) should show other working alternatives besides the one broken script for Linux systems.

**Comment by 0x6273** [comment]
> `sudo curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`

This is incorrect. You are running curl as root, and sh as a normal user, which is the opposite of what you want.
The correct command would be `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sudo sh`

**Comment by PortStone** [comment]
> > `sudo curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh`
> 
> This is incorrect. You are running curl as root, and sh as a normal user, which is the opposite of what you want.
> The correct command would be `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sudo sh`

You are right I didn't saw my error. It now works, thank you.
