### ISSUE TITLE
Vite is not supported. How should I fix it

### ISSUE THREAD

**Issue by shijunti19** [rustwasm/wasm-pack#911]
## 🐛 Bug description
https://github.com/vitejs/vite
```js
const rust = import("../pkg/a031.js");
rust
  .then((m) => {
    console.log(m);
    m.greet("hello");
  })
  .catch(console.error);
```
a031_bg.js:44 Uncaught TypeError: malloc is not a function
#### 🤔 Expected Behavior
What should have happened?

#### 👟 Steps to reproduce
Clear steps describing how to reproduce the issue, including commands and flags run. If you are seeing an error, please include the full error message and stack trace.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version:
rustc version:

**Comment by ashleygwilliams** [comment]
hello! i'm not sure what you are trying to achieve here. i'm going to close this issue but if you can add more info i can try to help you debug.

**Comment by kabouzeid** [comment]
I have the same problem. Just want to use the code in my vite app.

`import { my_rust_func } from "../pkg/my_rust_lib.js";`

I'm also getting
`Uncaught TypeError: malloc is not a function`

**Comment by gliheng** [comment]
You have to use wasm-pack build --target web

**Comment by Septias** [comment]
The approach used in `https://rustwasm.github.io/docs/book/introduction.html` is that you add your `pkg` as a dependency in your package.json file:
```json 
{ 
  },
  "dependencies": {
    "rust_lib": "../backend/pkg"
  },
}
```
But that doesn't work for me with Vite because `TypeError: wasm.greet is not a function`
The approach that works is as @gliheng mentioned to export for web and then use it as it says on the Vite website:
https://vitejs.dev/guide/features.html#webassembly
```js
import init, {greet} from './example.wasm'

init().then((_exports) => {
  greet()
})
```

**Comment by Niedzwiedzw** [comment]
@gliheng  and what then?

**Comment by winston0410** [comment]
@gliheng After I have do that, I am getting this error:

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
```

I guess there is something more need to be done for fixing this?

**Comment by Menci** [comment]
I just created a Vite plugin to work with wasm-pack generated wasm in the bundler mode: https://github.com/Menci/vite-plugin-wasm

**Comment by Septias** [comment]
Does it support ssg? @Menci

**Comment by Menci** [comment]
> Does it support ssg? @Menci

VitePress? It works in VitePress.
