### ISSUE TITLE
Bundled wasm-opt fails

### ISSUE THREAD

**Issue by lukaslueg** [rustwasm/wasm-pack#912]
wasm-pack 0.9.1 fails to run wasm-opt when building https://github.com/lukaslueg/macro_railroad_wasm

```
[wasm-validator error in module] unexpected true: Exported global cannot be mutable, on 
global$0
Fatal: error in validating input
Error: failed to execute `wasm-opt`: exited with exit code: 1
```

wasm-pack was able to run `wasm-opt` before, I guess the problem was introduced with recent updates of Rust, although I didn't run a regression.

To reproduce, clone the repo and run `wasm-pack build --target web`

wasm-pack version: 0.9.1
rustc version: 1.46

**Comment by lukaslueg** [comment]
I'm closing this here, as after some more testing I suspect something fishy in rustc itself, which used to not get picked up by the wasm-opt verifier.

**Comment by lukaslueg** [comment]
Turns out the behavior was introduced with `wasm-bindgen` >= 0.26.26, which generates the aforementioned mutable global, which causes `wasm-opt` to puke. According to [this](https://github.com/rust-lang/rust/issues/76404#issuecomment-687767377) comment, mutable globals are now stable and the bundled `wasm-opt` 90 (and 96) is not up to par.

I reopen this again, as `wasm-opt` will need to get updated or everybody using `wasm-opt` as part of `wasm-pack` who runs into this behavior will have their build broken.

**Comment by JHBonarius** [comment]
This is a duplicate of [this bug](https://github.com/rustwasm/wasm-pack/issues/886)

**Comment by lukaslueg** [comment]
aaaaannd it's closed again :-) Thanks for the heads-up
