### ISSUE TITLE
Add support for wasm-bindgen --weak-refs flag

### ISSUE THREAD

**Issue by mmgeorge** [rustwasm/wasm-pack#930]
## 💡 Feature description
The wasm-bindgen [--weak-refs](https://rustwasm.github.io/docs/wasm-bindgen/reference/weak-references.html) flag adds support for using TC39 Weak References proposal to garbage collect rust objects avoiding the need to explicitly call `free`. Currently this is [supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry) on major browsers with the exception of Safari. 

It would be great if we could pass this down to wasm-bindgen using wasm-pack.

**Comment by bes** [comment]
Safari 14.1 added support for weak refs. Safari 14.1 was released April 26, 2021.

This feature would be very appreciated 👍
