### ISSUE TITLE
wasm-pack prints wat syntax for a very long time

### ISSUE THREAD

**Issue by Mipsters** [rustwasm/wasm-pack#938]
## 🐛 Bug description
wasm-pack build prints to console what I think is `wat`

#### 🤔 Expected Behavior
build the project
not print `wat` code to console?

#### 👟 Steps to reproduce
clone my repo https://github.com/Mipsters/html5ever-wasm
run `wasm-pack build`
wait for everything to compile
gits of result is linked at the bottom

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: rustc 1.48.0 (7eac88abb 2020-11-16)

using git bash, powershell or cmd didn't matter
it worked at some point, but then this happened

was actually using this version https://github.com/rustwasm/wasm-pack/pull/908
and it worked pretty good for me except something weird that has nothing to do with this bug
and then this thing happened
and then I checked the regular version to see if it happened there too and it did

partial build log: https://gist.github.com/Mipsters/48511bc1926e3eaaaa5f132425834013

**Comment by Mipsters** [comment]
the problem lies in the `test` function
it also happens when it only contains
``` Rust
#[wasm_bindgen]
pub fn test(doc: &str) -> String {
    let mut out = Vec::new();
    return String::from_utf8(out).unwrap();
}
```

and I remove the square function

**Comment by juzi5201314** [comment]
hi, I think you seem to have encountered this bug: #886.
I have encountered it once and solved it based on this: https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-667669802

**Comment by ashleygwilliams** [comment]
@Mipsters was @juzi5201314's suggestion able to address your issue? i'm going to close, but if you need more help please follow up
