### ISSUE TITLE
release a new version

### ISSUE THREAD

**Issue by gengjiawen** [rustwasm/wasm-pack#951]
https://github.com/rustwasm/wasm-pack/pull/839
This fix has been merged for a while, but it's also a year without new release.
Can we draft a new release to fix related issues.

@ashleygwilliams

**Comment by Zageron** [comment]
> 
> 
> #839
> This fix has been merged for a while, but it's also a year without new release.
> Can we draft a new release to fix related issues.
> 
> @ashleygwilliams

`cargo install --git https://github.com/rustwasm/wasm-pack wasm-pack`

**Comment by lucperkins** [comment]
A big +1 to a new release. The `bundler` target issue bit me as well. Given how trivial it is issue a new release, the lack of one indicates to me that `wasm-pack` is essentially abandonware.

**Comment by Zageron** [comment]
@danwilhelm Sorry for the direct at, but you are the only person listed under people that seems to be active. Any news on this repository?

**Comment by danwilhelm** [comment]
@Zageron I have not kept up with the project's status. I would recommend reaching out to Rust's WASM working group, which has a very active channel `#wg-wasm` on [Rust's official Discord server](https://discordapp.com/invite/rust-lang).

**Comment by Zageron** [comment]
> @Zageron I have not kept up with the project's status. I would recommend reaching out to Rust's WASM working group, which has a very active channel `#wg-wasm` on [Rust's official Discord server](https://discordapp.com/invite/rust-lang).

Thank you very much. :)

**Comment by turboladen** [comment]
FWIW, I did some poking around and it does seem a bit like this project is abandoned for now.

* https://github.com/rustwasm/team/issues/294
* https://github.com/rustwasm/wasm-bindgen/issues/2337#issuecomment-716075906

**Comment by drager** [comment]
New release planned in #1020
