### ISSUE TITLE
Unable to disable wasm-opt

### ISSUE THREAD

**Issue by darkoverlordofdata** [rustwasm/wasm-pack#956]
## 🐛 Bug description
Unable to disable wasm-opt

#### 🤔 Expected Behavior
I expect the compiler to not use wasm-opt

#### 👟 Steps to reproduce
follow the tutorial at https://rustwasm.github.io/docs/book/game-of-life/introduction.html. 
when I run wasm-pack build it gets to the end and fails:
```
    Finished release [optimized] target(s) in 45.05s
[INFO]: Installing wasm-bindgen...
Error: no prebuilt wasm-opt binaries are available for this platform: Unrecognized target!
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
```

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.49.0 (e1884a8e3 2020-12-29)

Im running on GhostBSD (12.2-STABLE FreeBSD 12.2-STABLE GENERIC  amd64 amd64 GENERIC).
I'm trying to follow the wasm hello world tutorial. It fails to find wasm-opt. 
I disable wasm-opt and it still fails with the same message.

toml:
```
[package]
name = "wasm-game-of-life"
version = "0.1.0"
authors = ["darkoverlordofdata <darkoverlordofdata@gmail.com>"]
edition = "2018"

[package.metadata]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "0"
```

**Comment by darkoverlordofdata** [comment]
Sorry - the last line on the toml should say opt-level = "s"

The last thing I tried was this: [Select Optimization Level ](https://bytecodealliance.github.io/cargo-wasi/wasm-opt.html#selected-optimization-level) which gave me a different error. I changed it back but the error report I was writing still had the prior version of toml in it.

**Comment by darkoverlordofdata** [comment]
So, after dinner, I decided to try thiis again. I deleted the target folder and recompiled. Again, I get the same error. But I look through the pkg folder and everything is there except package.json. So I copied that from the documentation.  VSCode tells me that the null should be "". I fix that, and continue with the tutorial, and now it all works.

So, between evil instructions,  error message that may not be errors, and missing output files, I'm not  sure if it's working right or not. How am I supposed to tell?

**Comment by darkoverlordofdata** [comment]
Wait - there's more - this project runs with npm start. But I want to run it on a web server.
from the folder wasm-gameof-life/www:
 
I tried python3 -m http.server
I tried basic-http-server installed from cargo
I tried the Web Server for Chrome app
I tried http-server installed from npm

It get's the same on all:

Error importing `index.js`: TypeError: Failed to resolve module specifier "wasm-game-of-life". Relative references must start with either "/", "./", or "../"

I don't get it. How does this run if I'm targetting running on the web? Isn't that the point of this? What am I missing about rust+wasm?

**Comment by darkoverlordofdata** [comment]
Ah, I found this answer in a totally separate document - https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#bundlers
"This model, however, is not natively implemented in any JS implementation at this time"

Aiy Aiy Aiy, Help me Zordon!

I think I had the wrong impression of rustwasm - for some reason I thought it might be robust or ready for production or something like that. Everything about rust takes longer and takes the longest route to get there. I'm sticking with c++.

**Comment by protheory8** [comment]
@darkoverlordofdata 
Answer to your first question:
You're supposed to do
```toml
[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```
instead of
```toml
[package.metadata]
wasm-opt = false
```
in `Cargo.toml` as described in https://rustwasm.github.io/docs/wasm-pack/cargo-toml-configuration.html

Answer to second question:
"This model, however, is not natively implemented in any JS implementation at this time" is not related to your issue whatsoever, it's talking about why can't you use `bundler` target without using a bundler like Webpack.

To make it work, compile your project with `wasm-pack build --target web`, create `static` directory, move `pkg` directory into `static` directory and rename it to `wasm-game-of-life`, then copy `index.html` and `index.js` from `www` to `static` directory, then finally change the first line of `index.js` from `import { Universe, Cell } from "wasm-game-of-life";` to `import { Universe, Cell } from "wasm-game-of-life/wasm_game_of_life";` Use any web server to serve the contents of the `static` directory.

Whatever is inside `www` is a premade Node web server to serve the project, that's why it runs with `npm start`.
