### ISSUE TITLE
There should be a way to disable `sideEffects: false`

### ISSUE THREAD

**Issue by RReverser** [rustwasm/wasm-pack#972]
## 🐛 Bug description

Custom JS snippets can contain top-level side-effects. Right now, wasm-pack generated package.json includes `sideEffects: false` which marks every file as side-effect free, leading to potential bugs after bundling.

#### 🤔 Expected Behavior

When JS snippet files are generated, they should be put into the `sideEffects` array, and only the JS file generated by wasm-bindgen should be assumed to be side-effect free since it's the only one wasm-bindgen has control over.

`package.json` allows to list potentially side-effect-y files as

```json
{
  "sideEffects": [
    "path/to/snippet.js"
  ]
}
```

This will avoid bugs for snippets with top-level side-effects, while it won't decrease optimization level for common scenarios where the module is used via its main entry point.

**Comment by stephanemagnenat** [comment]
The problem is even worst than this. Because of side effects are ignored by default, the "main" Rust function annotated with `#[wasm_bindgen(start)]` is sometimes not called, because the call to `wasm.__wbindgen_start();` in `index.js` is dropped during tree shaking. See #989.
