### ISSUE TITLE
Fix or remove Travis

### ISSUE THREAD

**Issue by palfrey** [rustwasm/wasm-pack#979]
## 🐛 Bug description

https://github.com/rustwasm/wasm-pack/pull/966 has had "Test (linux-stable) Expected — Waiting for status to be reported" for almost a month now. As the issue name suggests, we should either fix the Travis build, or kill it entirely in favour of something else. I'm pro killing it entirely TBH, given the current state of Travis. I see @ashleygwilliams was looking at Github Actions for this about a year ago in https://github.com/rustwasm/wasm-pack/pull/772#issuecomment-589803455 ?

#### 🤔 Expected Behavior

Build should be green

#### 👟 Steps to reproduce

Open a PR!

**Comment by palfrey** [comment]
https://github.com/rustwasm/wasm-pack/pull/947 looks promising?

**Comment by drager** [comment]
Fixed in #947.
