### ISSUE TITLE
wasm-pack Build Errors

### ISSUE THREAD

**Issue by samDalton1** [rustwasm/wasm-pack#982]
## 🐛 Bug description
wasm-pack build --target no-modules

Here is some of the errors that I get.  It seems that it can't compile mio crate:

![image](https://user-images.githubusercontent.com/79739396/109378024-405d7f80-789d-11eb-8861-f37ad3057768.png)

#### 🤔 Expected Behavior
Should build successfully

#### 👟 Steps to reproduce
Here is my Cargo.toml file:

![image](https://user-images.githubusercontent.com/79739396/109378077-992d1800-789d-11eb-940b-7189acbcbf43.png)

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
rustc version: 1.50.0

I have tested in Windows and Ubuntu and get the same error in both.

**Comment by xhalo32** [comment]
Hi!

Mio currently doesn't support building to wasm32.

See this [similar issue](https://github.com/tokio-rs/mio/issues/642).
