### ISSUE TITLE
Is the `#[wasm_bindgen(start)]` attribute deprecated with Webpack 5 and sync import?

### ISSUE THREAD

**Issue by stephanemagnenat** [rustwasm/wasm-pack#989]
## 🐛 Bug description
I am using Rust along with wasm-bindgen, wasm-pack and wasm-pack-plugin to embed some Rust code in my Typescript-based app. I build the app using Webpack 5. I set this up around two years ago, following a wasm-bindgen guide, and it worked well including a "main" `main_js() -> Result<(), JsValue>` function with a `console::log_1` in it to test the loading of my wasm helper.

Recently, I noticed that this function is not called any more. The rest works fine. In the [documentation](https://rustwasm.github.io/docs/wasm-pack/tutorials/hybrid-applications-with-webpack/using-your-library.html), I see that now the import should be done the following way: `import("../crate/pkg").then(module => { module.run(); });` which hints to me that the run/main method of the module must be executed explicitly. I'm currently simply importing using `import { func1, ..., funcN } from 'path/pkg';`. So I am confused, did the specification about `#[wasm_bindgen(start)]` change?

I am also building another version of this helper to be used with Jest using `npx wasm-pack build --target nodejs --out-dir pkg-node` and in that case the main function is executed.

I certainly missed something but after thorough search I did not find it, so I submit a bug.

#### 🤔 Expected Behavior
The main function should be called in all cases.

#### 👟 Steps to reproduce
Create a simple project with the following code in `lib.rs`:
```rust
pub fn test() -> u32 {
    0
}

[wasm_bindgen(start)]
pub fn main_js() -> Result<(), JsValue> {
    console::log_1(&JsValue::from_str("Hello from Rust!"));
    Ok(())
}
```

integrate it with Webpack 5, using the following configuration:
```javascript
plugins: [
		new WasmPackPlugin({
			crateDirectory: path.resolve(__dirname, PATH),
			forceMode: "production"
		}),
],
experiments: {
		syncWebAssembly: true
}
```

import it with 
```typescript
import { test } from 'PATH/pkg';
```

the main function is not called when built with Webpack.

I did not re-created a test project because I expect I missed something, but if it seems I did not, I'll create one.

#### 🌍 Your environment
Include the relevant details of your environment.
wasm-pack version: 0.9.1
wasm-pack-plugin version: 1.3.3
rustc version: 1.50.0
webpack version: 5.20.2

**Comment by protheory8** [comment]
@stephanemagnenat It's supposed to be `#[wasm_bindgen(start)]` and not `[wasm_bindgen(start)]`, I'm not sure if this is the problem though, what is in your entry JS file?

**Comment by stephanemagnenat** [comment]
Thank you for the answer! I did forgot the `#` in the issue example, sorry for that, but not in the code, it is there. The whole thing also worked for quite a while before recently.

By entry JS file, do you mean the generated `index.js` file for the module? If so, here is the content:
```javascript
import * as wasm from "./index_bg.wasm";
export * from "./index_bg.js";
wasm.__wbindgen_start();
```

Here is how I use the library:
```typescript
import { function1, ... , functionN } from 'wasmhelpers/pkg';
```
As I'm using `syncWebAssembly: true` in Webpack, the Typescript module that is using wasm must itself be loaded asynchronously, which I do very early on in a `bootstrap.ts` file looking like this:
```typescript
async function init() {
	try {
		// working around webpack bug with WASM, see https://github.com/webpack/webpack/issues/6615
		await import('./app');
	} catch (e) {
		console.error('Error importing `app.ts`:', e);
	}
}
void init();
```
Could it be that the old `syncWebAssembly: true` approach is broken now Webpack 5?

The wasm itself seems correct:
```sh
wasm-objdump index_bg.wasm -x | rg __wbindgen_star
```
shows:
```
 - func[170] <main_js> -> "__wbindgen_start"
```
And it works with node when built for the `nodejs` target.

So my guess is that somewhat is broken on the Webpack side.

**Comment by protheory8** [comment]
Is `./app` a directory with the Wasm file and JS glue code? My code works fine, the function that is marked with `#[wasm_bindgen(start)]` is getting automatically and I use Webpack 5.

**Comment by protheory8** [comment]
But to be fair I also use `asyncWebAssembly` instead of `syncWebAssembly`
```json
experiments: {
    asyncWebAssembly: true
},
```

**Comment by protheory8** [comment]
Not sure if this is gonna help, but here are configs from my project (I copied most of it from Yew template though, but it does work without it):

`/webpack.config.js`:
```js
experiments: {
    asyncWebAssembly: true
},
entry: "./index.js",
output: {
    path: path.resolve(__dirname, "dist"),
    filename: "index.js",
    webassemblyModuleFilename: "main.wasm"
},
plugins: [
    new WasmPackPlugin({
        crateDirectory: "."
    })
]
```
`/index.js`:
```js
import("./pkg");
```
`/Cargo.toml` and `/src/`:
Manifest file and the source code of the Rust crate.

**Comment by stephanemagnenat** [comment]
Thanks for the help!

> Is ./app a directory with the Wasm file and JS glue code?

No, that is the user code, the Wasm file and its glue code are in a another directory.

As your setup works, as a next step I'll try to create a minimal reproducible test case of my problem.

**Comment by protheory8** [comment]
In my case `./pkg` refers to the directory where Wasm file and JS glue code is located.

**Comment by stephanemagnenat** [comment]
Yes, for me as well.

**Comment by stephanemagnenat** [comment]
I found the issue (finally): the generated `package.json` has the property `"sideEffects"` to `false` by default. But that tells WebPack that it can tree shake the module, and in particular ignore the code in the top-level of `index.js`, which is the one calling `wasm.__wbindgen_start();`. This is in effect a duplicate of #972.

**Comment by stephanemagnenat** [comment]
I'm closing in favor of #972 as that is the root cause.
